/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreateCustomer } from "../funcs/customersCreateCustomer.js";
import { customersGenerateBillingLinks } from "../funcs/customersGenerateBillingLinks.js";
import { customersList } from "../funcs/customersList.js";
import { customersListCustomerLicenses } from "../funcs/customersListCustomerLicenses.js";
import { customersListCustomerOrders } from "../funcs/customersListCustomerOrders.js";
import { customersListCustomerSubscriptions } from "../funcs/customersListCustomerSubscriptions.js";
import { customersRetrieve } from "../funcs/customersRetrieve.js";
import { customersUpdateCustomer } from "../funcs/customersUpdateCustomer.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Customers extends ClientSDK {
  /**
   * List all customers
   *
   * @remarks
   * Retrieve a paginated list of all customers. Filter and search through your customer base.
   */
  async list(
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.CustomerListEntity> {
    return unwrapAsync(customersList(
      this,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * Retrieve a customer
   *
   * @remarks
   * Retrieve customer information by ID or email. View purchase history, subscriptions, and profile details.
   */
  async retrieve(
    customerId?: string | undefined,
    email?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.CustomerEntity> {
    return unwrapAsync(customersRetrieve(
      this,
      customerId,
      email,
      options,
    ));
  }

  /**
   * Generate Customer Links
   *
   * @remarks
   * Generate a customer portal link for managing billing, subscriptions, and payment methods.
   */
  async generateBillingLinks(
    request: components.CreateCustomerPortalLinkRequestEntity,
    options?: RequestOptions,
  ): Promise<components.CustomerLinksEntity> {
    return unwrapAsync(customersGenerateBillingLinks(
      this,
      request,
      options,
    ));
  }

  /**
   * List customer orders
   *
   * @remarks
   * Retrieve a paginated list of orders for a specific customer.
   */
  async listCustomerOrders(
    id: string,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.OrderListEntity> {
    return unwrapAsync(customersListCustomerOrders(
      this,
      id,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * List customer subscriptions
   *
   * @remarks
   * Retrieve a paginated list of subscriptions for a specific customer.
   */
  async listCustomerSubscriptions(
    id: string,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.SubscriptionListEntity> {
    return unwrapAsync(customersListCustomerSubscriptions(
      this,
      id,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * List customer licenses
   *
   * @remarks
   * Retrieve a paginated list of license keys for a specific customer.
   */
  async listCustomerLicenses(
    id: string,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.LicenseListEntity> {
    return unwrapAsync(customersListCustomerLicenses(
      this,
      id,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * Create a customer
   *
   * @remarks
   * Create a new customer record for the authenticated store.
   */
  async createCustomer(
    request: components.CreateCustomerRequestEntity,
    options?: RequestOptions,
  ): Promise<components.CustomerEntity> {
    return unwrapAsync(customersCreateCustomer(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a customer
   */
  async updateCustomer(
    request: components.UpdateCustomerRequestEntity,
    options?: RequestOptions,
  ): Promise<components.CustomerEntity> {
    return unwrapAsync(customersUpdateCustomer(
      this,
      request,
      options,
    ));
  }
}
