/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customerCreditsAccountsExperimentalCloseCustomerCreditsAccount } from "../funcs/customerCreditsAccountsExperimentalCloseCustomerCreditsAccount.js";
import { customerCreditsAccountsExperimentalCreateCustomerCreditsAccount } from "../funcs/customerCreditsAccountsExperimentalCreateCustomerCreditsAccount.js";
import { customerCreditsAccountsExperimentalCreditCustomerCreditsAccount } from "../funcs/customerCreditsAccountsExperimentalCreditCustomerCreditsAccount.js";
import { customerCreditsAccountsExperimentalDebitCustomerCreditsAccount } from "../funcs/customerCreditsAccountsExperimentalDebitCustomerCreditsAccount.js";
import { customerCreditsAccountsExperimentalFreezeCustomerCreditsAccount } from "../funcs/customerCreditsAccountsExperimentalFreezeCustomerCreditsAccount.js";
import { customerCreditsAccountsExperimentalGetCustomerCreditsAccount } from "../funcs/customerCreditsAccountsExperimentalGetCustomerCreditsAccount.js";
import { customerCreditsAccountsExperimentalGetCustomerCreditsAccountBalance } from "../funcs/customerCreditsAccountsExperimentalGetCustomerCreditsAccountBalance.js";
import { customerCreditsAccountsExperimentalListCustomerCreditsAccountEntries } from "../funcs/customerCreditsAccountsExperimentalListCustomerCreditsAccountEntries.js";
import { customerCreditsAccountsExperimentalListCustomerCreditsAccounts } from "../funcs/customerCreditsAccountsExperimentalListCustomerCreditsAccounts.js";
import { customerCreditsAccountsExperimentalReverseCustomerCreditsAccountTransaction } from "../funcs/customerCreditsAccountsExperimentalReverseCustomerCreditsAccountTransaction.js";
import { customerCreditsAccountsExperimentalUnfreezeCustomerCreditsAccount } from "../funcs/customerCreditsAccountsExperimentalUnfreezeCustomerCreditsAccount.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CustomerCreditsAccountsExperimental extends ClientSDK {
  /**
   * Create a customer credits account
   *
   * @remarks
   * Create a new credits account for a customer. Optionally seed it with an initial balance.
   */
  async createCustomerCreditsAccount(
    request: components.CreateAccountDto,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalCreateCustomerCreditsAccount(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * List customer credits accounts
   *
   * @remarks
   * List accounts for the authenticated store with cursor pagination. System accounts are excluded.
   */
  async listCustomerCreditsAccounts(
    limit?: number | undefined,
    customerId?: string | undefined,
    startingAfter?: string | undefined,
    endingBefore?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.AccountListResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalListCustomerCreditsAccounts(
        this,
        limit,
        customerId,
        startingAfter,
        endingBefore,
        options,
      ),
    );
  }

  /**
   * Retrieve a customer credits account
   *
   * @remarks
   * Get details of a customer credits account by ID.
   */
  async getCustomerCreditsAccount(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalGetCustomerCreditsAccount(
        this,
        id,
        options,
      ),
    );
  }

  /**
   * Get account balance
   *
   * @remarks
   * Get the current balance of an account. Optionally pass ?at= for historical balance.
   */
  async getCustomerCreditsAccountBalance(
    id: string,
    at?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.BalanceResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalGetCustomerCreditsAccountBalance(
        this,
        id,
        at,
        options,
      ),
    );
  }

  /**
   * List account entries
   *
   * @remarks
   * List the credit and debit history for an account with cursor pagination.
   */
  async listCustomerCreditsAccountEntries(
    id: string,
    limit?: number | undefined,
    startingAfter?: string | undefined,
    endingBefore?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.EntryListResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalListCustomerCreditsAccountEntries(
        this,
        id,
        limit,
        startingAfter,
        endingBefore,
        options,
      ),
    );
  }

  /**
   * Freeze an account
   *
   * @remarks
   * Freeze an account to prevent new transactions.
   */
  async freezeCustomerCreditsAccount(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalFreezeCustomerCreditsAccount(
        this,
        id,
        options,
      ),
    );
  }

  /**
   * Unfreeze an account
   *
   * @remarks
   * Unfreeze a frozen account to allow transactions again.
   */
  async unfreezeCustomerCreditsAccount(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalUnfreezeCustomerCreditsAccount(
        this,
        id,
        options,
      ),
    );
  }

  /**
   * Credit an account
   *
   * @remarks
   * Add credits to a customer account. Returns the resulting transaction record.
   */
  async creditCustomerCreditsAccount(
    id: string,
    creditDebitRequestDto: components.CreditDebitRequestDto,
    options?: RequestOptions,
  ): Promise<components.TransactionResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalCreditCustomerCreditsAccount(
        this,
        id,
        creditDebitRequestDto,
        options,
      ),
    );
  }

  /**
   * Debit an account
   *
   * @remarks
   * Deduct credits from a customer account. Returns the resulting transaction record.
   */
  async debitCustomerCreditsAccount(
    id: string,
    creditDebitRequestDto: components.CreditDebitRequestDto,
    options?: RequestOptions,
  ): Promise<components.TransactionResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalDebitCustomerCreditsAccount(
        this,
        id,
        creditDebitRequestDto,
        options,
      ),
    );
  }

  /**
   * Reverse a transaction
   *
   * @remarks
   * Reverse a previous credit or debit on this account. Creates a new transaction that undoes the original, preserving the full history.
   */
  async reverseCustomerCreditsAccountTransaction(
    id: string,
    reverseTransactionRequestDto: components.ReverseTransactionRequestDto,
    options?: RequestOptions,
  ): Promise<components.TransactionResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalReverseCustomerCreditsAccountTransaction(
        this,
        id,
        reverseTransactionRequestDto,
        options,
      ),
    );
  }

  /**
   * Close an account
   *
   * @remarks
   * Permanently close an account. This action cannot be undone.
   */
  async closeCustomerCreditsAccount(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AccountResponseDto> {
    return unwrapAsync(
      customerCreditsAccountsExperimentalCloseCustomerCreditsAccount(
        this,
        id,
        options,
      ),
    );
  }
}
