/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AcknowledgeWebhookEventRequestEntity = {
  /**
   * The HTTP status code the local server answered with. Any 2xx marks the delivery successful. Report 503 when the local server could not be reached.
   */
  statusCode: number;
  /**
   * The response body the local server returned, truncated to 10,000 characters. Shown in the dashboard event log.
   */
  responseBody?: string | undefined;
};

/** @internal */
export const AcknowledgeWebhookEventRequestEntity$inboundSchema: z.ZodType<
  AcknowledgeWebhookEventRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  status_code: z.number(),
  response_body: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
    "response_body": "responseBody",
  });
});
/** @internal */
export type AcknowledgeWebhookEventRequestEntity$Outbound = {
  status_code: number;
  response_body?: string | undefined;
};

/** @internal */
export const AcknowledgeWebhookEventRequestEntity$outboundSchema: z.ZodType<
  AcknowledgeWebhookEventRequestEntity$Outbound,
  z.ZodTypeDef,
  AcknowledgeWebhookEventRequestEntity
> = z.object({
  statusCode: z.number(),
  responseBody: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
    responseBody: "response_body",
  });
});

export function acknowledgeWebhookEventRequestEntityToJSON(
  acknowledgeWebhookEventRequestEntity: AcknowledgeWebhookEventRequestEntity,
): string {
  return JSON.stringify(
    AcknowledgeWebhookEventRequestEntity$outboundSchema.parse(
      acknowledgeWebhookEventRequestEntity,
    ),
  );
}
export function acknowledgeWebhookEventRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<AcknowledgeWebhookEventRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AcknowledgeWebhookEventRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AcknowledgeWebhookEventRequestEntity' from JSON`,
  );
}
