/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EnvironmentMode,
  EnvironmentMode$inboundSchema,
  EnvironmentMode$outboundSchema,
} from "./environmentmode.js";

export type AffiliateInviteEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: EnvironmentMode;
  /**
   * String representing the object's type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * The email address the affiliate was invited with.
   */
  email: string;
  /**
   * The display name the affiliate was invited with.
   */
  name?: string | null | undefined;
  /**
   * The lifecycle status of the invitation: `pending` while the invitee has not yet accepted, `accepted` once they have joined the program.
   */
  status: string;
  /**
   * Creation date of the invitation as a timestamp.
   */
  createdAt: number;
};

/** @internal */
export const AffiliateInviteEntity$inboundSchema: z.ZodType<
  AffiliateInviteEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$inboundSchema,
  object: z.string(),
  email: z.string(),
  name: z.nullable(z.string()).optional(),
  status: z.string(),
  created_at: z.number(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type AffiliateInviteEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  email: string;
  name?: string | null | undefined;
  status: string;
  created_at: number;
};

/** @internal */
export const AffiliateInviteEntity$outboundSchema: z.ZodType<
  AffiliateInviteEntity$Outbound,
  z.ZodTypeDef,
  AffiliateInviteEntity
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$outboundSchema,
  object: z.string(),
  email: z.string(),
  name: z.nullable(z.string()).optional(),
  status: z.string(),
  createdAt: z.number(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function affiliateInviteEntityToJSON(
  affiliateInviteEntity: AffiliateInviteEntity,
): string {
  return JSON.stringify(
    AffiliateInviteEntity$outboundSchema.parse(affiliateInviteEntity),
  );
}
export function affiliateInviteEntityFromJSON(
  jsonString: string,
): SafeParseResult<AffiliateInviteEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AffiliateInviteEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AffiliateInviteEntity' from JSON`,
  );
}
