/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AffiliateInviteEntity,
  AffiliateInviteEntity$inboundSchema,
  AffiliateInviteEntity$Outbound,
  AffiliateInviteEntity$outboundSchema,
} from "./affiliateinviteentity.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";

export type AffiliateInviteListEntity = {
  /**
   * List of affiliate invitation items
   */
  items: Array<AffiliateInviteEntity>;
  /**
   * Pagination details for the list
   */
  pagination: PaginationEntity;
};

/** @internal */
export const AffiliateInviteListEntity$inboundSchema: z.ZodType<
  AffiliateInviteListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(AffiliateInviteEntity$inboundSchema),
  pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export type AffiliateInviteListEntity$Outbound = {
  items: Array<AffiliateInviteEntity$Outbound>;
  pagination: PaginationEntity$Outbound;
};

/** @internal */
export const AffiliateInviteListEntity$outboundSchema: z.ZodType<
  AffiliateInviteListEntity$Outbound,
  z.ZodTypeDef,
  AffiliateInviteListEntity
> = z.object({
  items: z.array(AffiliateInviteEntity$outboundSchema),
  pagination: PaginationEntity$outboundSchema,
});

export function affiliateInviteListEntityToJSON(
  affiliateInviteListEntity: AffiliateInviteListEntity,
): string {
  return JSON.stringify(
    AffiliateInviteListEntity$outboundSchema.parse(affiliateInviteListEntity),
  );
}
export function affiliateInviteListEntityFromJSON(
  jsonString: string,
): SafeParseResult<AffiliateInviteListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AffiliateInviteListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AffiliateInviteListEntity' from JSON`,
  );
}
