/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The kind of recipient: `store` for an existing store (add it directly), or `email` to invite someone by email (the split stays disabled until they accept).
 */
export const RecipientType = {
  Store: "store",
  Email: "email",
} as const;
/**
 * The kind of recipient: `store` for an existing store (add it directly), or `email` to invite someone by email (the split stays disabled until they accept).
 */
export type RecipientType = ClosedEnum<typeof RecipientType>;

export type CreateSplitRecipientRequestEntity = {
  /**
   * The kind of recipient: `store` for an existing store (add it directly), or `email` to invite someone by email (the split stays disabled until they accept).
   */
  recipientType: RecipientType;
  /**
   * The recipient reference: a store id when `recipient_type` is `store`, or an email address when `recipient_type` is `email`.
   */
  recipientReference: string;
  /**
   * The recipient's share as a percentage of the split net, from 1 to 100. The sum of all recipient shares must not exceed 100.
   */
  amount: number;
};

/** @internal */
export const RecipientType$inboundSchema: z.ZodNativeEnum<
  typeof RecipientType
> = z.nativeEnum(RecipientType);
/** @internal */
export const RecipientType$outboundSchema: z.ZodNativeEnum<
  typeof RecipientType
> = RecipientType$inboundSchema;

/** @internal */
export const CreateSplitRecipientRequestEntity$inboundSchema: z.ZodType<
  CreateSplitRecipientRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  recipient_type: RecipientType$inboundSchema,
  recipient_reference: z.string(),
  amount: z.number(),
}).transform((v) => {
  return remap$(v, {
    "recipient_type": "recipientType",
    "recipient_reference": "recipientReference",
  });
});
/** @internal */
export type CreateSplitRecipientRequestEntity$Outbound = {
  recipient_type: string;
  recipient_reference: string;
  amount: number;
};

/** @internal */
export const CreateSplitRecipientRequestEntity$outboundSchema: z.ZodType<
  CreateSplitRecipientRequestEntity$Outbound,
  z.ZodTypeDef,
  CreateSplitRecipientRequestEntity
> = z.object({
  recipientType: RecipientType$outboundSchema,
  recipientReference: z.string(),
  amount: z.number(),
}).transform((v) => {
  return remap$(v, {
    recipientType: "recipient_type",
    recipientReference: "recipient_reference",
  });
});

export function createSplitRecipientRequestEntityToJSON(
  createSplitRecipientRequestEntity: CreateSplitRecipientRequestEntity,
): string {
  return JSON.stringify(
    CreateSplitRecipientRequestEntity$outboundSchema.parse(
      createSplitRecipientRequestEntity,
    ),
  );
}
export function createSplitRecipientRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<CreateSplitRecipientRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSplitRecipientRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSplitRecipientRequestEntity' from JSON`,
  );
}
