/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MeterFilterApiRequestDto,
  MeterFilterApiRequestDto$inboundSchema,
  MeterFilterApiRequestDto$Outbound,
  MeterFilterApiRequestDto$outboundSchema,
} from "./meterfilterapirequestdto.js";

/**
 * Aggregation applied to the matching events
 */
export const Aggregation = {
  Count: "count",
  Sum: "sum",
  Average: "average",
  Min: "min",
  Max: "max",
  Unique: "unique",
} as const;
/**
 * Aggregation applied to the matching events
 */
export type Aggregation = ClosedEnum<typeof Aggregation>;

export type CreateMeterApiRequestDto = {
  /**
   * Human-readable meter name, unique within your store
   */
  name: string;
  /**
   * The usage event name this meter consumes
   */
  eventName: string;
  /**
   * Aggregation applied to the matching events
   */
  aggregation: Aggregation;
  /**
   * Event property the aggregation reduces. Required for every aggregation except "count", which ignores it.
   */
  aggregationProperty?: string | undefined;
  /**
   * Optional filter narrowing which events the meter counts. Omitted means "count every event with this event name".
   */
  filter?: MeterFilterApiRequestDto | undefined;
  /**
   * Display unit for the metered quantity. Also names the customer-credits bucket the meter settles into.
   */
  unitLabel: string;
};

/** @internal */
export const Aggregation$inboundSchema: z.ZodNativeEnum<typeof Aggregation> = z
  .nativeEnum(Aggregation);
/** @internal */
export const Aggregation$outboundSchema: z.ZodNativeEnum<typeof Aggregation> =
  Aggregation$inboundSchema;

/** @internal */
export const CreateMeterApiRequestDto$inboundSchema: z.ZodType<
  CreateMeterApiRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  event_name: z.string(),
  aggregation: Aggregation$inboundSchema,
  aggregation_property: z.string().optional(),
  filter: MeterFilterApiRequestDto$inboundSchema.optional(),
  unit_label: z.string(),
}).transform((v) => {
  return remap$(v, {
    "event_name": "eventName",
    "aggregation_property": "aggregationProperty",
    "unit_label": "unitLabel",
  });
});
/** @internal */
export type CreateMeterApiRequestDto$Outbound = {
  name: string;
  event_name: string;
  aggregation: string;
  aggregation_property?: string | undefined;
  filter?: MeterFilterApiRequestDto$Outbound | undefined;
  unit_label: string;
};

/** @internal */
export const CreateMeterApiRequestDto$outboundSchema: z.ZodType<
  CreateMeterApiRequestDto$Outbound,
  z.ZodTypeDef,
  CreateMeterApiRequestDto
> = z.object({
  name: z.string(),
  eventName: z.string(),
  aggregation: Aggregation$outboundSchema,
  aggregationProperty: z.string().optional(),
  filter: MeterFilterApiRequestDto$outboundSchema.optional(),
  unitLabel: z.string(),
}).transform((v) => {
  return remap$(v, {
    eventName: "event_name",
    aggregationProperty: "aggregation_property",
    unitLabel: "unit_label",
  });
});

export function createMeterApiRequestDtoToJSON(
  createMeterApiRequestDto: CreateMeterApiRequestDto,
): string {
  return JSON.stringify(
    CreateMeterApiRequestDto$outboundSchema.parse(createMeterApiRequestDto),
  );
}
export function createMeterApiRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<CreateMeterApiRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMeterApiRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMeterApiRequestDto' from JSON`,
  );
}
