/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CreateSplitRecipientRequestEntity,
  CreateSplitRecipientRequestEntity$inboundSchema,
  CreateSplitRecipientRequestEntity$Outbound,
  CreateSplitRecipientRequestEntity$outboundSchema,
} from "./createsplitrecipientrequestentity.js";

/**
 * What the split applies to: `store` (every payment to your store) or `product` (payments for one product).
 */
export const CreateSplitRequestEntityType = {
  Store: "store",
  Product: "product",
} as const;
/**
 * What the split applies to: `store` (every payment to your store) or `product` (payments for one product).
 */
export type CreateSplitRequestEntityType = ClosedEnum<
  typeof CreateSplitRequestEntityType
>;

export type CreateSplitRequestEntity = {
  /**
   * An optional human-readable description of the split.
   */
  description?: string | null | undefined;
  /**
   * What the split applies to: `store` (every payment to your store) or `product` (payments for one product).
   */
  type: CreateSplitRequestEntityType;
  /**
   * The id of the entity the split applies to: your store id when `type` is `store`, or the product id when `type` is `product`.
   */
  typeReference: string;
  /**
   * The recipients of the split and their percentage shares. Between 1 and 10 recipients; shares must sum to at most 100.
   */
  recipients: Array<CreateSplitRecipientRequestEntity>;
};

/** @internal */
export const CreateSplitRequestEntityType$inboundSchema: z.ZodNativeEnum<
  typeof CreateSplitRequestEntityType
> = z.nativeEnum(CreateSplitRequestEntityType);
/** @internal */
export const CreateSplitRequestEntityType$outboundSchema: z.ZodNativeEnum<
  typeof CreateSplitRequestEntityType
> = CreateSplitRequestEntityType$inboundSchema;

/** @internal */
export const CreateSplitRequestEntity$inboundSchema: z.ZodType<
  CreateSplitRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.nullable(z.string()).optional(),
  type: CreateSplitRequestEntityType$inboundSchema,
  type_reference: z.string(),
  recipients: z.array(CreateSplitRecipientRequestEntity$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "type_reference": "typeReference",
  });
});
/** @internal */
export type CreateSplitRequestEntity$Outbound = {
  description?: string | null | undefined;
  type: string;
  type_reference: string;
  recipients: Array<CreateSplitRecipientRequestEntity$Outbound>;
};

/** @internal */
export const CreateSplitRequestEntity$outboundSchema: z.ZodType<
  CreateSplitRequestEntity$Outbound,
  z.ZodTypeDef,
  CreateSplitRequestEntity
> = z.object({
  description: z.nullable(z.string()).optional(),
  type: CreateSplitRequestEntityType$outboundSchema,
  typeReference: z.string(),
  recipients: z.array(CreateSplitRecipientRequestEntity$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    typeReference: "type_reference",
  });
});

export function createSplitRequestEntityToJSON(
  createSplitRequestEntity: CreateSplitRequestEntity,
): string {
  return JSON.stringify(
    CreateSplitRequestEntity$outboundSchema.parse(createSplitRequestEntity),
  );
}
export function createSplitRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<CreateSplitRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSplitRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSplitRequestEntity' from JSON`,
  );
}
