/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
  WebhookEventType$outboundSchema,
} from "./webhookeventtype.js";

export type CreateWebhookRequestEntity = {
  /**
   * The HTTPS URL Creem will deliver events to.
   */
  url: string;
  /**
   * A human-readable label for the endpoint.
   */
  name?: string | undefined;
  events?: Array<WebhookEventType> | undefined;
};

/** @internal */
export const CreateWebhookRequestEntity$inboundSchema: z.ZodType<
  CreateWebhookRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  name: z.string().optional(),
  events: z.array(WebhookEventType$inboundSchema).optional(),
});
/** @internal */
export type CreateWebhookRequestEntity$Outbound = {
  url: string;
  name?: string | undefined;
  events?: Array<string> | undefined;
};

/** @internal */
export const CreateWebhookRequestEntity$outboundSchema: z.ZodType<
  CreateWebhookRequestEntity$Outbound,
  z.ZodTypeDef,
  CreateWebhookRequestEntity
> = z.object({
  url: z.string(),
  name: z.string().optional(),
  events: z.array(WebhookEventType$outboundSchema).optional(),
});

export function createWebhookRequestEntityToJSON(
  createWebhookRequestEntity: CreateWebhookRequestEntity,
): string {
  return JSON.stringify(
    CreateWebhookRequestEntity$outboundSchema.parse(createWebhookRequestEntity),
  );
}
export function createWebhookRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookRequestEntity' from JSON`,
  );
}
