/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateAffiliateInviteRequestEntity = {
  /**
   * The email address to send the affiliate invitation to.
   */
  email: string;
  /**
   * The display name of the affiliate being invited.
   */
  name: string;
  /**
   * The ID of the affiliate program to invite into. Optional: when omitted, the invitation falls back to the store's affiliate program. Provide this only if your store runs more than one program.
   */
  programId?: string | null | undefined;
};

/** @internal */
export const CreateAffiliateInviteRequestEntity$inboundSchema: z.ZodType<
  CreateAffiliateInviteRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  name: z.string(),
  program_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "program_id": "programId",
  });
});
/** @internal */
export type CreateAffiliateInviteRequestEntity$Outbound = {
  email: string;
  name: string;
  program_id?: string | null | undefined;
};

/** @internal */
export const CreateAffiliateInviteRequestEntity$outboundSchema: z.ZodType<
  CreateAffiliateInviteRequestEntity$Outbound,
  z.ZodTypeDef,
  CreateAffiliateInviteRequestEntity
> = z.object({
  email: z.string(),
  name: z.string(),
  programId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    programId: "program_id",
  });
});

export function createAffiliateInviteRequestEntityToJSON(
  createAffiliateInviteRequestEntity: CreateAffiliateInviteRequestEntity,
): string {
  return JSON.stringify(
    CreateAffiliateInviteRequestEntity$outboundSchema.parse(
      createAffiliateInviteRequestEntity,
    ),
  );
}
export function createAffiliateInviteRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<CreateAffiliateInviteRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateAffiliateInviteRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAffiliateInviteRequestEntity' from JSON`,
  );
}
