/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookDeliveryMode,
  WebhookDeliveryMode$inboundSchema,
  WebhookDeliveryMode$outboundSchema,
} from "./webhookdeliverymode.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
  WebhookEventType$outboundSchema,
} from "./webhookeventtype.js";

export type CreateWebhookRequestEntity = {
  /**
   * The HTTPS URL Creem will deliver events to. Required unless `delivery_mode` is `cli`, in which case it is ignored.
   */
  url?: string | undefined;
  /**
   * How events reach this endpoint: `http` deliveries are POSTed to `url`; `cli` deliveries wait in the pending-events feed for a local `creem listen` session.
   */
  deliveryMode?: WebhookDeliveryMode | undefined;
  /**
   * A human-readable label for the endpoint.
   */
  name?: string | undefined;
  events?: Array<WebhookEventType> | undefined;
};

/** @internal */
export const CreateWebhookRequestEntity$inboundSchema: z.ZodType<
  CreateWebhookRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string().optional(),
  delivery_mode: WebhookDeliveryMode$inboundSchema.optional(),
  name: z.string().optional(),
  events: z.array(WebhookEventType$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "delivery_mode": "deliveryMode",
  });
});
/** @internal */
export type CreateWebhookRequestEntity$Outbound = {
  url?: string | undefined;
  delivery_mode?: string | undefined;
  name?: string | undefined;
  events?: Array<string> | undefined;
};

/** @internal */
export const CreateWebhookRequestEntity$outboundSchema: z.ZodType<
  CreateWebhookRequestEntity$Outbound,
  z.ZodTypeDef,
  CreateWebhookRequestEntity
> = z.object({
  url: z.string().optional(),
  deliveryMode: WebhookDeliveryMode$outboundSchema.optional(),
  name: z.string().optional(),
  events: z.array(WebhookEventType$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    deliveryMode: "delivery_mode",
  });
});

export function createWebhookRequestEntityToJSON(
  createWebhookRequestEntity: CreateWebhookRequestEntity,
): string {
  return JSON.stringify(
    CreateWebhookRequestEntity$outboundSchema.parse(createWebhookRequestEntity),
  );
}
export function createWebhookRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookRequestEntity' from JSON`,
  );
}
