/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EnvironmentMode,
  EnvironmentMode$inboundSchema,
  EnvironmentMode$outboundSchema,
} from "./environmentmode.js";

/**
 * Your own id for this customer, when you have set one — usage ingestion resolves `external_customer_id` against it.
 */
export type ExternalId = {};

export type CustomerEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: EnvironmentMode;
  /**
   * String representing the object’s type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * Customer email address.
   */
  email: string;
  /**
   * Customer name.
   */
  name?: string | null | undefined;
  /**
   * Additional metadata associated with the customer.
   */
  metadata?: { [k: string]: any } | null | undefined;
  /**
   * The ISO 3166-1 alpha-2 country code for the customer.
   */
  country: string | null;
  /**
   * Your own id for this customer, when you have set one — usage ingestion resolves `external_customer_id` against it.
   */
  externalId?: ExternalId | null | undefined;
  /**
   * Creation date of the customer
   */
  createdAt: Date;
  /**
   * Last updated date of the customer
   */
  updatedAt: Date;
};

/** @internal */
export const ExternalId$inboundSchema: z.ZodType<
  ExternalId,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type ExternalId$Outbound = {};

/** @internal */
export const ExternalId$outboundSchema: z.ZodType<
  ExternalId$Outbound,
  z.ZodTypeDef,
  ExternalId
> = z.object({});

export function externalIdToJSON(externalId: ExternalId): string {
  return JSON.stringify(ExternalId$outboundSchema.parse(externalId));
}
export function externalIdFromJSON(
  jsonString: string,
): SafeParseResult<ExternalId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExternalId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExternalId' from JSON`,
  );
}

/** @internal */
export const CustomerEntity$inboundSchema: z.ZodType<
  CustomerEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$inboundSchema,
  object: z.string(),
  email: z.string(),
  name: z.nullable(z.string()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  country: z.nullable(z.string()),
  external_id: z.nullable(z.lazy(() => ExternalId$inboundSchema)).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "external_id": "externalId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type CustomerEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  email: string;
  name?: string | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  country: string | null;
  external_id?: ExternalId$Outbound | null | undefined;
  created_at: string;
  updated_at: string;
};

/** @internal */
export const CustomerEntity$outboundSchema: z.ZodType<
  CustomerEntity$Outbound,
  z.ZodTypeDef,
  CustomerEntity
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$outboundSchema,
  object: z.string(),
  email: z.string(),
  name: z.nullable(z.string()).optional(),
  metadata: z.nullable(z.record(z.any())).optional(),
  country: z.nullable(z.string()),
  externalId: z.nullable(z.lazy(() => ExternalId$outboundSchema)).optional(),
  createdAt: z.date().transform(v => v.toISOString()),
  updatedAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    externalId: "external_id",
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

export function customerEntityToJSON(customerEntity: CustomerEntity): string {
  return JSON.stringify(CustomerEntity$outboundSchema.parse(customerEntity));
}
export function customerEntityFromJSON(
  jsonString: string,
): SafeParseResult<CustomerEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerEntity' from JSON`,
  );
}
