/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * String representing the object type.
 */
export const CustomerCreditsGrantEntityObject = {
  CustomerCreditsGrant: "customer_credits_grant",
} as const;
/**
 * String representing the object type.
 */
export type CustomerCreditsGrantEntityObject = ClosedEnum<
  typeof CustomerCreditsGrantEntityObject
>;

export type CustomerCreditsGrantEntity = {
  /**
   * Ledger transaction id (cct_...) the movement belongs to. One transaction may move several buckets; the pair (id, account_id) identifies this movement uniquely.
   */
  id: string;
  /**
   * Identifier of the customer whose bucket moved.
   */
  customerId: string;
  /**
   * Ledger account id (cca_...) of the credit bucket that moved.
   */
  accountId: string;
  /**
   * Name of the credit bucket. Buckets are per customer, and a store may run several (for example one per meter).
   */
  bucketName: string;
  /**
   * Display unit for the bucket (for example "images" or "tokens").
   */
  unitLabel: string;
  /**
   * Net amount moved for this bucket, in minor units, serialised as a string to preserve precision. Always positive; the event type carries the direction.
   */
  amountMinorUnits: string;
  /**
   * The bucket's balance immediately after this movement committed, in minor units, serialised as a string to preserve precision.
   */
  balanceAfterMinorUnits: string;
  /**
   * Reference the ledger transaction was posted under — cross-links the movement to what caused it (an order, a usage aggregation window, an auto-recharge grant).
   */
  reference: string;
  /**
   * ISO-8601 instant the ledger transaction was posted.
   */
  occurredAt: string;
  /**
   * String representing the object type.
   */
  object: CustomerCreditsGrantEntityObject;
};

/** @internal */
export const CustomerCreditsGrantEntityObject$inboundSchema: z.ZodNativeEnum<
  typeof CustomerCreditsGrantEntityObject
> = z.nativeEnum(CustomerCreditsGrantEntityObject);
/** @internal */
export const CustomerCreditsGrantEntityObject$outboundSchema: z.ZodNativeEnum<
  typeof CustomerCreditsGrantEntityObject
> = CustomerCreditsGrantEntityObject$inboundSchema;

/** @internal */
export const CustomerCreditsGrantEntity$inboundSchema: z.ZodType<
  CustomerCreditsGrantEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customer_id: z.string(),
  account_id: z.string(),
  bucket_name: z.string(),
  unit_label: z.string(),
  amount_minor_units: z.string(),
  balance_after_minor_units: z.string(),
  reference: z.string(),
  occurred_at: z.string(),
  object: CustomerCreditsGrantEntityObject$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "account_id": "accountId",
    "bucket_name": "bucketName",
    "unit_label": "unitLabel",
    "amount_minor_units": "amountMinorUnits",
    "balance_after_minor_units": "balanceAfterMinorUnits",
    "occurred_at": "occurredAt",
  });
});
/** @internal */
export type CustomerCreditsGrantEntity$Outbound = {
  id: string;
  customer_id: string;
  account_id: string;
  bucket_name: string;
  unit_label: string;
  amount_minor_units: string;
  balance_after_minor_units: string;
  reference: string;
  occurred_at: string;
  object: string;
};

/** @internal */
export const CustomerCreditsGrantEntity$outboundSchema: z.ZodType<
  CustomerCreditsGrantEntity$Outbound,
  z.ZodTypeDef,
  CustomerCreditsGrantEntity
> = z.object({
  id: z.string(),
  customerId: z.string(),
  accountId: z.string(),
  bucketName: z.string(),
  unitLabel: z.string(),
  amountMinorUnits: z.string(),
  balanceAfterMinorUnits: z.string(),
  reference: z.string(),
  occurredAt: z.string(),
  object: CustomerCreditsGrantEntityObject$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    accountId: "account_id",
    bucketName: "bucket_name",
    unitLabel: "unit_label",
    amountMinorUnits: "amount_minor_units",
    balanceAfterMinorUnits: "balance_after_minor_units",
    occurredAt: "occurred_at",
  });
});

export function customerCreditsGrantEntityToJSON(
  customerCreditsGrantEntity: CustomerCreditsGrantEntity,
): string {
  return JSON.stringify(
    CustomerCreditsGrantEntity$outboundSchema.parse(customerCreditsGrantEntity),
  );
}
export function customerCreditsGrantEntityFromJSON(
  jsonString: string,
): SafeParseResult<CustomerCreditsGrantEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerCreditsGrantEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerCreditsGrantEntity' from JSON`,
  );
}
