/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CustomerCreditsFeatureEntity = {
  /**
   * The number of credits to grant. String to preserve BigInt precision.
   */
  amount: string;
  /**
   * Optional label for the credit unit (e.g. "tokens", "credits").
   */
  unitLabel?: string | null | undefined;
  /**
   * The customer-credit bucket this grant funds — the `name` of the customer's credit account. Set it to a meter bucket (e.g. "images") so the credits fund a per-unit metered price; otherwise they land in `default` and metered usage cannot spend them. Distinct from `unit_label`, which is only a display label. On UPDATE the field is tri-state: OMIT it to leave the stored bucket unchanged, send `null` to clear it to the shared `default` wallet, or send a name to set it. On CREATE, omitted or null both mean `default`. A present-but-blank value is rejected.
   */
  bucketName?: string | null | undefined;
};

/** @internal */
export const CustomerCreditsFeatureEntity$inboundSchema: z.ZodType<
  CustomerCreditsFeatureEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.string(),
  unit_label: z.nullable(z.string()).optional(),
  bucket_name: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "unit_label": "unitLabel",
    "bucket_name": "bucketName",
  });
});
/** @internal */
export type CustomerCreditsFeatureEntity$Outbound = {
  amount: string;
  unit_label?: string | null | undefined;
  bucket_name?: string | null | undefined;
};

/** @internal */
export const CustomerCreditsFeatureEntity$outboundSchema: z.ZodType<
  CustomerCreditsFeatureEntity$Outbound,
  z.ZodTypeDef,
  CustomerCreditsFeatureEntity
> = z.object({
  amount: z.string(),
  unitLabel: z.nullable(z.string()).optional(),
  bucketName: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    unitLabel: "unit_label",
    bucketName: "bucket_name",
  });
});

export function customerCreditsFeatureEntityToJSON(
  customerCreditsFeatureEntity: CustomerCreditsFeatureEntity,
): string {
  return JSON.stringify(
    CustomerCreditsFeatureEntity$outboundSchema.parse(
      customerCreditsFeatureEntity,
    ),
  );
}
export function customerCreditsFeatureEntityFromJSON(
  jsonString: string,
): SafeParseResult<CustomerCreditsFeatureEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerCreditsFeatureEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerCreditsFeatureEntity' from JSON`,
  );
}
