/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * String representing the object type.
 */
export const ObjectT = {
  CustomerCreditsExhaustion: "customer_credits_exhaustion",
} as const;
/**
 * String representing the object type.
 */
export type ObjectT = ClosedEnum<typeof ObjectT>;

export type CustomerCreditsExhaustionEntity = {
  /**
   * Stable identity of this exhaustion episode. One episode spans from the first refused charge until credits are next added, so this value is the same across every signal about the same exhaustion.
   */
  id: string;
  /**
   * String representing the object type.
   */
  object: ObjectT;
  /**
   * Identifier of the customer whose credits ran out.
   */
  customerId: string;
  /**
   * Name of the credit bucket that ran dry. Buckets are per customer, and a store may run several (for example one per meter).
   */
  bucketName: string;
  /**
   * Display unit for the bucket, as configured on the meter (for example "images" or "tokens").
   */
  unitLabel: string;
  /**
   * The charge that could not be covered, in minor units, serialised as a string to preserve precision.
   */
  shortfallMinorUnits: string;
  /**
   * ISO-8601 instant at which the usage charge was refused for lack of credit.
   */
  occurredAt: string;
};

/** @internal */
export const ObjectT$inboundSchema: z.ZodNativeEnum<typeof ObjectT> = z
  .nativeEnum(ObjectT);
/** @internal */
export const ObjectT$outboundSchema: z.ZodNativeEnum<typeof ObjectT> =
  ObjectT$inboundSchema;

/** @internal */
export const CustomerCreditsExhaustionEntity$inboundSchema: z.ZodType<
  CustomerCreditsExhaustionEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: ObjectT$inboundSchema,
  customer_id: z.string(),
  bucket_name: z.string(),
  unit_label: z.string(),
  shortfall_minor_units: z.string(),
  occurred_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "bucket_name": "bucketName",
    "unit_label": "unitLabel",
    "shortfall_minor_units": "shortfallMinorUnits",
    "occurred_at": "occurredAt",
  });
});
/** @internal */
export type CustomerCreditsExhaustionEntity$Outbound = {
  id: string;
  object: string;
  customer_id: string;
  bucket_name: string;
  unit_label: string;
  shortfall_minor_units: string;
  occurred_at: string;
};

/** @internal */
export const CustomerCreditsExhaustionEntity$outboundSchema: z.ZodType<
  CustomerCreditsExhaustionEntity$Outbound,
  z.ZodTypeDef,
  CustomerCreditsExhaustionEntity
> = z.object({
  id: z.string(),
  object: ObjectT$outboundSchema,
  customerId: z.string(),
  bucketName: z.string(),
  unitLabel: z.string(),
  shortfallMinorUnits: z.string(),
  occurredAt: z.string(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    bucketName: "bucket_name",
    unitLabel: "unit_label",
    shortfallMinorUnits: "shortfall_minor_units",
    occurredAt: "occurred_at",
  });
});

export function customerCreditsExhaustionEntityToJSON(
  customerCreditsExhaustionEntity: CustomerCreditsExhaustionEntity,
): string {
  return JSON.stringify(
    CustomerCreditsExhaustionEntity$outboundSchema.parse(
      customerCreditsExhaustionEntity,
    ),
  );
}
export function customerCreditsExhaustionEntityFromJSON(
  jsonString: string,
): SafeParseResult<CustomerCreditsExhaustionEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerCreditsExhaustionEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerCreditsExhaustionEntity' from JSON`,
  );
}
