/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * String representing the object type.
 */
export const CustomerCreditsAutoRechargeEntityObject = {
  CustomerCreditsAutoRecharge: "customer_credits_auto_recharge",
} as const;
/**
 * String representing the object type.
 */
export type CustomerCreditsAutoRechargeEntityObject = ClosedEnum<
  typeof CustomerCreditsAutoRechargeEntityObject
>;

export type CustomerCreditsAutoRechargeEntity = {
  /**
   * Ledger transaction id (cct_...) of the credit grant the recharge posted — the same id the accompanying credits.granted event carries.
   */
  id: string;
  /**
   * String representing the object type.
   */
  object: CustomerCreditsAutoRechargeEntityObject;
  /**
   * Identifier of the customer whose bucket was topped up.
   */
  customerId: string;
  /**
   * Name of the credit bucket that was topped up.
   */
  bucketName: string;
  /**
   * Display unit for the bucket (for example "images" or "tokens").
   */
  unitLabel: string;
  /**
   * Amount granted into the bucket, in minor units, serialised as a string to preserve precision.
   */
  amountMinorUnits: string;
  /**
   * ISO-4217 currency the off-session recharge was charged in.
   */
  currency: string;
  /**
   * Provider-side charge reference for the off-session top-up.
   */
  chargeReference: string;
  /**
   * Usage aggregation-window reference the recharge reconciles against.
   */
  reference: string;
};

/** @internal */
export const CustomerCreditsAutoRechargeEntityObject$inboundSchema:
  z.ZodNativeEnum<typeof CustomerCreditsAutoRechargeEntityObject> = z
    .nativeEnum(CustomerCreditsAutoRechargeEntityObject);
/** @internal */
export const CustomerCreditsAutoRechargeEntityObject$outboundSchema:
  z.ZodNativeEnum<typeof CustomerCreditsAutoRechargeEntityObject> =
    CustomerCreditsAutoRechargeEntityObject$inboundSchema;

/** @internal */
export const CustomerCreditsAutoRechargeEntity$inboundSchema: z.ZodType<
  CustomerCreditsAutoRechargeEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: CustomerCreditsAutoRechargeEntityObject$inboundSchema,
  customer_id: z.string(),
  bucket_name: z.string(),
  unit_label: z.string(),
  amount_minor_units: z.string(),
  currency: z.string(),
  charge_reference: z.string(),
  reference: z.string(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "bucket_name": "bucketName",
    "unit_label": "unitLabel",
    "amount_minor_units": "amountMinorUnits",
    "charge_reference": "chargeReference",
  });
});
/** @internal */
export type CustomerCreditsAutoRechargeEntity$Outbound = {
  id: string;
  object: string;
  customer_id: string;
  bucket_name: string;
  unit_label: string;
  amount_minor_units: string;
  currency: string;
  charge_reference: string;
  reference: string;
};

/** @internal */
export const CustomerCreditsAutoRechargeEntity$outboundSchema: z.ZodType<
  CustomerCreditsAutoRechargeEntity$Outbound,
  z.ZodTypeDef,
  CustomerCreditsAutoRechargeEntity
> = z.object({
  id: z.string(),
  object: CustomerCreditsAutoRechargeEntityObject$outboundSchema,
  customerId: z.string(),
  bucketName: z.string(),
  unitLabel: z.string(),
  amountMinorUnits: z.string(),
  currency: z.string(),
  chargeReference: z.string(),
  reference: z.string(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    bucketName: "bucket_name",
    unitLabel: "unit_label",
    amountMinorUnits: "amount_minor_units",
    chargeReference: "charge_reference",
  });
});

export function customerCreditsAutoRechargeEntityToJSON(
  customerCreditsAutoRechargeEntity: CustomerCreditsAutoRechargeEntity,
): string {
  return JSON.stringify(
    CustomerCreditsAutoRechargeEntity$outboundSchema.parse(
      customerCreditsAutoRechargeEntity,
    ),
  );
}
export function customerCreditsAutoRechargeEntityFromJSON(
  jsonString: string,
): SafeParseResult<CustomerCreditsAutoRechargeEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomerCreditsAutoRechargeEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomerCreditsAutoRechargeEntity' from JSON`,
  );
}
