/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Value compared against, as stored after parsing
 */
export type FilterClauseApiResponseDtoValue = string | number | boolean;

export type FilterClauseApiResponseDto = {
  /**
   * Event property tested
   */
  property: string;
  /**
   * Comparison operator
   */
  operator: string;
  /**
   * Value compared against, as stored after parsing
   */
  value: string | number | boolean;
};

/** @internal */
export const FilterClauseApiResponseDtoValue$inboundSchema: z.ZodType<
  FilterClauseApiResponseDtoValue,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.number(), z.boolean()]);
/** @internal */
export type FilterClauseApiResponseDtoValue$Outbound =
  | string
  | number
  | boolean;

/** @internal */
export const FilterClauseApiResponseDtoValue$outboundSchema: z.ZodType<
  FilterClauseApiResponseDtoValue$Outbound,
  z.ZodTypeDef,
  FilterClauseApiResponseDtoValue
> = z.union([z.string(), z.number(), z.boolean()]);

export function filterClauseApiResponseDtoValueToJSON(
  filterClauseApiResponseDtoValue: FilterClauseApiResponseDtoValue,
): string {
  return JSON.stringify(
    FilterClauseApiResponseDtoValue$outboundSchema.parse(
      filterClauseApiResponseDtoValue,
    ),
  );
}
export function filterClauseApiResponseDtoValueFromJSON(
  jsonString: string,
): SafeParseResult<FilterClauseApiResponseDtoValue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FilterClauseApiResponseDtoValue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FilterClauseApiResponseDtoValue' from JSON`,
  );
}

/** @internal */
export const FilterClauseApiResponseDto$inboundSchema: z.ZodType<
  FilterClauseApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  property: z.string(),
  operator: z.string(),
  value: z.union([z.string(), z.number(), z.boolean()]),
});
/** @internal */
export type FilterClauseApiResponseDto$Outbound = {
  property: string;
  operator: string;
  value: string | number | boolean;
};

/** @internal */
export const FilterClauseApiResponseDto$outboundSchema: z.ZodType<
  FilterClauseApiResponseDto$Outbound,
  z.ZodTypeDef,
  FilterClauseApiResponseDto
> = z.object({
  property: z.string(),
  operator: z.string(),
  value: z.union([z.string(), z.number(), z.boolean()]),
});

export function filterClauseApiResponseDtoToJSON(
  filterClauseApiResponseDto: FilterClauseApiResponseDto,
): string {
  return JSON.stringify(
    FilterClauseApiResponseDto$outboundSchema.parse(filterClauseApiResponseDto),
  );
}
export function filterClauseApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<FilterClauseApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FilterClauseApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FilterClauseApiResponseDto' from JSON`,
  );
}
