/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Comparison operator
 */
export const Operator = {
  Equals: "equals",
  NotEquals: "not_equals",
  Gt: "gt",
  Gte: "gte",
  Lt: "lt",
  Lte: "lte",
  Contains: "contains",
  NotContains: "not_contains",
} as const;
/**
 * Comparison operator
 */
export type Operator = ClosedEnum<typeof Operator>;

/**
 * Value to compare against. Auto-parsed (number → boolean → string) on both sides before comparison, so "10" and 10 behave the same — which is why a raw number or boolean is accepted here as well as a string.
 */
export type Value = string | number | boolean;

export type FilterClauseApiRequestDto = {
  /**
   * Event property to test. Resolved as a top-level property first, then as a metadata key — never prefixed with "metadata.".
   */
  property: string;
  /**
   * Comparison operator
   */
  operator: Operator;
  /**
   * Value to compare against. Auto-parsed (number → boolean → string) on both sides before comparison, so "10" and 10 behave the same — which is why a raw number or boolean is accepted here as well as a string.
   */
  value: string | number | boolean;
};

/** @internal */
export const Operator$inboundSchema: z.ZodNativeEnum<typeof Operator> = z
  .nativeEnum(Operator);
/** @internal */
export const Operator$outboundSchema: z.ZodNativeEnum<typeof Operator> =
  Operator$inboundSchema;

/** @internal */
export const Value$inboundSchema: z.ZodType<Value, z.ZodTypeDef, unknown> = z
  .union([z.string(), z.number(), z.boolean()]);
/** @internal */
export type Value$Outbound = string | number | boolean;

/** @internal */
export const Value$outboundSchema: z.ZodType<
  Value$Outbound,
  z.ZodTypeDef,
  Value
> = z.union([z.string(), z.number(), z.boolean()]);

export function valueToJSON(value: Value): string {
  return JSON.stringify(Value$outboundSchema.parse(value));
}
export function valueFromJSON(
  jsonString: string,
): SafeParseResult<Value, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Value$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Value' from JSON`,
  );
}

/** @internal */
export const FilterClauseApiRequestDto$inboundSchema: z.ZodType<
  FilterClauseApiRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  property: z.string(),
  operator: Operator$inboundSchema,
  value: z.union([z.string(), z.number(), z.boolean()]),
});
/** @internal */
export type FilterClauseApiRequestDto$Outbound = {
  property: string;
  operator: string;
  value: string | number | boolean;
};

/** @internal */
export const FilterClauseApiRequestDto$outboundSchema: z.ZodType<
  FilterClauseApiRequestDto$Outbound,
  z.ZodTypeDef,
  FilterClauseApiRequestDto
> = z.object({
  property: z.string(),
  operator: Operator$outboundSchema,
  value: z.union([z.string(), z.number(), z.boolean()]),
});

export function filterClauseApiRequestDtoToJSON(
  filterClauseApiRequestDto: FilterClauseApiRequestDto,
): string {
  return JSON.stringify(
    FilterClauseApiRequestDto$outboundSchema.parse(filterClauseApiRequestDto),
  );
}
export function filterClauseApiRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<FilterClauseApiRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FilterClauseApiRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FilterClauseApiRequestDto' from JSON`,
  );
}
