/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Top-level structured fields carried by the event — this is where the value an aggregation reduces (e.g. "tokens") lives. At most 50 keys, keys at most 40 characters, string values at most 500 characters.
 */
export type Properties = {};

/**
 * Free-form metadata. Addressable by meter filter clauses without a prefix. Same limits as `properties`.
 */
export type Metadata = {};

export type IngestUsageEventApiRequestDto = {
  /**
   * The usage event name; must match a meter to be aggregated
   */
  name: string;
  /**
   * The customer this usage is attributed to
   */
  customerId: string;
  /**
   * Your idempotency key for this event, unique within your store. Re-sending the same event_id is a no-op. Generated for you when omitted — supply your own if you want retries to be safe.
   */
  eventId?: string | undefined;
  /**
   * When the usage occurred (ISO 8601), on your clock. Defaults to the time of ingestion.
   */
  timestamp?: string | undefined;
  /**
   * Top-level structured fields carried by the event — this is where the value an aggregation reduces (e.g. "tokens") lives. At most 50 keys, keys at most 40 characters, string values at most 500 characters.
   */
  properties?: Properties | undefined;
  /**
   * Free-form metadata. Addressable by meter filter clauses without a prefix. Same limits as `properties`.
   */
  metadata?: Metadata | undefined;
};

/** @internal */
export const Properties$inboundSchema: z.ZodType<
  Properties,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type Properties$Outbound = {};

/** @internal */
export const Properties$outboundSchema: z.ZodType<
  Properties$Outbound,
  z.ZodTypeDef,
  Properties
> = z.object({});

export function propertiesToJSON(properties: Properties): string {
  return JSON.stringify(Properties$outboundSchema.parse(properties));
}
export function propertiesFromJSON(
  jsonString: string,
): SafeParseResult<Properties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Properties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Properties' from JSON`,
  );
}

/** @internal */
export const Metadata$inboundSchema: z.ZodType<
  Metadata,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type Metadata$Outbound = {};

/** @internal */
export const Metadata$outboundSchema: z.ZodType<
  Metadata$Outbound,
  z.ZodTypeDef,
  Metadata
> = z.object({});

export function metadataToJSON(metadata: Metadata): string {
  return JSON.stringify(Metadata$outboundSchema.parse(metadata));
}
export function metadataFromJSON(
  jsonString: string,
): SafeParseResult<Metadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metadata' from JSON`,
  );
}

/** @internal */
export const IngestUsageEventApiRequestDto$inboundSchema: z.ZodType<
  IngestUsageEventApiRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  customer_id: z.string(),
  event_id: z.string().optional(),
  timestamp: z.string().optional(),
  properties: z.lazy(() => Properties$inboundSchema).optional(),
  metadata: z.lazy(() => Metadata$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "event_id": "eventId",
  });
});
/** @internal */
export type IngestUsageEventApiRequestDto$Outbound = {
  name: string;
  customer_id: string;
  event_id?: string | undefined;
  timestamp?: string | undefined;
  properties?: Properties$Outbound | undefined;
  metadata?: Metadata$Outbound | undefined;
};

/** @internal */
export const IngestUsageEventApiRequestDto$outboundSchema: z.ZodType<
  IngestUsageEventApiRequestDto$Outbound,
  z.ZodTypeDef,
  IngestUsageEventApiRequestDto
> = z.object({
  name: z.string(),
  customerId: z.string(),
  eventId: z.string().optional(),
  timestamp: z.string().optional(),
  properties: z.lazy(() => Properties$outboundSchema).optional(),
  metadata: z.lazy(() => Metadata$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    eventId: "event_id",
  });
});

export function ingestUsageEventApiRequestDtoToJSON(
  ingestUsageEventApiRequestDto: IngestUsageEventApiRequestDto,
): string {
  return JSON.stringify(
    IngestUsageEventApiRequestDto$outboundSchema.parse(
      ingestUsageEventApiRequestDto,
    ),
  );
}
export function ingestUsageEventApiRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<IngestUsageEventApiRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestUsageEventApiRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestUsageEventApiRequestDto' from JSON`,
  );
}
