/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  IngestUsageEventApiRequestDto,
  IngestUsageEventApiRequestDto$inboundSchema,
  IngestUsageEventApiRequestDto$Outbound,
  IngestUsageEventApiRequestDto$outboundSchema,
} from "./ingestusageeventapirequestdto.js";

export type IngestUsageEventsApiRequestDto = {
  /**
   * The batch of usage events to ingest (1–100). The whole batch is validated before anything is written.
   */
  events: Array<IngestUsageEventApiRequestDto>;
};

/** @internal */
export const IngestUsageEventsApiRequestDto$inboundSchema: z.ZodType<
  IngestUsageEventsApiRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  events: z.array(IngestUsageEventApiRequestDto$inboundSchema),
});
/** @internal */
export type IngestUsageEventsApiRequestDto$Outbound = {
  events: Array<IngestUsageEventApiRequestDto$Outbound>;
};

/** @internal */
export const IngestUsageEventsApiRequestDto$outboundSchema: z.ZodType<
  IngestUsageEventsApiRequestDto$Outbound,
  z.ZodTypeDef,
  IngestUsageEventsApiRequestDto
> = z.object({
  events: z.array(IngestUsageEventApiRequestDto$outboundSchema),
});

export function ingestUsageEventsApiRequestDtoToJSON(
  ingestUsageEventsApiRequestDto: IngestUsageEventsApiRequestDto,
): string {
  return JSON.stringify(
    IngestUsageEventsApiRequestDto$outboundSchema.parse(
      ingestUsageEventsApiRequestDto,
    ),
  );
}
export function ingestUsageEventsApiRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<IngestUsageEventsApiRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestUsageEventsApiRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestUsageEventsApiRequestDto' from JSON`,
  );
}
