/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type IngestUsageEventApiRequestDto = {
  /**
   * The usage event name; must match a meter to be aggregated
   */
  name: string;
  /**
   * The Creem customer this usage is attributed to. Exactly one of `customer_id` / `external_customer_id` is required per event; the id must belong to an existing customer of your store or the whole batch is rejected. Trimmed; letters, digits, `_` and `-` only; at most 255 characters.
   */
  customerId?: string | undefined;
  /**
   * Your own id for this customer, resolved to the Creem customer it was registered for via the customers API. Exactly one of `customer_id` / `external_customer_id` is required per event; an id no customer carries rejects the whole batch. Trimmed; letters, digits, `_` and `-` only; at most 255 characters.
   */
  externalCustomerId?: string | undefined;
  /**
   * Your idempotency key for this event, unique within your store. Re-sending the same event_id is a no-op. Generated for you when omitted — supply your own if you want retries to be safe.
   */
  eventId?: string | undefined;
  /**
   * When the usage occurred (ISO 8601), on your clock. Defaults to the time of ingestion.
   */
  timestamp?: string | undefined;
  /**
   * The event's attributes — the ONE bag. Meter filter clauses and aggregation properties (e.g. "tokens") resolve their keys here, unprefixed. At most 50 keys, keys at most 40 characters, string and serialized-object values at most 500 characters.
   */
  properties?: { [k: string]: any } | undefined;
};

/** @internal */
export const IngestUsageEventApiRequestDto$inboundSchema: z.ZodType<
  IngestUsageEventApiRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  customer_id: z.string().optional(),
  external_customer_id: z.string().optional(),
  event_id: z.string().optional(),
  timestamp: z.string().optional(),
  properties: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "external_customer_id": "externalCustomerId",
    "event_id": "eventId",
  });
});
/** @internal */
export type IngestUsageEventApiRequestDto$Outbound = {
  name: string;
  customer_id?: string | undefined;
  external_customer_id?: string | undefined;
  event_id?: string | undefined;
  timestamp?: string | undefined;
  properties?: { [k: string]: any } | undefined;
};

/** @internal */
export const IngestUsageEventApiRequestDto$outboundSchema: z.ZodType<
  IngestUsageEventApiRequestDto$Outbound,
  z.ZodTypeDef,
  IngestUsageEventApiRequestDto
> = z.object({
  name: z.string(),
  customerId: z.string().optional(),
  externalCustomerId: z.string().optional(),
  eventId: z.string().optional(),
  timestamp: z.string().optional(),
  properties: z.record(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    externalCustomerId: "external_customer_id",
    eventId: "event_id",
  });
});

export function ingestUsageEventApiRequestDtoToJSON(
  ingestUsageEventApiRequestDto: IngestUsageEventApiRequestDto,
): string {
  return JSON.stringify(
    IngestUsageEventApiRequestDto$outboundSchema.parse(
      ingestUsageEventApiRequestDto,
    ),
  );
}
export function ingestUsageEventApiRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<IngestUsageEventApiRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestUsageEventApiRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestUsageEventApiRequestDto' from JSON`,
  );
}
