/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Warning code. `no_matching_meter`: no meter consumes this event name. `meter_archived`: only archived meters match — unarchive one to resume aggregation. `timestamp_outside_late_window`: the billing period the timestamp falls in is finalized, so the event will never change its totals.
 */
export const Code = {
  NoMatchingMeter: "no_matching_meter",
  MeterArchived: "meter_archived",
  TimestampOutsideLateWindow: "timestamp_outside_late_window",
} as const;
/**
 * Warning code. `no_matching_meter`: no meter consumes this event name. `meter_archived`: only archived meters match — unarchive one to resume aggregation. `timestamp_outside_late_window`: the billing period the timestamp falls in is finalized, so the event will never change its totals.
 */
export type Code = ClosedEnum<typeof Code>;

export type IngestUsageEventWarningApiDto = {
  /**
   * Zero-based index of the event in the submitted batch
   */
  index: number;
  /**
   * Warning code. `no_matching_meter`: no meter consumes this event name. `meter_archived`: only archived meters match — unarchive one to resume aggregation. `timestamp_outside_late_window`: the billing period the timestamp falls in is finalized, so the event will never change its totals.
   */
  code: Code;
  /**
   * Human-readable explanation
   */
  message: string;
};

/** @internal */
export const Code$inboundSchema: z.ZodNativeEnum<typeof Code> = z.nativeEnum(
  Code,
);
/** @internal */
export const Code$outboundSchema: z.ZodNativeEnum<typeof Code> =
  Code$inboundSchema;

/** @internal */
export const IngestUsageEventWarningApiDto$inboundSchema: z.ZodType<
  IngestUsageEventWarningApiDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  index: z.number(),
  code: Code$inboundSchema,
  message: z.string(),
});
/** @internal */
export type IngestUsageEventWarningApiDto$Outbound = {
  index: number;
  code: string;
  message: string;
};

/** @internal */
export const IngestUsageEventWarningApiDto$outboundSchema: z.ZodType<
  IngestUsageEventWarningApiDto$Outbound,
  z.ZodTypeDef,
  IngestUsageEventWarningApiDto
> = z.object({
  index: z.number(),
  code: Code$outboundSchema,
  message: z.string(),
});

export function ingestUsageEventWarningApiDtoToJSON(
  ingestUsageEventWarningApiDto: IngestUsageEventWarningApiDto,
): string {
  return JSON.stringify(
    IngestUsageEventWarningApiDto$outboundSchema.parse(
      ingestUsageEventWarningApiDto,
    ),
  );
}
export function ingestUsageEventWarningApiDtoFromJSON(
  jsonString: string,
): SafeParseResult<IngestUsageEventWarningApiDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => IngestUsageEventWarningApiDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'IngestUsageEventWarningApiDto' from JSON`,
  );
}
