/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MeterPreviewDailyApiResponseDto,
  MeterPreviewDailyApiResponseDto$inboundSchema,
  MeterPreviewDailyApiResponseDto$Outbound,
  MeterPreviewDailyApiResponseDto$outboundSchema,
} from "./meterpreviewdailyapiresponsedto.js";

export type MeterPreviewApiResponseDto = {
  /**
   * Events the meter would count over the preview window
   */
  matchedEvents: number;
  /**
   * Aggregated units over the whole window, as a string for BigInt safety
   */
  units: string;
  /**
   * Distinct customers among the matching events
   */
  distinctCustomers: number;
  /**
   * The last 7 UTC days (today included), oldest first and zero-filled
   */
  daily: Array<MeterPreviewDailyApiResponseDto>;
};

/** @internal */
export const MeterPreviewApiResponseDto$inboundSchema: z.ZodType<
  MeterPreviewApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  matched_events: z.number(),
  units: z.string(),
  distinct_customers: z.number(),
  daily: z.array(MeterPreviewDailyApiResponseDto$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "matched_events": "matchedEvents",
    "distinct_customers": "distinctCustomers",
  });
});
/** @internal */
export type MeterPreviewApiResponseDto$Outbound = {
  matched_events: number;
  units: string;
  distinct_customers: number;
  daily: Array<MeterPreviewDailyApiResponseDto$Outbound>;
};

/** @internal */
export const MeterPreviewApiResponseDto$outboundSchema: z.ZodType<
  MeterPreviewApiResponseDto$Outbound,
  z.ZodTypeDef,
  MeterPreviewApiResponseDto
> = z.object({
  matchedEvents: z.number(),
  units: z.string(),
  distinctCustomers: z.number(),
  daily: z.array(MeterPreviewDailyApiResponseDto$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    matchedEvents: "matched_events",
    distinctCustomers: "distinct_customers",
  });
});

export function meterPreviewApiResponseDtoToJSON(
  meterPreviewApiResponseDto: MeterPreviewApiResponseDto,
): string {
  return JSON.stringify(
    MeterPreviewApiResponseDto$outboundSchema.parse(meterPreviewApiResponseDto),
  );
}
export function meterPreviewApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MeterPreviewApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterPreviewApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterPreviewApiResponseDto' from JSON`,
  );
}
