/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MeterConsumedUnitsApiResponseDto = {
  /**
   * Meter ID
   */
  meterId: string;
  /**
   * Customer ID
   */
  customerId: string;
  /**
   * Consumed units for the period, as a string for BigInt safety
   */
  units: string;
  /**
   * Start of the billing period (inclusive, ISO 8601)
   */
  periodStart: string;
  /**
   * End of the billing period (exclusive, ISO 8601)
   */
  periodEnd: string;
  /**
   * When the projection was last advanced. Null when no usage has been folded into this period yet, and always null for an `at=` reply (which is replayed from raw events rather than read from the projection).
   */
  updatedAt: string | null;
  /**
   * The point in time the units were replayed as of. Present only when `at=` was supplied.
   */
  asOf?: string | undefined;
};

/** @internal */
export const MeterConsumedUnitsApiResponseDto$inboundSchema: z.ZodType<
  MeterConsumedUnitsApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  meter_id: z.string(),
  customer_id: z.string(),
  units: z.string(),
  period_start: z.string(),
  period_end: z.string(),
  updated_at: z.nullable(z.string()),
  as_of: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "meter_id": "meterId",
    "customer_id": "customerId",
    "period_start": "periodStart",
    "period_end": "periodEnd",
    "updated_at": "updatedAt",
    "as_of": "asOf",
  });
});
/** @internal */
export type MeterConsumedUnitsApiResponseDto$Outbound = {
  meter_id: string;
  customer_id: string;
  units: string;
  period_start: string;
  period_end: string;
  updated_at: string | null;
  as_of?: string | undefined;
};

/** @internal */
export const MeterConsumedUnitsApiResponseDto$outboundSchema: z.ZodType<
  MeterConsumedUnitsApiResponseDto$Outbound,
  z.ZodTypeDef,
  MeterConsumedUnitsApiResponseDto
> = z.object({
  meterId: z.string(),
  customerId: z.string(),
  units: z.string(),
  periodStart: z.string(),
  periodEnd: z.string(),
  updatedAt: z.nullable(z.string()),
  asOf: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    meterId: "meter_id",
    customerId: "customer_id",
    periodStart: "period_start",
    periodEnd: "period_end",
    updatedAt: "updated_at",
    asOf: "as_of",
  });
});

export function meterConsumedUnitsApiResponseDtoToJSON(
  meterConsumedUnitsApiResponseDto: MeterConsumedUnitsApiResponseDto,
): string {
  return JSON.stringify(
    MeterConsumedUnitsApiResponseDto$outboundSchema.parse(
      meterConsumedUnitsApiResponseDto,
    ),
  );
}
export function meterConsumedUnitsApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MeterConsumedUnitsApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterConsumedUnitsApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterConsumedUnitsApiResponseDto' from JSON`,
  );
}
