/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FilterClauseApiResponseDto,
  FilterClauseApiResponseDto$inboundSchema,
  FilterClauseApiResponseDto$Outbound,
  FilterClauseApiResponseDto$outboundSchema,
} from "./filterclauseapiresponsedto.js";

/**
 * How the clauses combine
 */
export const MeterFilterApiResponseDtoConjunction = {
  And: "and",
  Or: "or",
} as const;
/**
 * How the clauses combine
 */
export type MeterFilterApiResponseDtoConjunction = ClosedEnum<
  typeof MeterFilterApiResponseDtoConjunction
>;

export type MeterFilterApiResponseDto = {
  /**
   * How the clauses combine
   */
  conjunction: MeterFilterApiResponseDtoConjunction;
  /**
   * Filter clauses; empty means the meter counts every event
   */
  clauses: Array<FilterClauseApiResponseDto>;
};

/** @internal */
export const MeterFilterApiResponseDtoConjunction$inboundSchema:
  z.ZodNativeEnum<typeof MeterFilterApiResponseDtoConjunction> = z.nativeEnum(
    MeterFilterApiResponseDtoConjunction,
  );
/** @internal */
export const MeterFilterApiResponseDtoConjunction$outboundSchema:
  z.ZodNativeEnum<typeof MeterFilterApiResponseDtoConjunction> =
    MeterFilterApiResponseDtoConjunction$inboundSchema;

/** @internal */
export const MeterFilterApiResponseDto$inboundSchema: z.ZodType<
  MeterFilterApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  conjunction: MeterFilterApiResponseDtoConjunction$inboundSchema,
  clauses: z.array(FilterClauseApiResponseDto$inboundSchema),
});
/** @internal */
export type MeterFilterApiResponseDto$Outbound = {
  conjunction: string;
  clauses: Array<FilterClauseApiResponseDto$Outbound>;
};

/** @internal */
export const MeterFilterApiResponseDto$outboundSchema: z.ZodType<
  MeterFilterApiResponseDto$Outbound,
  z.ZodTypeDef,
  MeterFilterApiResponseDto
> = z.object({
  conjunction: MeterFilterApiResponseDtoConjunction$outboundSchema,
  clauses: z.array(FilterClauseApiResponseDto$outboundSchema),
});

export function meterFilterApiResponseDtoToJSON(
  meterFilterApiResponseDto: MeterFilterApiResponseDto,
): string {
  return JSON.stringify(
    MeterFilterApiResponseDto$outboundSchema.parse(meterFilterApiResponseDto),
  );
}
export function meterFilterApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MeterFilterApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterFilterApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterFilterApiResponseDto' from JSON`,
  );
}
