/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MeterFilterApiResponseDto,
  MeterFilterApiResponseDto$inboundSchema,
  MeterFilterApiResponseDto$Outbound,
  MeterFilterApiResponseDto$outboundSchema,
} from "./meterfilterapiresponsedto.js";

/**
 * Aggregation applied to matching events
 */
export const MeterApiResponseDtoAggregation = {
  Count: "count",
  Sum: "sum",
  Average: "average",
  Min: "min",
  Max: "max",
  Unique: "unique",
} as const;
/**
 * Aggregation applied to matching events
 */
export type MeterApiResponseDtoAggregation = ClosedEnum<
  typeof MeterApiResponseDtoAggregation
>;

/**
 * Whether the meter is active or archived
 */
export const MeterApiResponseDtoStatus = {
  Active: "active",
  Archived: "archived",
} as const;
/**
 * Whether the meter is active or archived
 */
export type MeterApiResponseDtoStatus = ClosedEnum<
  typeof MeterApiResponseDtoStatus
>;

export type MeterApiResponseDto = {
  /**
   * Meter ID
   */
  id: string;
  /**
   * Store ID
   */
  storeId: string;
  /**
   * Meter name
   */
  name: string;
  /**
   * Usage event name the meter consumes
   */
  eventName: string;
  /**
   * Aggregation applied to matching events
   */
  aggregation: MeterApiResponseDtoAggregation;
  /**
   * Property the aggregation reduces; null for "count"
   */
  aggregationProperty: string | null;
  /**
   * The meter filter; always present (empty clauses = match all)
   */
  filter: MeterFilterApiResponseDto;
  /**
   * Display unit
   */
  unitLabel: string;
  /**
   * Whether the meter is active or archived
   */
  status: MeterApiResponseDtoStatus;
  /**
   * Creation timestamp (ISO 8601)
   */
  createdAt: string;
  /**
   * Last update timestamp (ISO 8601)
   */
  updatedAt: string;
};

/** @internal */
export const MeterApiResponseDtoAggregation$inboundSchema: z.ZodNativeEnum<
  typeof MeterApiResponseDtoAggregation
> = z.nativeEnum(MeterApiResponseDtoAggregation);
/** @internal */
export const MeterApiResponseDtoAggregation$outboundSchema: z.ZodNativeEnum<
  typeof MeterApiResponseDtoAggregation
> = MeterApiResponseDtoAggregation$inboundSchema;

/** @internal */
export const MeterApiResponseDtoStatus$inboundSchema: z.ZodNativeEnum<
  typeof MeterApiResponseDtoStatus
> = z.nativeEnum(MeterApiResponseDtoStatus);
/** @internal */
export const MeterApiResponseDtoStatus$outboundSchema: z.ZodNativeEnum<
  typeof MeterApiResponseDtoStatus
> = MeterApiResponseDtoStatus$inboundSchema;

/** @internal */
export const MeterApiResponseDto$inboundSchema: z.ZodType<
  MeterApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  store_id: z.string(),
  name: z.string(),
  event_name: z.string(),
  aggregation: MeterApiResponseDtoAggregation$inboundSchema,
  aggregation_property: z.nullable(z.string()),
  filter: MeterFilterApiResponseDto$inboundSchema,
  unit_label: z.string(),
  status: MeterApiResponseDtoStatus$inboundSchema,
  created_at: z.string(),
  updated_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "store_id": "storeId",
    "event_name": "eventName",
    "aggregation_property": "aggregationProperty",
    "unit_label": "unitLabel",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type MeterApiResponseDto$Outbound = {
  id: string;
  store_id: string;
  name: string;
  event_name: string;
  aggregation: string;
  aggregation_property: string | null;
  filter: MeterFilterApiResponseDto$Outbound;
  unit_label: string;
  status: string;
  created_at: string;
  updated_at: string;
};

/** @internal */
export const MeterApiResponseDto$outboundSchema: z.ZodType<
  MeterApiResponseDto$Outbound,
  z.ZodTypeDef,
  MeterApiResponseDto
> = z.object({
  id: z.string(),
  storeId: z.string(),
  name: z.string(),
  eventName: z.string(),
  aggregation: MeterApiResponseDtoAggregation$outboundSchema,
  aggregationProperty: z.nullable(z.string()),
  filter: MeterFilterApiResponseDto$outboundSchema,
  unitLabel: z.string(),
  status: MeterApiResponseDtoStatus$outboundSchema,
  createdAt: z.string(),
  updatedAt: z.string(),
}).transform((v) => {
  return remap$(v, {
    storeId: "store_id",
    eventName: "event_name",
    aggregationProperty: "aggregation_property",
    unitLabel: "unit_label",
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

export function meterApiResponseDtoToJSON(
  meterApiResponseDto: MeterApiResponseDto,
): string {
  return JSON.stringify(
    MeterApiResponseDto$outboundSchema.parse(meterApiResponseDto),
  );
}
export function meterApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MeterApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterApiResponseDto' from JSON`,
  );
}
