/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MeterApiResponseDto,
  MeterApiResponseDto$inboundSchema,
  MeterApiResponseDto$Outbound,
  MeterApiResponseDto$outboundSchema,
} from "./meterapiresponsedto.js";

export type MeterListApiResponseDto = {
  /**
   * Object type
   */
  object: string;
  /**
   * Array of meters
   */
  data: Array<MeterApiResponseDto>;
  /**
   * Whether more items exist beyond this page
   */
  hasMore: boolean;
};

/** @internal */
export const MeterListApiResponseDto$inboundSchema: z.ZodType<
  MeterListApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string(),
  data: z.array(MeterApiResponseDto$inboundSchema),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});
/** @internal */
export type MeterListApiResponseDto$Outbound = {
  object: string;
  data: Array<MeterApiResponseDto$Outbound>;
  has_more: boolean;
};

/** @internal */
export const MeterListApiResponseDto$outboundSchema: z.ZodType<
  MeterListApiResponseDto$Outbound,
  z.ZodTypeDef,
  MeterListApiResponseDto
> = z.object({
  object: z.string(),
  data: z.array(MeterApiResponseDto$outboundSchema),
  hasMore: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
  });
});

export function meterListApiResponseDtoToJSON(
  meterListApiResponseDto: MeterListApiResponseDto,
): string {
  return JSON.stringify(
    MeterListApiResponseDto$outboundSchema.parse(meterListApiResponseDto),
  );
}
export function meterListApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MeterListApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterListApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterListApiResponseDto' from JSON`,
  );
}
