/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MeterPreviewDailyApiResponseDto = {
  /**
   * UTC calendar day
   */
  date: string;
  /**
   * Matching events on this day
   */
  eventCount: number;
  /**
   * The aggregation folded over this day alone, as a string for BigInt safety
   */
  value: string;
};

/** @internal */
export const MeterPreviewDailyApiResponseDto$inboundSchema: z.ZodType<
  MeterPreviewDailyApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: z.string(),
  event_count: z.number(),
  value: z.string(),
}).transform((v) => {
  return remap$(v, {
    "event_count": "eventCount",
  });
});
/** @internal */
export type MeterPreviewDailyApiResponseDto$Outbound = {
  date: string;
  event_count: number;
  value: string;
};

/** @internal */
export const MeterPreviewDailyApiResponseDto$outboundSchema: z.ZodType<
  MeterPreviewDailyApiResponseDto$Outbound,
  z.ZodTypeDef,
  MeterPreviewDailyApiResponseDto
> = z.object({
  date: z.string(),
  eventCount: z.number(),
  value: z.string(),
}).transform((v) => {
  return remap$(v, {
    eventCount: "event_count",
  });
});

export function meterPreviewDailyApiResponseDtoToJSON(
  meterPreviewDailyApiResponseDto: MeterPreviewDailyApiResponseDto,
): string {
  return JSON.stringify(
    MeterPreviewDailyApiResponseDto$outboundSchema.parse(
      meterPreviewDailyApiResponseDto,
    ),
  );
}
export function meterPreviewDailyApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<MeterPreviewDailyApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterPreviewDailyApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterPreviewDailyApiResponseDto' from JSON`,
  );
}
