/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  FilterClauseApiRequestDto,
  FilterClauseApiRequestDto$inboundSchema,
  FilterClauseApiRequestDto$Outbound,
  FilterClauseApiRequestDto$outboundSchema,
} from "./filterclauseapirequestdto.js";

/**
 * How the clauses combine
 */
export const Conjunction = {
  And: "and",
  Or: "or",
} as const;
/**
 * How the clauses combine
 */
export type Conjunction = ClosedEnum<typeof Conjunction>;

export type MeterFilterApiRequestDto = {
  /**
   * How the clauses combine
   */
  conjunction: Conjunction;
  /**
   * Filter clauses. An empty list means the meter counts every event with the given event name.
   */
  clauses: Array<FilterClauseApiRequestDto>;
};

/** @internal */
export const Conjunction$inboundSchema: z.ZodNativeEnum<typeof Conjunction> = z
  .nativeEnum(Conjunction);
/** @internal */
export const Conjunction$outboundSchema: z.ZodNativeEnum<typeof Conjunction> =
  Conjunction$inboundSchema;

/** @internal */
export const MeterFilterApiRequestDto$inboundSchema: z.ZodType<
  MeterFilterApiRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  conjunction: Conjunction$inboundSchema,
  clauses: z.array(FilterClauseApiRequestDto$inboundSchema),
});
/** @internal */
export type MeterFilterApiRequestDto$Outbound = {
  conjunction: string;
  clauses: Array<FilterClauseApiRequestDto$Outbound>;
};

/** @internal */
export const MeterFilterApiRequestDto$outboundSchema: z.ZodType<
  MeterFilterApiRequestDto$Outbound,
  z.ZodTypeDef,
  MeterFilterApiRequestDto
> = z.object({
  conjunction: Conjunction$outboundSchema,
  clauses: z.array(FilterClauseApiRequestDto$outboundSchema),
});

export function meterFilterApiRequestDtoToJSON(
  meterFilterApiRequestDto: MeterFilterApiRequestDto,
): string {
  return JSON.stringify(
    MeterFilterApiRequestDto$outboundSchema.parse(meterFilterApiRequestDto),
  );
}
export function meterFilterApiRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<MeterFilterApiRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MeterFilterApiRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MeterFilterApiRequestDto' from JSON`,
  );
}
