/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EntryInputDto,
  EntryInputDto$inboundSchema,
  EntryInputDto$Outbound,
  EntryInputDto$outboundSchema,
} from "./entryinputdto.js";

export type PostTransactionDto = {
  /**
   * Your reference ID to link this transaction to an event in your system
   */
  reference: string;
  /**
   * Idempotency key to prevent duplicate transactions
   */
  idempotencyKey: string;
  /**
   * Array of entries. Must have at least 2 entries and the total debits must equal total credits.
   */
  entries: Array<EntryInputDto>;
};

/** @internal */
export const PostTransactionDto$inboundSchema: z.ZodType<
  PostTransactionDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  reference: z.string(),
  idempotency_key: z.string(),
  entries: z.array(EntryInputDto$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "idempotency_key": "idempotencyKey",
  });
});
/** @internal */
export type PostTransactionDto$Outbound = {
  reference: string;
  idempotency_key: string;
  entries: Array<EntryInputDto$Outbound>;
};

/** @internal */
export const PostTransactionDto$outboundSchema: z.ZodType<
  PostTransactionDto$Outbound,
  z.ZodTypeDef,
  PostTransactionDto
> = z.object({
  reference: z.string(),
  idempotencyKey: z.string(),
  entries: z.array(EntryInputDto$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency_key",
  });
});

export function postTransactionDtoToJSON(
  postTransactionDto: PostTransactionDto,
): string {
  return JSON.stringify(
    PostTransactionDto$outboundSchema.parse(postTransactionDto),
  );
}
export function postTransactionDtoFromJSON(
  jsonString: string,
): SafeParseResult<PostTransactionDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostTransactionDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostTransactionDto' from JSON`,
  );
}
