/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PreviewUsageEventReportApiDto,
  PreviewUsageEventReportApiDto$inboundSchema,
  PreviewUsageEventReportApiDto$Outbound,
  PreviewUsageEventReportApiDto$outboundSchema,
} from "./previewusageeventreportapidto.js";

export type PreviewUsageEventsApiResponseDto = {
  /**
   * Whether the batch as submitted would be accepted by POST /v1/events/ingest (ingest validation is all-or-nothing)
   */
  valid: boolean;
  /**
   * Per-event report, in submission order
   */
  events: Array<PreviewUsageEventReportApiDto>;
};

/** @internal */
export const PreviewUsageEventsApiResponseDto$inboundSchema: z.ZodType<
  PreviewUsageEventsApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  valid: z.boolean(),
  events: z.array(PreviewUsageEventReportApiDto$inboundSchema),
});
/** @internal */
export type PreviewUsageEventsApiResponseDto$Outbound = {
  valid: boolean;
  events: Array<PreviewUsageEventReportApiDto$Outbound>;
};

/** @internal */
export const PreviewUsageEventsApiResponseDto$outboundSchema: z.ZodType<
  PreviewUsageEventsApiResponseDto$Outbound,
  z.ZodTypeDef,
  PreviewUsageEventsApiResponseDto
> = z.object({
  valid: z.boolean(),
  events: z.array(PreviewUsageEventReportApiDto$outboundSchema),
});

export function previewUsageEventsApiResponseDtoToJSON(
  previewUsageEventsApiResponseDto: PreviewUsageEventsApiResponseDto,
): string {
  return JSON.stringify(
    PreviewUsageEventsApiResponseDto$outboundSchema.parse(
      previewUsageEventsApiResponseDto,
    ),
  );
}
export function previewUsageEventsApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<PreviewUsageEventsApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewUsageEventsApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewUsageEventsApiResponseDto' from JSON`,
  );
}
