/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PreviewUsageEventWarningApiDto,
  PreviewUsageEventWarningApiDto$inboundSchema,
  PreviewUsageEventWarningApiDto$Outbound,
  PreviewUsageEventWarningApiDto$outboundSchema,
} from "./previewusageeventwarningapidto.js";

/**
 * Why the event is invalid. Null when valid.
 */
export type ErrorT = {
  /**
   * Validation error code
   */
  code: string;
  /**
   * What is wrong with the event
   */
  message: string;
  /**
   * The offending field, named as you sent it
   */
  param?: string | null | undefined;
};

export type PreviewUsageEventReportApiDto = {
  /**
   * Whether this event would pass ingest validation
   */
  valid: boolean;
  /**
   * The idempotency key the event would be recorded under — your `event_id`, trimmed. Null when the event is invalid, and also null when you omitted `event_id`: ingest generates a fresh id at accept time, so previewing one would be misleading.
   */
  eventId?: string | null | undefined;
  /**
   * The Creem customer the usage would be attributed to — resolved from your `external_customer_id` where you sent one. Null when the event is invalid or the reference does not resolve.
   */
  customerId?: string | null | undefined;
  /**
   * Why the event is invalid. Null when valid.
   */
  error?: ErrorT | null | undefined;
  /**
   * Advisory: would this event deduplicate against an already-stored event (or an earlier entry of this batch)? Null when the event is invalid. Racy by nature — a signal for debugging retries, not a guarantee.
   */
  duplicate?: boolean | null | undefined;
  /**
   * Ids of the active meters that would consume this event, at preview time
   */
  matchedMeters: Array<string>;
  /**
   * Advisory warnings — same semantics as ingest warnings
   */
  warnings: Array<PreviewUsageEventWarningApiDto>;
};

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z
  .object({
    code: z.string(),
    message: z.string(),
    param: z.nullable(z.string()).optional(),
  });
/** @internal */
export type ErrorT$Outbound = {
  code: string;
  message: string;
  param?: string | null | undefined;
};

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<
  ErrorT$Outbound,
  z.ZodTypeDef,
  ErrorT
> = z.object({
  code: z.string(),
  message: z.string(),
  param: z.nullable(z.string()).optional(),
});

export function errorToJSON(errorT: ErrorT): string {
  return JSON.stringify(ErrorT$outboundSchema.parse(errorT));
}
export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const PreviewUsageEventReportApiDto$inboundSchema: z.ZodType<
  PreviewUsageEventReportApiDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  valid: z.boolean(),
  event_id: z.nullable(z.string()).optional(),
  customer_id: z.nullable(z.string()).optional(),
  error: z.nullable(z.lazy(() => ErrorT$inboundSchema)).optional(),
  duplicate: z.nullable(z.boolean()).optional(),
  matched_meters: z.array(z.string()),
  warnings: z.array(PreviewUsageEventWarningApiDto$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "event_id": "eventId",
    "customer_id": "customerId",
    "matched_meters": "matchedMeters",
  });
});
/** @internal */
export type PreviewUsageEventReportApiDto$Outbound = {
  valid: boolean;
  event_id?: string | null | undefined;
  customer_id?: string | null | undefined;
  error?: ErrorT$Outbound | null | undefined;
  duplicate?: boolean | null | undefined;
  matched_meters: Array<string>;
  warnings: Array<PreviewUsageEventWarningApiDto$Outbound>;
};

/** @internal */
export const PreviewUsageEventReportApiDto$outboundSchema: z.ZodType<
  PreviewUsageEventReportApiDto$Outbound,
  z.ZodTypeDef,
  PreviewUsageEventReportApiDto
> = z.object({
  valid: z.boolean(),
  eventId: z.nullable(z.string()).optional(),
  customerId: z.nullable(z.string()).optional(),
  error: z.nullable(z.lazy(() => ErrorT$outboundSchema)).optional(),
  duplicate: z.nullable(z.boolean()).optional(),
  matchedMeters: z.array(z.string()),
  warnings: z.array(PreviewUsageEventWarningApiDto$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    eventId: "event_id",
    customerId: "customer_id",
    matchedMeters: "matched_meters",
  });
});

export function previewUsageEventReportApiDtoToJSON(
  previewUsageEventReportApiDto: PreviewUsageEventReportApiDto,
): string {
  return JSON.stringify(
    PreviewUsageEventReportApiDto$outboundSchema.parse(
      previewUsageEventReportApiDto,
    ),
  );
}
export function previewUsageEventReportApiDtoFromJSON(
  jsonString: string,
): SafeParseResult<PreviewUsageEventReportApiDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewUsageEventReportApiDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewUsageEventReportApiDto' from JSON`,
  );
}
