/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MeterFilterApiRequestDto,
  MeterFilterApiRequestDto$inboundSchema,
  MeterFilterApiRequestDto$Outbound,
  MeterFilterApiRequestDto$outboundSchema,
} from "./meterfilterapirequestdto.js";

/**
 * Aggregation to dry-run
 */
export const PreviewMeterApiRequestDtoAggregation = {
  Count: "count",
  Sum: "sum",
  Average: "average",
  Min: "min",
  Max: "max",
  Unique: "unique",
} as const;
/**
 * Aggregation to dry-run
 */
export type PreviewMeterApiRequestDtoAggregation = ClosedEnum<
  typeof PreviewMeterApiRequestDtoAggregation
>;

export type PreviewMeterApiRequestDto = {
  /**
   * The usage event name the candidate meter would consume
   */
  eventName: string;
  /**
   * Aggregation to dry-run
   */
  aggregation: PreviewMeterApiRequestDtoAggregation;
  /**
   * Event property the aggregation reduces. Required for every aggregation except "count".
   */
  aggregationProperty?: string | undefined;
  /**
   * Optional filter to dry-run alongside the aggregation
   */
  filter?: MeterFilterApiRequestDto | undefined;
  /**
   * Display unit for the preview. Cosmetic (nothing is persisted); defaults to "units".
   */
  unitLabel?: string | undefined;
};

/** @internal */
export const PreviewMeterApiRequestDtoAggregation$inboundSchema:
  z.ZodNativeEnum<typeof PreviewMeterApiRequestDtoAggregation> = z.nativeEnum(
    PreviewMeterApiRequestDtoAggregation,
  );
/** @internal */
export const PreviewMeterApiRequestDtoAggregation$outboundSchema:
  z.ZodNativeEnum<typeof PreviewMeterApiRequestDtoAggregation> =
    PreviewMeterApiRequestDtoAggregation$inboundSchema;

/** @internal */
export const PreviewMeterApiRequestDto$inboundSchema: z.ZodType<
  PreviewMeterApiRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  event_name: z.string(),
  aggregation: PreviewMeterApiRequestDtoAggregation$inboundSchema,
  aggregation_property: z.string().optional(),
  filter: MeterFilterApiRequestDto$inboundSchema.optional(),
  unit_label: z.string().default("units"),
}).transform((v) => {
  return remap$(v, {
    "event_name": "eventName",
    "aggregation_property": "aggregationProperty",
    "unit_label": "unitLabel",
  });
});
/** @internal */
export type PreviewMeterApiRequestDto$Outbound = {
  event_name: string;
  aggregation: string;
  aggregation_property?: string | undefined;
  filter?: MeterFilterApiRequestDto$Outbound | undefined;
  unit_label: string;
};

/** @internal */
export const PreviewMeterApiRequestDto$outboundSchema: z.ZodType<
  PreviewMeterApiRequestDto$Outbound,
  z.ZodTypeDef,
  PreviewMeterApiRequestDto
> = z.object({
  eventName: z.string(),
  aggregation: PreviewMeterApiRequestDtoAggregation$outboundSchema,
  aggregationProperty: z.string().optional(),
  filter: MeterFilterApiRequestDto$outboundSchema.optional(),
  unitLabel: z.string().default("units"),
}).transform((v) => {
  return remap$(v, {
    eventName: "event_name",
    aggregationProperty: "aggregation_property",
    unitLabel: "unit_label",
  });
});

export function previewMeterApiRequestDtoToJSON(
  previewMeterApiRequestDto: PreviewMeterApiRequestDto,
): string {
  return JSON.stringify(
    PreviewMeterApiRequestDto$outboundSchema.parse(previewMeterApiRequestDto),
  );
}
export function previewMeterApiRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<PreviewMeterApiRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewMeterApiRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewMeterApiRequestDto' from JSON`,
  );
}
