/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PreviewUsageEventWarningApiDto,
  PreviewUsageEventWarningApiDto$inboundSchema,
  PreviewUsageEventWarningApiDto$Outbound,
  PreviewUsageEventWarningApiDto$outboundSchema,
} from "./previewusageeventwarningapidto.js";

/**
 * The idempotency key the event would be recorded under — your `event_id`, trimmed. Null when the event is invalid, and also null when you omitted `event_id`: ingest generates a fresh id at accept time, so previewing one would be misleading.
 */
export type EventId = {};

/**
 * The offending field, named as you sent it
 */
export type Param = {};

/**
 * Why the event is invalid. Null when valid.
 */
export type ErrorT = {
  /**
   * Validation error code
   */
  code: string;
  /**
   * What is wrong with the event
   */
  message: string;
  /**
   * The offending field, named as you sent it
   */
  param?: Param | null | undefined;
};

/**
 * Advisory: would this event deduplicate against an already-stored event (or an earlier entry of this batch)? Null when the event is invalid. Racy by nature — a signal for debugging retries, not a guarantee.
 */
export type Duplicate = {};

export type PreviewUsageEventReportApiDto = {
  /**
   * Whether this event would pass ingest validation
   */
  valid: boolean;
  /**
   * The idempotency key the event would be recorded under — your `event_id`, trimmed. Null when the event is invalid, and also null when you omitted `event_id`: ingest generates a fresh id at accept time, so previewing one would be misleading.
   */
  eventId?: EventId | null | undefined;
  /**
   * Why the event is invalid. Null when valid.
   */
  error?: ErrorT | null | undefined;
  /**
   * Advisory: would this event deduplicate against an already-stored event (or an earlier entry of this batch)? Null when the event is invalid. Racy by nature — a signal for debugging retries, not a guarantee.
   */
  duplicate?: Duplicate | null | undefined;
  /**
   * Ids of the active meters that would consume this event, at preview time
   */
  matchedMeters: Array<string>;
  /**
   * Advisory warnings — same semantics as ingest warnings
   */
  warnings: Array<PreviewUsageEventWarningApiDto>;
};

/** @internal */
export const EventId$inboundSchema: z.ZodType<EventId, z.ZodTypeDef, unknown> =
  z.object({});
/** @internal */
export type EventId$Outbound = {};

/** @internal */
export const EventId$outboundSchema: z.ZodType<
  EventId$Outbound,
  z.ZodTypeDef,
  EventId
> = z.object({});

export function eventIdToJSON(eventId: EventId): string {
  return JSON.stringify(EventId$outboundSchema.parse(eventId));
}
export function eventIdFromJSON(
  jsonString: string,
): SafeParseResult<EventId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventId' from JSON`,
  );
}

/** @internal */
export const Param$inboundSchema: z.ZodType<Param, z.ZodTypeDef, unknown> = z
  .object({});
/** @internal */
export type Param$Outbound = {};

/** @internal */
export const Param$outboundSchema: z.ZodType<
  Param$Outbound,
  z.ZodTypeDef,
  Param
> = z.object({});

export function paramToJSON(param: Param): string {
  return JSON.stringify(Param$outboundSchema.parse(param));
}
export function paramFromJSON(
  jsonString: string,
): SafeParseResult<Param, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Param$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Param' from JSON`,
  );
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z
  .object({
    code: z.string(),
    message: z.string(),
    param: z.nullable(z.lazy(() => Param$inboundSchema)).optional(),
  });
/** @internal */
export type ErrorT$Outbound = {
  code: string;
  message: string;
  param?: Param$Outbound | null | undefined;
};

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<
  ErrorT$Outbound,
  z.ZodTypeDef,
  ErrorT
> = z.object({
  code: z.string(),
  message: z.string(),
  param: z.nullable(z.lazy(() => Param$outboundSchema)).optional(),
});

export function errorToJSON(errorT: ErrorT): string {
  return JSON.stringify(ErrorT$outboundSchema.parse(errorT));
}
export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const Duplicate$inboundSchema: z.ZodType<
  Duplicate,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type Duplicate$Outbound = {};

/** @internal */
export const Duplicate$outboundSchema: z.ZodType<
  Duplicate$Outbound,
  z.ZodTypeDef,
  Duplicate
> = z.object({});

export function duplicateToJSON(duplicate: Duplicate): string {
  return JSON.stringify(Duplicate$outboundSchema.parse(duplicate));
}
export function duplicateFromJSON(
  jsonString: string,
): SafeParseResult<Duplicate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Duplicate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Duplicate' from JSON`,
  );
}

/** @internal */
export const PreviewUsageEventReportApiDto$inboundSchema: z.ZodType<
  PreviewUsageEventReportApiDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  valid: z.boolean(),
  event_id: z.nullable(z.lazy(() => EventId$inboundSchema)).optional(),
  error: z.nullable(z.lazy(() => ErrorT$inboundSchema)).optional(),
  duplicate: z.nullable(z.lazy(() => Duplicate$inboundSchema)).optional(),
  matched_meters: z.array(z.string()),
  warnings: z.array(PreviewUsageEventWarningApiDto$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "event_id": "eventId",
    "matched_meters": "matchedMeters",
  });
});
/** @internal */
export type PreviewUsageEventReportApiDto$Outbound = {
  valid: boolean;
  event_id?: EventId$Outbound | null | undefined;
  error?: ErrorT$Outbound | null | undefined;
  duplicate?: Duplicate$Outbound | null | undefined;
  matched_meters: Array<string>;
  warnings: Array<PreviewUsageEventWarningApiDto$Outbound>;
};

/** @internal */
export const PreviewUsageEventReportApiDto$outboundSchema: z.ZodType<
  PreviewUsageEventReportApiDto$Outbound,
  z.ZodTypeDef,
  PreviewUsageEventReportApiDto
> = z.object({
  valid: z.boolean(),
  eventId: z.nullable(z.lazy(() => EventId$outboundSchema)).optional(),
  error: z.nullable(z.lazy(() => ErrorT$outboundSchema)).optional(),
  duplicate: z.nullable(z.lazy(() => Duplicate$outboundSchema)).optional(),
  matchedMeters: z.array(z.string()),
  warnings: z.array(PreviewUsageEventWarningApiDto$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    eventId: "event_id",
    matchedMeters: "matched_meters",
  });
});

export function previewUsageEventReportApiDtoToJSON(
  previewUsageEventReportApiDto: PreviewUsageEventReportApiDto,
): string {
  return JSON.stringify(
    PreviewUsageEventReportApiDto$outboundSchema.parse(
      previewUsageEventReportApiDto,
    ),
  );
}
export function previewUsageEventReportApiDtoFromJSON(
  jsonString: string,
): SafeParseResult<PreviewUsageEventReportApiDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewUsageEventReportApiDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewUsageEventReportApiDto' from JSON`,
  );
}
