/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Warning code — same set as ingest warnings
 */
export const PreviewUsageEventWarningApiDtoCode = {
  NoMatchingMeter: "no_matching_meter",
  MeterArchived: "meter_archived",
  TimestampOutsideLateWindow: "timestamp_outside_late_window",
} as const;
/**
 * Warning code — same set as ingest warnings
 */
export type PreviewUsageEventWarningApiDtoCode = ClosedEnum<
  typeof PreviewUsageEventWarningApiDtoCode
>;

export type PreviewUsageEventWarningApiDto = {
  /**
   * Warning code — same set as ingest warnings
   */
  code: PreviewUsageEventWarningApiDtoCode;
  /**
   * Human-readable explanation
   */
  message: string;
};

/** @internal */
export const PreviewUsageEventWarningApiDtoCode$inboundSchema: z.ZodNativeEnum<
  typeof PreviewUsageEventWarningApiDtoCode
> = z.nativeEnum(PreviewUsageEventWarningApiDtoCode);
/** @internal */
export const PreviewUsageEventWarningApiDtoCode$outboundSchema: z.ZodNativeEnum<
  typeof PreviewUsageEventWarningApiDtoCode
> = PreviewUsageEventWarningApiDtoCode$inboundSchema;

/** @internal */
export const PreviewUsageEventWarningApiDto$inboundSchema: z.ZodType<
  PreviewUsageEventWarningApiDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: PreviewUsageEventWarningApiDtoCode$inboundSchema,
  message: z.string(),
});
/** @internal */
export type PreviewUsageEventWarningApiDto$Outbound = {
  code: string;
  message: string;
};

/** @internal */
export const PreviewUsageEventWarningApiDto$outboundSchema: z.ZodType<
  PreviewUsageEventWarningApiDto$Outbound,
  z.ZodTypeDef,
  PreviewUsageEventWarningApiDto
> = z.object({
  code: PreviewUsageEventWarningApiDtoCode$outboundSchema,
  message: z.string(),
});

export function previewUsageEventWarningApiDtoToJSON(
  previewUsageEventWarningApiDto: PreviewUsageEventWarningApiDto,
): string {
  return JSON.stringify(
    PreviewUsageEventWarningApiDto$outboundSchema.parse(
      previewUsageEventWarningApiDto,
    ),
  );
}
export function previewUsageEventWarningApiDtoFromJSON(
  jsonString: string,
): SafeParseResult<PreviewUsageEventWarningApiDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewUsageEventWarningApiDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewUsageEventWarningApiDto' from JSON`,
  );
}
