/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Unit of a custom billing period. Required when `billing_period` is `custom`; must be omitted for preset billing periods.
 */
export const ProductRequestRecurringInterval = {
  Day: "day",
  Week: "week",
  Month: "month",
  Year: "year",
} as const;
/**
 * Unit of a custom billing period. Required when `billing_period` is `custom`; must be omitted for preset billing periods.
 */
export type ProductRequestRecurringInterval = ClosedEnum<
  typeof ProductRequestRecurringInterval
>;

/** @internal */
export const ProductRequestRecurringInterval$inboundSchema: z.ZodNativeEnum<
  typeof ProductRequestRecurringInterval
> = z.nativeEnum(ProductRequestRecurringInterval);
/** @internal */
export const ProductRequestRecurringInterval$outboundSchema: z.ZodNativeEnum<
  typeof ProductRequestRecurringInterval
> = ProductRequestRecurringInterval$inboundSchema;
