/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Billing interval. Required when `billing_type` is `recurring`. Use a preset for the common cadences, or `custom` together with `recurring_interval` + `recurring_interval_count` for anything else (e.g. weekly).
 */
export const ProductRequestBillingPeriod = {
  Once: "once",
  EveryDay: "every-day",
  EveryMonth: "every-month",
  EveryThreeMonths: "every-three-months",
  EverySixMonths: "every-six-months",
  EveryYear: "every-year",
  Custom: "custom",
} as const;
/**
 * Billing interval. Required when `billing_type` is `recurring`. Use a preset for the common cadences, or `custom` together with `recurring_interval` + `recurring_interval_count` for anything else (e.g. weekly).
 */
export type ProductRequestBillingPeriod = ClosedEnum<
  typeof ProductRequestBillingPeriod
>;

/** @internal */
export const ProductRequestBillingPeriod$inboundSchema: z.ZodNativeEnum<
  typeof ProductRequestBillingPeriod
> = z.nativeEnum(ProductRequestBillingPeriod);
/** @internal */
export const ProductRequestBillingPeriod$outboundSchema: z.ZodNativeEnum<
  typeof ProductRequestBillingPeriod
> = ProductRequestBillingPeriod$inboundSchema;
