/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The feature type. Only `customerCredits` can be managed through the API.
 */
export const ProductFeatureRequestType = {
  CustomerCredits: "customerCredits",
} as const;
/**
 * The feature type. Only `customerCredits` can be managed through the API.
 */
export type ProductFeatureRequestType = ClosedEnum<
  typeof ProductFeatureRequestType
>;

/** @internal */
export const ProductFeatureRequestType$inboundSchema: z.ZodNativeEnum<
  typeof ProductFeatureRequestType
> = z.nativeEnum(ProductFeatureRequestType);
/** @internal */
export const ProductFeatureRequestType$outboundSchema: z.ZodNativeEnum<
  typeof ProductFeatureRequestType
> = ProductFeatureRequestType$inboundSchema;
