/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomerCreditsFeatureEntity,
  CustomerCreditsFeatureEntity$inboundSchema,
  CustomerCreditsFeatureEntity$Outbound,
  CustomerCreditsFeatureEntity$outboundSchema,
} from "./customercreditsfeatureentity.js";
import {
  ProductFeatureRequestType,
  ProductFeatureRequestType$inboundSchema,
  ProductFeatureRequestType$outboundSchema,
} from "./productfeaturerequesttype.js";

export type ProductFeatureRequestEntity = {
  /**
   * Identifier of an existing feature to edit in place (update only). Omit to add a new feature.
   */
  id?: string | undefined;
  /**
   * The feature type. Only `customerCredits` can be managed through the API.
   */
  type: ProductFeatureRequestType;
  /**
   * A brief description of the feature, shown to the customer.
   */
  description: string;
  /**
   * The credit grant this feature carries.
   */
  customerCredits: CustomerCreditsFeatureEntity;
};

/** @internal */
export const ProductFeatureRequestEntity$inboundSchema: z.ZodType<
  ProductFeatureRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  type: ProductFeatureRequestType$inboundSchema,
  description: z.string(),
  customer_credits: CustomerCreditsFeatureEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "customer_credits": "customerCredits",
  });
});
/** @internal */
export type ProductFeatureRequestEntity$Outbound = {
  id?: string | undefined;
  type: string;
  description: string;
  customer_credits: CustomerCreditsFeatureEntity$Outbound;
};

/** @internal */
export const ProductFeatureRequestEntity$outboundSchema: z.ZodType<
  ProductFeatureRequestEntity$Outbound,
  z.ZodTypeDef,
  ProductFeatureRequestEntity
> = z.object({
  id: z.string().optional(),
  type: ProductFeatureRequestType$outboundSchema,
  description: z.string(),
  customerCredits: CustomerCreditsFeatureEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    customerCredits: "customer_credits",
  });
});

export function productFeatureRequestEntityToJSON(
  productFeatureRequestEntity: ProductFeatureRequestEntity,
): string {
  return JSON.stringify(
    ProductFeatureRequestEntity$outboundSchema.parse(
      productFeatureRequestEntity,
    ),
  );
}
export function productFeatureRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<ProductFeatureRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductFeatureRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductFeatureRequestEntity' from JSON`,
  );
}
