/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * How the share is calculated. Currently always `percentage` — the recipient receives `amount` percent of the split net.
 */
export const SplitRecipientEntityType = {
  Fixed: "fixed",
  Percentage: "percentage",
} as const;
/**
 * How the share is calculated. Currently always `percentage` — the recipient receives `amount` percent of the split net.
 */
export type SplitRecipientEntityType = ClosedEnum<
  typeof SplitRecipientEntityType
>;

/**
 * The kind of recipient. `store` and `user` are resolved (active) recipients; `email` is an invitee who has not yet accepted (the split share is held until they do).
 */
export const SplitRecipientEntityRecipientType = {
  Store: "store",
  User: "user",
  Email: "email",
} as const;
/**
 * The kind of recipient. `store` and `user` are resolved (active) recipients; `email` is an invitee who has not yet accepted (the split share is held until they do).
 */
export type SplitRecipientEntityRecipientType = ClosedEnum<
  typeof SplitRecipientEntityRecipientType
>;

/**
 * Invite lifecycle for email-type recipients that have not been accepted yet: `pending` (awaiting acceptance) or `declined`. Absent for resolved store/user recipients.
 */
export const InviteStatus = {
  Pending: "pending",
  Declined: "declined",
} as const;
/**
 * Invite lifecycle for email-type recipients that have not been accepted yet: `pending` (awaiting acceptance) or `declined`. Absent for resolved store/user recipients.
 */
export type InviteStatus = ClosedEnum<typeof InviteStatus>;

export type SplitRecipientEntity = {
  /**
   * How the share is calculated. Currently always `percentage` — the recipient receives `amount` percent of the split net.
   */
  type: SplitRecipientEntityType;
  /**
   * The kind of recipient. `store` and `user` are resolved (active) recipients; `email` is an invitee who has not yet accepted (the split share is held until they do).
   */
  recipientType: SplitRecipientEntityRecipientType;
  /**
   * Reference to the recipient: a store id (`recipient_type: store`), a user id (`recipient_type: user`), or a masked email address (`recipient_type: email`). Raw invitee email addresses are never returned.
   */
  recipientReference: string;
  /**
   * The recipient share, as a percentage of the split net (e.g. 25 = 25%).
   */
  amount: number;
  /**
   * Whether this recipient is currently receiving its share. Email invitees start disabled until they accept.
   */
  enabled: boolean;
  /**
   * Invite lifecycle for email-type recipients that have not been accepted yet: `pending` (awaiting acceptance) or `declined`. Absent for resolved store/user recipients.
   */
  inviteStatus?: InviteStatus | null | undefined;
};

/** @internal */
export const SplitRecipientEntityType$inboundSchema: z.ZodNativeEnum<
  typeof SplitRecipientEntityType
> = z.nativeEnum(SplitRecipientEntityType);
/** @internal */
export const SplitRecipientEntityType$outboundSchema: z.ZodNativeEnum<
  typeof SplitRecipientEntityType
> = SplitRecipientEntityType$inboundSchema;

/** @internal */
export const SplitRecipientEntityRecipientType$inboundSchema: z.ZodNativeEnum<
  typeof SplitRecipientEntityRecipientType
> = z.nativeEnum(SplitRecipientEntityRecipientType);
/** @internal */
export const SplitRecipientEntityRecipientType$outboundSchema: z.ZodNativeEnum<
  typeof SplitRecipientEntityRecipientType
> = SplitRecipientEntityRecipientType$inboundSchema;

/** @internal */
export const InviteStatus$inboundSchema: z.ZodNativeEnum<typeof InviteStatus> =
  z.nativeEnum(InviteStatus);
/** @internal */
export const InviteStatus$outboundSchema: z.ZodNativeEnum<typeof InviteStatus> =
  InviteStatus$inboundSchema;

/** @internal */
export const SplitRecipientEntity$inboundSchema: z.ZodType<
  SplitRecipientEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: SplitRecipientEntityType$inboundSchema,
  recipient_type: SplitRecipientEntityRecipientType$inboundSchema,
  recipient_reference: z.string(),
  amount: z.number(),
  enabled: z.boolean(),
  invite_status: z.nullable(InviteStatus$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "recipient_type": "recipientType",
    "recipient_reference": "recipientReference",
    "invite_status": "inviteStatus",
  });
});
/** @internal */
export type SplitRecipientEntity$Outbound = {
  type: string;
  recipient_type: string;
  recipient_reference: string;
  amount: number;
  enabled: boolean;
  invite_status?: string | null | undefined;
};

/** @internal */
export const SplitRecipientEntity$outboundSchema: z.ZodType<
  SplitRecipientEntity$Outbound,
  z.ZodTypeDef,
  SplitRecipientEntity
> = z.object({
  type: SplitRecipientEntityType$outboundSchema,
  recipientType: SplitRecipientEntityRecipientType$outboundSchema,
  recipientReference: z.string(),
  amount: z.number(),
  enabled: z.boolean(),
  inviteStatus: z.nullable(InviteStatus$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    recipientType: "recipient_type",
    recipientReference: "recipient_reference",
    inviteStatus: "invite_status",
  });
});

export function splitRecipientEntityToJSON(
  splitRecipientEntity: SplitRecipientEntity,
): string {
  return JSON.stringify(
    SplitRecipientEntity$outboundSchema.parse(splitRecipientEntity),
  );
}
export function splitRecipientEntityFromJSON(
  jsonString: string,
): SafeParseResult<SplitRecipientEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SplitRecipientEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SplitRecipientEntity' from JSON`,
  );
}
