/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EnvironmentMode,
  EnvironmentMode$inboundSchema,
  EnvironmentMode$outboundSchema,
} from "./environmentmode.js";
import {
  SplitRecipientEntity,
  SplitRecipientEntity$inboundSchema,
  SplitRecipientEntity$Outbound,
  SplitRecipientEntity$outboundSchema,
} from "./splitrecipiententity.js";

/**
 * What the split applies to: `store` (every payment to the store) or `product` (payments for a specific product).
 */
export const SplitEntityType = {
  Store: "store",
  Product: "product",
} as const;
/**
 * What the split applies to: `store` (every payment to the store) or `product` (payments for a specific product).
 */
export type SplitEntityType = ClosedEnum<typeof SplitEntityType>;

export type SplitEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: EnvironmentMode;
  /**
   * String representing the object's type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * The id of the store that owns this split.
   */
  storeId: string;
  /**
   * A human-readable description of the split.
   */
  description?: string | null | undefined;
  /**
   * What the split applies to: `store` (every payment to the store) or `product` (payments for a specific product).
   */
  type: SplitEntityType;
  /**
   * The id of the entity the split applies to: the store id when `type` is `store`, or the product id when `type` is `product`.
   */
  typeReference: string;
  /**
   * Whether the split is active. A split created with email invitees starts disabled and activates once the first invitee accepts.
   */
  enabled: boolean;
  /**
   * The recipients of the split and their shares.
   */
  recipients: Array<SplitRecipientEntity>;
  /**
   * Creation date of the split as a timestamp.
   */
  createdAt: number;
};

/** @internal */
export const SplitEntityType$inboundSchema: z.ZodNativeEnum<
  typeof SplitEntityType
> = z.nativeEnum(SplitEntityType);
/** @internal */
export const SplitEntityType$outboundSchema: z.ZodNativeEnum<
  typeof SplitEntityType
> = SplitEntityType$inboundSchema;

/** @internal */
export const SplitEntity$inboundSchema: z.ZodType<
  SplitEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$inboundSchema,
  object: z.string(),
  store_id: z.string(),
  description: z.nullable(z.string()).optional(),
  type: SplitEntityType$inboundSchema,
  type_reference: z.string(),
  enabled: z.boolean(),
  recipients: z.array(SplitRecipientEntity$inboundSchema),
  created_at: z.number(),
}).transform((v) => {
  return remap$(v, {
    "store_id": "storeId",
    "type_reference": "typeReference",
    "created_at": "createdAt",
  });
});
/** @internal */
export type SplitEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  store_id: string;
  description?: string | null | undefined;
  type: string;
  type_reference: string;
  enabled: boolean;
  recipients: Array<SplitRecipientEntity$Outbound>;
  created_at: number;
};

/** @internal */
export const SplitEntity$outboundSchema: z.ZodType<
  SplitEntity$Outbound,
  z.ZodTypeDef,
  SplitEntity
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$outboundSchema,
  object: z.string(),
  storeId: z.string(),
  description: z.nullable(z.string()).optional(),
  type: SplitEntityType$outboundSchema,
  typeReference: z.string(),
  enabled: z.boolean(),
  recipients: z.array(SplitRecipientEntity$outboundSchema),
  createdAt: z.number(),
}).transform((v) => {
  return remap$(v, {
    storeId: "store_id",
    typeReference: "type_reference",
    createdAt: "created_at",
  });
});

export function splitEntityToJSON(splitEntity: SplitEntity): string {
  return JSON.stringify(SplitEntity$outboundSchema.parse(splitEntity));
}
export function splitEntityFromJSON(
  jsonString: string,
): SafeParseResult<SplitEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SplitEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SplitEntity' from JSON`,
  );
}
