/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TransactionResponseDto,
  TransactionResponseDto$inboundSchema,
  TransactionResponseDto$Outbound,
  TransactionResponseDto$outboundSchema,
} from "./transactionresponsedto.js";

export type TransactionListResponseDto = {
  /**
   * Object type
   */
  object: string;
  /**
   * Array of transactions
   */
  data: Array<TransactionResponseDto>;
  /**
   * Whether more items exist beyond this page
   */
  hasMore: boolean;
};

/** @internal */
export const TransactionListResponseDto$inboundSchema: z.ZodType<
  TransactionListResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string(),
  data: z.array(TransactionResponseDto$inboundSchema),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});
/** @internal */
export type TransactionListResponseDto$Outbound = {
  object: string;
  data: Array<TransactionResponseDto$Outbound>;
  has_more: boolean;
};

/** @internal */
export const TransactionListResponseDto$outboundSchema: z.ZodType<
  TransactionListResponseDto$Outbound,
  z.ZodTypeDef,
  TransactionListResponseDto
> = z.object({
  object: z.string(),
  data: z.array(TransactionResponseDto$outboundSchema),
  hasMore: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
  });
});

export function transactionListResponseDtoToJSON(
  transactionListResponseDto: TransactionListResponseDto,
): string {
  return JSON.stringify(
    TransactionListResponseDto$outboundSchema.parse(transactionListResponseDto),
  );
}
export function transactionListResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<TransactionListResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionListResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionListResponseDto' from JSON`,
  );
}
