/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
  WebhookEventType$outboundSchema,
} from "./webhookeventtype.js";
import {
  WebhookStatus,
  WebhookStatus$inboundSchema,
  WebhookStatus$outboundSchema,
} from "./webhookstatus.js";

export type UpdateWebhookRequestEntity = {
  /**
   * The HTTPS URL Creem will deliver events to.
   */
  url?: string | undefined;
  /**
   * A human-readable label for the endpoint. Send `null` to clear it.
   */
  name?: string | null | undefined;
  /**
   * Whether the endpoint receives deliveries. Disabled endpoints keep their configuration but receive nothing.
   */
  status?: WebhookStatus | undefined;
  events?: Array<WebhookEventType> | undefined;
};

/** @internal */
export const UpdateWebhookRequestEntity$inboundSchema: z.ZodType<
  UpdateWebhookRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string().optional(),
  name: z.nullable(z.string()).optional(),
  status: WebhookStatus$inboundSchema.optional(),
  events: z.array(WebhookEventType$inboundSchema).optional(),
});
/** @internal */
export type UpdateWebhookRequestEntity$Outbound = {
  url?: string | undefined;
  name?: string | null | undefined;
  status?: string | undefined;
  events?: Array<string> | undefined;
};

/** @internal */
export const UpdateWebhookRequestEntity$outboundSchema: z.ZodType<
  UpdateWebhookRequestEntity$Outbound,
  z.ZodTypeDef,
  UpdateWebhookRequestEntity
> = z.object({
  url: z.string().optional(),
  name: z.nullable(z.string()).optional(),
  status: WebhookStatus$outboundSchema.optional(),
  events: z.array(WebhookEventType$outboundSchema).optional(),
});

export function updateWebhookRequestEntityToJSON(
  updateWebhookRequestEntity: UpdateWebhookRequestEntity,
): string {
  return JSON.stringify(
    UpdateWebhookRequestEntity$outboundSchema.parse(updateWebhookRequestEntity),
  );
}
export function updateWebhookRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookRequestEntity' from JSON`,
  );
}
