/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MeterFilterApiRequestDto,
  MeterFilterApiRequestDto$inboundSchema,
  MeterFilterApiRequestDto$Outbound,
  MeterFilterApiRequestDto$outboundSchema,
} from "./meterfilterapirequestdto.js";

/**
 * New aggregation. Part of the meter definition, so it is only editable while the meter has processed no usage and has no associated purchase. Omit to leave unchanged; `null` is rejected.
 */
export const UpdateMeterApiRequestDtoAggregation = {
  Count: "count",
  Sum: "sum",
  Average: "average",
  Min: "min",
  Max: "max",
  Unique: "unique",
} as const;
/**
 * New aggregation. Part of the meter definition, so it is only editable while the meter has processed no usage and has no associated purchase. Omit to leave unchanged; `null` is rejected.
 */
export type UpdateMeterApiRequestDtoAggregation = ClosedEnum<
  typeof UpdateMeterApiRequestDtoAggregation
>;

export type UpdateMeterApiRequestDto = {
  /**
   * New meter name. Renaming is allowed even after the meter has processed usage — the name is a label, not part of the definition. Must stay unique within the store. Omit to leave unchanged; `null` is rejected.
   */
  name?: string | undefined;
  /**
   * New aggregation. Part of the meter definition, so it is only editable while the meter has processed no usage and has no associated purchase. Omit to leave unchanged; `null` is rejected.
   */
  aggregation?: UpdateMeterApiRequestDtoAggregation | undefined;
  /**
   * New aggregation property. Omit to leave unchanged; send `null` to clear it (only valid when the resulting aggregation is "count").
   */
  aggregationProperty?: string | null | undefined;
  /**
   * New filter. Part of the meter definition (see `aggregation`). Omit to leave unchanged; `null` is rejected — to remove a filter, send one with an empty `clauses` array.
   */
  filter?: MeterFilterApiRequestDto | undefined;
};

/** @internal */
export const UpdateMeterApiRequestDtoAggregation$inboundSchema: z.ZodNativeEnum<
  typeof UpdateMeterApiRequestDtoAggregation
> = z.nativeEnum(UpdateMeterApiRequestDtoAggregation);
/** @internal */
export const UpdateMeterApiRequestDtoAggregation$outboundSchema:
  z.ZodNativeEnum<typeof UpdateMeterApiRequestDtoAggregation> =
    UpdateMeterApiRequestDtoAggregation$inboundSchema;

/** @internal */
export const UpdateMeterApiRequestDto$inboundSchema: z.ZodType<
  UpdateMeterApiRequestDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  aggregation: UpdateMeterApiRequestDtoAggregation$inboundSchema.optional(),
  aggregation_property: z.nullable(z.string()).optional(),
  filter: MeterFilterApiRequestDto$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "aggregation_property": "aggregationProperty",
  });
});
/** @internal */
export type UpdateMeterApiRequestDto$Outbound = {
  name?: string | undefined;
  aggregation?: string | undefined;
  aggregation_property?: string | null | undefined;
  filter?: MeterFilterApiRequestDto$Outbound | undefined;
};

/** @internal */
export const UpdateMeterApiRequestDto$outboundSchema: z.ZodType<
  UpdateMeterApiRequestDto$Outbound,
  z.ZodTypeDef,
  UpdateMeterApiRequestDto
> = z.object({
  name: z.string().optional(),
  aggregation: UpdateMeterApiRequestDtoAggregation$outboundSchema.optional(),
  aggregationProperty: z.nullable(z.string()).optional(),
  filter: MeterFilterApiRequestDto$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    aggregationProperty: "aggregation_property",
  });
});

export function updateMeterApiRequestDtoToJSON(
  updateMeterApiRequestDto: UpdateMeterApiRequestDto,
): string {
  return JSON.stringify(
    UpdateMeterApiRequestDto$outboundSchema.parse(updateMeterApiRequestDto),
  );
}
export function updateMeterApiRequestDtoFromJSON(
  jsonString: string,
): SafeParseResult<UpdateMeterApiRequestDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateMeterApiRequestDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateMeterApiRequestDto' from JSON`,
  );
}
