/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ProductCurrency,
  ProductCurrency$inboundSchema,
  ProductCurrency$outboundSchema,
} from "./productcurrency.js";
import {
  ProductFeatureRequestEntity,
  ProductFeatureRequestEntity$inboundSchema,
  ProductFeatureRequestEntity$Outbound,
  ProductFeatureRequestEntity$outboundSchema,
} from "./productfeaturerequestentity.js";
import {
  ProductRequestBillingPeriod,
  ProductRequestBillingPeriod$inboundSchema,
  ProductRequestBillingPeriod$outboundSchema,
} from "./productrequestbillingperiod.js";
import {
  ProductRequestBillingType,
  ProductRequestBillingType$inboundSchema,
  ProductRequestBillingType$outboundSchema,
} from "./productrequestbillingtype.js";
import {
  ProductRequestRecurringInterval,
  ProductRequestRecurringInterval$inboundSchema,
  ProductRequestRecurringInterval$outboundSchema,
} from "./productrequestrecurringinterval.js";
import {
  TaxMode,
  TaxMode$inboundSchema,
  TaxMode$outboundSchema,
} from "./taxmode.js";
import {
  UsagePriceRequestEntity,
  UsagePriceRequestEntity$inboundSchema,
  UsagePriceRequestEntity$Outbound,
  UsagePriceRequestEntity$outboundSchema,
} from "./usagepricerequestentity.js";

export type UpdateProductRequestEntity = {
  /**
   * Name of the product
   */
  name?: string | undefined;
  /**
   * Description of the product
   */
  description?: string | undefined;
  /**
   * URL of the product image
   */
  imageUrl?: string | undefined;
  /**
   * Ordered list of product image URLs (max 8). The first entry is the cover image; when provided it takes precedence over image_url. An empty list — or an explicit `null` — removes all images. Omit to leave the gallery unchanged.
   */
  imageUrls?: Array<string> | undefined;
  /**
   * Redirect URL after successful payment.
   */
  defaultSuccessUrl?: string | undefined;
  /**
   * The price of the product in cents. Must be 0 (free product) or at least 100 (one whole unit of the currency).
   */
  price?: number | undefined;
  /**
   * Three-letter uppercase ISO 4217 currency code. Must be one of Creem's supported currencies.
   */
  currency?: ProductCurrency | undefined;
  /**
   * Billing method for the product: `recurring` subscription or `onetime` payment.
   */
  billingType?: ProductRequestBillingType | undefined;
  /**
   * Billing interval. Required when `billing_type` is `recurring`. Use a preset for the common cadences, or `custom` together with `recurring_interval` + `recurring_interval_count` for anything else (e.g. weekly).
   */
  billingPeriod?: ProductRequestBillingPeriod | undefined;
  /**
   * Unit of a custom billing period. Required when `billing_period` is `custom`; must be omitted for preset billing periods.
   */
  recurringInterval?: ProductRequestRecurringInterval | undefined;
  /**
   * Number of `recurring_interval` units per billing cycle. Required when `billing_period` is `custom`. Bounds: day 1–365, week 1–52, month 1–24, year 1–3.
   */
  recurringIntervalCount?: number | undefined;
  /**
   * Specifies the tax calculation mode for the transaction. If set to "inclusive," the tax is included in the price. If set to "exclusive," the tax is added on top of the price.
   */
  taxMode?: TaxMode | undefined;
  /**
   * When true, business customers whose valid VAT ID triggers reverse charge pay the price excluding VAT instead of the tax-inclusive price. Only supported for tax-inclusive one-time products; the merchant gives up the VAT portion on those sales. Defaults to false. Omit to leave unchanged.
   */
  businessNetPricing?: boolean | undefined;
  /**
   * Length of the trial period in days. A whole number of days, at least 1. Only supported for recurring products. Omit to leave the trial unchanged; send `null` to remove it (a paid trial's price is cleared with it). Switching `billing_type` to `onetime` removes the trial as well.
   */
  trialPeriodDays?: number | null | undefined;
  /**
   * Amount charged at checkout to start the trial, instead of a free card verification. In cents (100 = $1.00). Requires a trial period and must be at least 100 and lower than `price`; only supported on standard-priced recurring products without pay-what-you-want. Omit to leave unchanged; send `null` or 0 to make the trial free.
   */
  trialPrice?: number | null | undefined;
  /**
   * Enable pay-what-you-want pricing (one-time only).
   */
  payWhatYouWant?: boolean | undefined;
  /**
   * Suggested amount in cents when pay_what_you_want is enabled. Omit to leave unchanged; send `null` to clear it.
   */
  suggestedPrice?: number | undefined;
  /**
   * Metered charges billed on top of the base price, one per meter. Recurring products only. The array is the complete set after the update: omit (or send `null`) to leave charges untouched, send `[]` to remove all, include `id` to edit a charge in place.
   */
  usagePrices?: Array<UsagePriceRequestEntity> | undefined;
  /**
   * Features granted by purchase. Only `customerCredits` (a credit grant into one of the customer credit buckets) can be managed through the API. The array is the complete set of credit features after the update: omit (or send `null`) to leave features untouched, include `id` to edit in place; credit features missing from the array are removed.
   */
  features?: Array<ProductFeatureRequestEntity> | undefined;
};

/** @internal */
export const UpdateProductRequestEntity$inboundSchema: z.ZodType<
  UpdateProductRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  image_url: z.string().optional(),
  image_urls: z.array(z.string()).optional(),
  default_success_url: z.string().optional(),
  price: z.number().int().optional(),
  currency: ProductCurrency$inboundSchema.optional(),
  billing_type: ProductRequestBillingType$inboundSchema.optional(),
  billing_period: ProductRequestBillingPeriod$inboundSchema.optional(),
  recurring_interval: ProductRequestRecurringInterval$inboundSchema.optional(),
  recurring_interval_count: z.number().int().optional(),
  tax_mode: TaxMode$inboundSchema.optional(),
  business_net_pricing: z.boolean().optional(),
  trial_period_days: z.nullable(z.number().int()).optional(),
  trial_price: z.nullable(z.number().int()).optional(),
  pay_what_you_want: z.boolean().optional(),
  suggested_price: z.number().int().optional(),
  usage_prices: z.array(UsagePriceRequestEntity$inboundSchema).optional(),
  features: z.array(ProductFeatureRequestEntity$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "image_url": "imageUrl",
    "image_urls": "imageUrls",
    "default_success_url": "defaultSuccessUrl",
    "billing_type": "billingType",
    "billing_period": "billingPeriod",
    "recurring_interval": "recurringInterval",
    "recurring_interval_count": "recurringIntervalCount",
    "tax_mode": "taxMode",
    "business_net_pricing": "businessNetPricing",
    "trial_period_days": "trialPeriodDays",
    "trial_price": "trialPrice",
    "pay_what_you_want": "payWhatYouWant",
    "suggested_price": "suggestedPrice",
    "usage_prices": "usagePrices",
  });
});
/** @internal */
export type UpdateProductRequestEntity$Outbound = {
  name?: string | undefined;
  description?: string | undefined;
  image_url?: string | undefined;
  image_urls?: Array<string> | undefined;
  default_success_url?: string | undefined;
  price?: number | undefined;
  currency?: string | undefined;
  billing_type?: string | undefined;
  billing_period?: string | undefined;
  recurring_interval?: string | undefined;
  recurring_interval_count?: number | undefined;
  tax_mode?: string | undefined;
  business_net_pricing?: boolean | undefined;
  trial_period_days?: number | null | undefined;
  trial_price?: number | null | undefined;
  pay_what_you_want?: boolean | undefined;
  suggested_price?: number | undefined;
  usage_prices?: Array<UsagePriceRequestEntity$Outbound> | undefined;
  features?: Array<ProductFeatureRequestEntity$Outbound> | undefined;
};

/** @internal */
export const UpdateProductRequestEntity$outboundSchema: z.ZodType<
  UpdateProductRequestEntity$Outbound,
  z.ZodTypeDef,
  UpdateProductRequestEntity
> = z.object({
  name: z.string().optional(),
  description: z.string().optional(),
  imageUrl: z.string().optional(),
  imageUrls: z.array(z.string()).optional(),
  defaultSuccessUrl: z.string().optional(),
  price: z.number().int().optional(),
  currency: ProductCurrency$outboundSchema.optional(),
  billingType: ProductRequestBillingType$outboundSchema.optional(),
  billingPeriod: ProductRequestBillingPeriod$outboundSchema.optional(),
  recurringInterval: ProductRequestRecurringInterval$outboundSchema.optional(),
  recurringIntervalCount: z.number().int().optional(),
  taxMode: TaxMode$outboundSchema.optional(),
  businessNetPricing: z.boolean().optional(),
  trialPeriodDays: z.nullable(z.number().int()).optional(),
  trialPrice: z.nullable(z.number().int()).optional(),
  payWhatYouWant: z.boolean().optional(),
  suggestedPrice: z.number().int().optional(),
  usagePrices: z.array(UsagePriceRequestEntity$outboundSchema).optional(),
  features: z.array(ProductFeatureRequestEntity$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
    imageUrls: "image_urls",
    defaultSuccessUrl: "default_success_url",
    billingType: "billing_type",
    billingPeriod: "billing_period",
    recurringInterval: "recurring_interval",
    recurringIntervalCount: "recurring_interval_count",
    taxMode: "tax_mode",
    businessNetPricing: "business_net_pricing",
    trialPeriodDays: "trial_period_days",
    trialPrice: "trial_price",
    payWhatYouWant: "pay_what_you_want",
    suggestedPrice: "suggested_price",
    usagePrices: "usage_prices",
  });
});

export function updateProductRequestEntityToJSON(
  updateProductRequestEntity: UpdateProductRequestEntity,
): string {
  return JSON.stringify(
    UpdateProductRequestEntity$outboundSchema.parse(updateProductRequestEntity),
  );
}
export function updateProductRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProductRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProductRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProductRequestEntity' from JSON`,
  );
}
