/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateCustomerRequestEntity = {
  /**
   * The ID of the customer to update.
   */
  customerId: string;
  /**
   * The full name of the customer.
   */
  name?: string | undefined;
  /**
   * Additional metadata for the customer. Omit to leave unchanged; send `null` to clear it.
   */
  metadata?: { [k: string]: any } | undefined;
  /**
   * Your own id for this customer. Unique per store; usage ingestion resolves `external_customer_id` against it. Omit to leave unchanged; send `null` to clear it. Trimmed; letters, digits, `_` and `-` only; at most 255 characters.
   */
  externalId?: string | null | undefined;
};

/** @internal */
export const UpdateCustomerRequestEntity$inboundSchema: z.ZodType<
  UpdateCustomerRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_id: z.string(),
  name: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  external_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "external_id": "externalId",
  });
});
/** @internal */
export type UpdateCustomerRequestEntity$Outbound = {
  customer_id: string;
  name?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  external_id?: string | null | undefined;
};

/** @internal */
export const UpdateCustomerRequestEntity$outboundSchema: z.ZodType<
  UpdateCustomerRequestEntity$Outbound,
  z.ZodTypeDef,
  UpdateCustomerRequestEntity
> = z.object({
  customerId: z.string(),
  name: z.string().optional(),
  metadata: z.record(z.any()).optional(),
  externalId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    externalId: "external_id",
  });
});

export function updateCustomerRequestEntityToJSON(
  updateCustomerRequestEntity: UpdateCustomerRequestEntity,
): string {
  return JSON.stringify(
    UpdateCustomerRequestEntity$outboundSchema.parse(
      updateCustomerRequestEntity,
    ),
  );
}
export function updateCustomerRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<UpdateCustomerRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateCustomerRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateCustomerRequestEntity' from JSON`,
  );
}
