/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UsagePriceSettlementMode,
  UsagePriceSettlementMode$inboundSchema,
  UsagePriceSettlementMode$outboundSchema,
} from "./usagepricesettlementmode.js";
import {
  UsagePriceTargetAccount,
  UsagePriceTargetAccount$inboundSchema,
  UsagePriceTargetAccount$outboundSchema,
} from "./usagepricetargetaccount.js";
import {
  UsagePriceTrialUsageMode,
  UsagePriceTrialUsageMode$inboundSchema,
  UsagePriceTrialUsageMode$outboundSchema,
} from "./usagepricetrialusagemode.js";

export type UsagePriceEntity = {
  /**
   * Unique identifier of the usage price.
   */
  id: string;
  /**
   * The meter this charge bills.
   */
  meterId: string;
  /**
   * Tax-exclusive price per SINGLE meter unit, in minor units of the product currency. "$20 per 1,000,000 tokens" is 0.002 (2000 cents / 1,000,000). Fractional values are allowed.
   */
  unitPrice: number;
  /**
   * Meter units free per billing period, per customer, before the charge applies.
   */
  freeAllowance: number;
  /**
   * Optional ceiling on the charge per billing period, in minor units. Null means uncapped.
   */
  cap?: number | null | undefined;
  /**
   * How the charge settles: `prepaid` debits the customer credit account as usage aggregates; `postpaid` bills at renewal where the store supports it.
   */
  settlementMode: UsagePriceSettlementMode;
  /**
   * Credit bucket a prepaid charge debits: `shared` (the customer default wallet) or `per_unit` (a bucket named after the meter unit label, or `target_account_name`). Defaults to `shared`.
   */
  targetAccount: UsagePriceTargetAccount;
  /**
   * The per-unit bucket this charge debits: the name given on write, or the meter unit label when none was. Null for a `shared` charge.
   */
  targetAccountName?: string | null | undefined;
  /**
   * Usage metered during a free trial: `free` is not charged, `accrue` is charged when the trial converts. Defaults to `free`.
   */
  trialUsageMode: UsagePriceTrialUsageMode;
};

/** @internal */
export const UsagePriceEntity$inboundSchema: z.ZodType<
  UsagePriceEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  meter_id: z.string(),
  unit_price: z.number(),
  free_allowance: z.number().int(),
  cap: z.nullable(z.number().int()).optional(),
  settlement_mode: UsagePriceSettlementMode$inboundSchema,
  target_account: UsagePriceTargetAccount$inboundSchema,
  target_account_name: z.nullable(z.string()).optional(),
  trial_usage_mode: UsagePriceTrialUsageMode$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "meter_id": "meterId",
    "unit_price": "unitPrice",
    "free_allowance": "freeAllowance",
    "settlement_mode": "settlementMode",
    "target_account": "targetAccount",
    "target_account_name": "targetAccountName",
    "trial_usage_mode": "trialUsageMode",
  });
});
/** @internal */
export type UsagePriceEntity$Outbound = {
  id: string;
  meter_id: string;
  unit_price: number;
  free_allowance: number;
  cap?: number | null | undefined;
  settlement_mode: string;
  target_account: string;
  target_account_name?: string | null | undefined;
  trial_usage_mode: string;
};

/** @internal */
export const UsagePriceEntity$outboundSchema: z.ZodType<
  UsagePriceEntity$Outbound,
  z.ZodTypeDef,
  UsagePriceEntity
> = z.object({
  id: z.string(),
  meterId: z.string(),
  unitPrice: z.number(),
  freeAllowance: z.number().int(),
  cap: z.nullable(z.number().int()).optional(),
  settlementMode: UsagePriceSettlementMode$outboundSchema,
  targetAccount: UsagePriceTargetAccount$outboundSchema,
  targetAccountName: z.nullable(z.string()).optional(),
  trialUsageMode: UsagePriceTrialUsageMode$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    meterId: "meter_id",
    unitPrice: "unit_price",
    freeAllowance: "free_allowance",
    settlementMode: "settlement_mode",
    targetAccount: "target_account",
    targetAccountName: "target_account_name",
    trialUsageMode: "trial_usage_mode",
  });
});

export function usagePriceEntityToJSON(
  usagePriceEntity: UsagePriceEntity,
): string {
  return JSON.stringify(
    UsagePriceEntity$outboundSchema.parse(usagePriceEntity),
  );
}
export function usagePriceEntityFromJSON(
  jsonString: string,
): SafeParseResult<UsagePriceEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsagePriceEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsagePriceEntity' from JSON`,
  );
}
