/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UsagePriceSettlementMode,
  UsagePriceSettlementMode$inboundSchema,
  UsagePriceSettlementMode$outboundSchema,
} from "./usagepricesettlementmode.js";
import {
  UsagePriceTargetAccount,
  UsagePriceTargetAccount$inboundSchema,
  UsagePriceTargetAccount$outboundSchema,
} from "./usagepricetargetaccount.js";
import {
  UsagePriceTrialUsageMode,
  UsagePriceTrialUsageMode$inboundSchema,
  UsagePriceTrialUsageMode$outboundSchema,
} from "./usagepricetrialusagemode.js";

export type UsagePriceRequestEntity = {
  /**
   * Identifier of an existing usage price to edit in place (update only). Omit to add a new charge.
   */
  id?: string | undefined;
  /**
   * The meter this charge bills. Must belong to the same store. One charge per meter per product.
   */
  meterId: string;
  /**
   * Tax-exclusive price per SINGLE meter unit, in minor units of the product currency. "$20 per 1,000,000 tokens" is 0.002 (2000 cents / 1,000,000), not 20. Fractional values are allowed.
   */
  unitPrice: number;
  /**
   * Meter units free per billing period, per customer, before the charge applies. Defaults to 0.
   */
  freeAllowance?: number | undefined;
  /**
   * Optional ceiling on the charge per billing period, in minor units.
   */
  cap?: number | null | undefined;
  /**
   * How the charge settles: `prepaid` debits the customer credit account as usage aggregates; `postpaid` bills at renewal where the store supports it.
   */
  settlementMode: UsagePriceSettlementMode;
  /**
   * Credit bucket a prepaid charge debits: `shared` (the customer default wallet) or `per_unit` (a bucket named after the meter unit label, or `target_account_name`). Defaults to `shared`.
   */
  targetAccount?: UsagePriceTargetAccount | undefined;
  /**
   * Explicit name for the per-unit bucket. Only meaningful with `target_account: per_unit`; defaults to the meter unit label.
   */
  targetAccountName?: string | null | undefined;
  /**
   * Usage metered during a free trial: `free` is not charged, `accrue` is charged when the trial converts. Defaults to `free`.
   */
  trialUsageMode?: UsagePriceTrialUsageMode | undefined;
};

/** @internal */
export const UsagePriceRequestEntity$inboundSchema: z.ZodType<
  UsagePriceRequestEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  meter_id: z.string(),
  unit_price: z.number(),
  free_allowance: z.number().int().optional(),
  cap: z.nullable(z.number().int()).optional(),
  settlement_mode: UsagePriceSettlementMode$inboundSchema,
  target_account: UsagePriceTargetAccount$inboundSchema.optional(),
  target_account_name: z.nullable(z.string()).optional(),
  trial_usage_mode: UsagePriceTrialUsageMode$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "meter_id": "meterId",
    "unit_price": "unitPrice",
    "free_allowance": "freeAllowance",
    "settlement_mode": "settlementMode",
    "target_account": "targetAccount",
    "target_account_name": "targetAccountName",
    "trial_usage_mode": "trialUsageMode",
  });
});
/** @internal */
export type UsagePriceRequestEntity$Outbound = {
  id?: string | undefined;
  meter_id: string;
  unit_price: number;
  free_allowance?: number | undefined;
  cap?: number | null | undefined;
  settlement_mode: string;
  target_account?: string | undefined;
  target_account_name?: string | null | undefined;
  trial_usage_mode?: string | undefined;
};

/** @internal */
export const UsagePriceRequestEntity$outboundSchema: z.ZodType<
  UsagePriceRequestEntity$Outbound,
  z.ZodTypeDef,
  UsagePriceRequestEntity
> = z.object({
  id: z.string().optional(),
  meterId: z.string(),
  unitPrice: z.number(),
  freeAllowance: z.number().int().optional(),
  cap: z.nullable(z.number().int()).optional(),
  settlementMode: UsagePriceSettlementMode$outboundSchema,
  targetAccount: UsagePriceTargetAccount$outboundSchema.optional(),
  targetAccountName: z.nullable(z.string()).optional(),
  trialUsageMode: UsagePriceTrialUsageMode$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    meterId: "meter_id",
    unitPrice: "unit_price",
    freeAllowance: "free_allowance",
    settlementMode: "settlement_mode",
    targetAccount: "target_account",
    targetAccountName: "target_account_name",
    trialUsageMode: "trial_usage_mode",
  });
});

export function usagePriceRequestEntityToJSON(
  usagePriceRequestEntity: UsagePriceRequestEntity,
): string {
  return JSON.stringify(
    UsagePriceRequestEntity$outboundSchema.parse(usagePriceRequestEntity),
  );
}
export function usagePriceRequestEntityFromJSON(
  jsonString: string,
): SafeParseResult<UsagePriceRequestEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsagePriceRequestEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsagePriceRequestEntity' from JSON`,
  );
}
