/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  UsageEventApiResponseDto,
  UsageEventApiResponseDto$inboundSchema,
  UsageEventApiResponseDto$Outbound,
  UsageEventApiResponseDto$outboundSchema,
} from "./usageeventapiresponsedto.js";

export type UsageEventListApiResponseDto = {
  /**
   * Object type
   */
  object: string;
  /**
   * Array of usage events
   */
  data: Array<UsageEventApiResponseDto>;
  /**
   * Whether more items exist beyond this page
   */
  hasMore: boolean;
};

/** @internal */
export const UsageEventListApiResponseDto$inboundSchema: z.ZodType<
  UsageEventListApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string(),
  data: z.array(UsageEventApiResponseDto$inboundSchema),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});
/** @internal */
export type UsageEventListApiResponseDto$Outbound = {
  object: string;
  data: Array<UsageEventApiResponseDto$Outbound>;
  has_more: boolean;
};

/** @internal */
export const UsageEventListApiResponseDto$outboundSchema: z.ZodType<
  UsageEventListApiResponseDto$Outbound,
  z.ZodTypeDef,
  UsageEventListApiResponseDto
> = z.object({
  object: z.string(),
  data: z.array(UsageEventApiResponseDto$outboundSchema),
  hasMore: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    hasMore: "has_more",
  });
});

export function usageEventListApiResponseDtoToJSON(
  usageEventListApiResponseDto: UsageEventListApiResponseDto,
): string {
  return JSON.stringify(
    UsageEventListApiResponseDto$outboundSchema.parse(
      usageEventListApiResponseDto,
    ),
  );
}
export function usageEventListApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<UsageEventListApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageEventListApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageEventListApiResponseDto' from JSON`,
  );
}
