/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Usage metered during a free trial: `free` is not charged, `accrue` is charged when the trial converts. Defaults to `free`.
 */
export const UsagePriceTrialUsageMode = {
  Free: "free",
  Accrue: "accrue",
} as const;
/**
 * Usage metered during a free trial: `free` is not charged, `accrue` is charged when the trial converts. Defaults to `free`.
 */
export type UsagePriceTrialUsageMode = ClosedEnum<
  typeof UsagePriceTrialUsageMode
>;

/** @internal */
export const UsagePriceTrialUsageMode$inboundSchema: z.ZodNativeEnum<
  typeof UsagePriceTrialUsageMode
> = z.nativeEnum(UsagePriceTrialUsageMode);
/** @internal */
export const UsagePriceTrialUsageMode$outboundSchema: z.ZodNativeEnum<
  typeof UsagePriceTrialUsageMode
> = UsagePriceTrialUsageMode$inboundSchema;
