/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Top-level structured fields carried by the event
 */
export type UsageEventApiResponseDtoProperties = {};

/**
 * Free-form metadata; keys are addressable by meter filters
 */
export type UsageEventApiResponseDtoMetadata = {};

export type UsageEventApiResponseDto = {
  /**
   * Usage event ID
   */
  id: string;
  /**
   * Customer ID
   */
  customerId: string;
  /**
   * Your idempotency key for this event
   */
  eventId: string;
  /**
   * Event name
   */
  name: string;
  /**
   * Top-level structured fields carried by the event
   */
  properties: UsageEventApiResponseDtoProperties;
  /**
   * Free-form metadata; keys are addressable by meter filters
   */
  metadata: UsageEventApiResponseDtoMetadata;
  /**
   * When the usage occurred, on your clock (ISO 8601)
   */
  timestamp: string;
  /**
   * When the event was ingested (ISO 8601)
   */
  createdAt: string;
};

/** @internal */
export const UsageEventApiResponseDtoProperties$inboundSchema: z.ZodType<
  UsageEventApiResponseDtoProperties,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type UsageEventApiResponseDtoProperties$Outbound = {};

/** @internal */
export const UsageEventApiResponseDtoProperties$outboundSchema: z.ZodType<
  UsageEventApiResponseDtoProperties$Outbound,
  z.ZodTypeDef,
  UsageEventApiResponseDtoProperties
> = z.object({});

export function usageEventApiResponseDtoPropertiesToJSON(
  usageEventApiResponseDtoProperties: UsageEventApiResponseDtoProperties,
): string {
  return JSON.stringify(
    UsageEventApiResponseDtoProperties$outboundSchema.parse(
      usageEventApiResponseDtoProperties,
    ),
  );
}
export function usageEventApiResponseDtoPropertiesFromJSON(
  jsonString: string,
): SafeParseResult<UsageEventApiResponseDtoProperties, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UsageEventApiResponseDtoProperties$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageEventApiResponseDtoProperties' from JSON`,
  );
}

/** @internal */
export const UsageEventApiResponseDtoMetadata$inboundSchema: z.ZodType<
  UsageEventApiResponseDtoMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type UsageEventApiResponseDtoMetadata$Outbound = {};

/** @internal */
export const UsageEventApiResponseDtoMetadata$outboundSchema: z.ZodType<
  UsageEventApiResponseDtoMetadata$Outbound,
  z.ZodTypeDef,
  UsageEventApiResponseDtoMetadata
> = z.object({});

export function usageEventApiResponseDtoMetadataToJSON(
  usageEventApiResponseDtoMetadata: UsageEventApiResponseDtoMetadata,
): string {
  return JSON.stringify(
    UsageEventApiResponseDtoMetadata$outboundSchema.parse(
      usageEventApiResponseDtoMetadata,
    ),
  );
}
export function usageEventApiResponseDtoMetadataFromJSON(
  jsonString: string,
): SafeParseResult<UsageEventApiResponseDtoMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageEventApiResponseDtoMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageEventApiResponseDtoMetadata' from JSON`,
  );
}

/** @internal */
export const UsageEventApiResponseDto$inboundSchema: z.ZodType<
  UsageEventApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customer_id: z.string(),
  event_id: z.string(),
  name: z.string(),
  properties: z.lazy(() => UsageEventApiResponseDtoProperties$inboundSchema),
  metadata: z.lazy(() => UsageEventApiResponseDtoMetadata$inboundSchema),
  timestamp: z.string(),
  created_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "event_id": "eventId",
    "created_at": "createdAt",
  });
});
/** @internal */
export type UsageEventApiResponseDto$Outbound = {
  id: string;
  customer_id: string;
  event_id: string;
  name: string;
  properties: UsageEventApiResponseDtoProperties$Outbound;
  metadata: UsageEventApiResponseDtoMetadata$Outbound;
  timestamp: string;
  created_at: string;
};

/** @internal */
export const UsageEventApiResponseDto$outboundSchema: z.ZodType<
  UsageEventApiResponseDto$Outbound,
  z.ZodTypeDef,
  UsageEventApiResponseDto
> = z.object({
  id: z.string(),
  customerId: z.string(),
  eventId: z.string(),
  name: z.string(),
  properties: z.lazy(() => UsageEventApiResponseDtoProperties$outboundSchema),
  metadata: z.lazy(() => UsageEventApiResponseDtoMetadata$outboundSchema),
  timestamp: z.string(),
  createdAt: z.string(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    eventId: "event_id",
    createdAt: "created_at",
  });
});

export function usageEventApiResponseDtoToJSON(
  usageEventApiResponseDto: UsageEventApiResponseDto,
): string {
  return JSON.stringify(
    UsageEventApiResponseDto$outboundSchema.parse(usageEventApiResponseDto),
  );
}
export function usageEventApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<UsageEventApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageEventApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageEventApiResponseDto' from JSON`,
  );
}
