/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Credit bucket a prepaid charge debits: `shared` (the customer default wallet) or `per_unit` (a bucket named after the meter unit label, or `target_account_name`). Defaults to `shared`.
 */
export const UsagePriceTargetAccount = {
  Shared: "shared",
  PerUnit: "per_unit",
} as const;
/**
 * Credit bucket a prepaid charge debits: `shared` (the customer default wallet) or `per_unit` (a bucket named after the meter unit label, or `target_account_name`). Defaults to `shared`.
 */
export type UsagePriceTargetAccount = ClosedEnum<
  typeof UsagePriceTargetAccount
>;

/** @internal */
export const UsagePriceTargetAccount$inboundSchema: z.ZodNativeEnum<
  typeof UsagePriceTargetAccount
> = z.nativeEnum(UsagePriceTargetAccount);
/** @internal */
export const UsagePriceTargetAccount$outboundSchema: z.ZodNativeEnum<
  typeof UsagePriceTargetAccount
> = UsagePriceTargetAccount$inboundSchema;
