/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Error category
 */
export const UsageMeteringErrorDetailApiDtoType = {
  InvalidRequestError: "invalid_request_error",
  ApiError: "api_error",
  AuthenticationError: "authentication_error",
  RateLimitError: "rate_limit_error",
} as const;
/**
 * Error category
 */
export type UsageMeteringErrorDetailApiDtoType = ClosedEnum<
  typeof UsageMeteringErrorDetailApiDtoType
>;

/**
 * Structured, machine-readable context for errors that support an action, omitted entirely when there is none. Currently emitted for `meter_name_taken` when the colliding name is held by an ARCHIVED meter: `archived_holder` is true and `archived_holder_id` is that meter, which can be restored via POST /v1/meters/{id}/unarchive. Additive — treat unknown keys as ignorable.
 */
export type Details = {};

export type UsageMeteringErrorDetailApiDto = {
  /**
   * Error category
   */
  type: UsageMeteringErrorDetailApiDtoType;
  /**
   * Machine-readable error code
   */
  code: string | null;
  /**
   * Human-readable error message
   */
  message: string;
  /**
   * The parameter related to the error, if applicable
   */
  param?: string | null | undefined;
  /**
   * Structured, machine-readable context for errors that support an action, omitted entirely when there is none. Currently emitted for `meter_name_taken` when the colliding name is held by an ARCHIVED meter: `archived_holder` is true and `archived_holder_id` is that meter, which can be restored via POST /v1/meters/{id}/unarchive. Additive — treat unknown keys as ignorable.
   */
  details?: Details | undefined;
  /**
   * Unique request identifier for support
   */
  requestId: string;
};

/** @internal */
export const UsageMeteringErrorDetailApiDtoType$inboundSchema: z.ZodNativeEnum<
  typeof UsageMeteringErrorDetailApiDtoType
> = z.nativeEnum(UsageMeteringErrorDetailApiDtoType);
/** @internal */
export const UsageMeteringErrorDetailApiDtoType$outboundSchema: z.ZodNativeEnum<
  typeof UsageMeteringErrorDetailApiDtoType
> = UsageMeteringErrorDetailApiDtoType$inboundSchema;

/** @internal */
export const Details$inboundSchema: z.ZodType<Details, z.ZodTypeDef, unknown> =
  z.object({});
/** @internal */
export type Details$Outbound = {};

/** @internal */
export const Details$outboundSchema: z.ZodType<
  Details$Outbound,
  z.ZodTypeDef,
  Details
> = z.object({});

export function detailsToJSON(details: Details): string {
  return JSON.stringify(Details$outboundSchema.parse(details));
}
export function detailsFromJSON(
  jsonString: string,
): SafeParseResult<Details, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Details$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Details' from JSON`,
  );
}

/** @internal */
export const UsageMeteringErrorDetailApiDto$inboundSchema: z.ZodType<
  UsageMeteringErrorDetailApiDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: UsageMeteringErrorDetailApiDtoType$inboundSchema,
  code: z.nullable(z.string()),
  message: z.string(),
  param: z.nullable(z.string()).optional(),
  details: z.lazy(() => Details$inboundSchema).optional(),
  request_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});
/** @internal */
export type UsageMeteringErrorDetailApiDto$Outbound = {
  type: string;
  code: string | null;
  message: string;
  param?: string | null | undefined;
  details?: Details$Outbound | undefined;
  request_id: string;
};

/** @internal */
export const UsageMeteringErrorDetailApiDto$outboundSchema: z.ZodType<
  UsageMeteringErrorDetailApiDto$Outbound,
  z.ZodTypeDef,
  UsageMeteringErrorDetailApiDto
> = z.object({
  type: UsageMeteringErrorDetailApiDtoType$outboundSchema,
  code: z.nullable(z.string()),
  message: z.string(),
  param: z.nullable(z.string()).optional(),
  details: z.lazy(() => Details$outboundSchema).optional(),
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

export function usageMeteringErrorDetailApiDtoToJSON(
  usageMeteringErrorDetailApiDto: UsageMeteringErrorDetailApiDto,
): string {
  return JSON.stringify(
    UsageMeteringErrorDetailApiDto$outboundSchema.parse(
      usageMeteringErrorDetailApiDto,
    ),
  );
}
export function usageMeteringErrorDetailApiDtoFromJSON(
  jsonString: string,
): SafeParseResult<UsageMeteringErrorDetailApiDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageMeteringErrorDetailApiDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageMeteringErrorDetailApiDto' from JSON`,
  );
}
