/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UsageEventApiResponseDto = {
  /**
   * Usage event ID
   */
  id: string;
  /**
   * Customer ID
   */
  customerId: string;
  /**
   * Your idempotency key for this event
   */
  eventId: string;
  /**
   * Event name
   */
  name: string;
  /**
   * The event's attributes — meter filters and aggregation read their keys here
   */
  properties: { [k: string]: any };
  /**
   * When the usage occurred, on your clock (ISO 8601)
   */
  timestamp: string;
  /**
   * When the event was ingested (ISO 8601)
   */
  createdAt: string;
  /**
   * Ids of the ACTIVE meters that consume this event name, computed at read time (an archived or later-created meter changes this answer — it is not stored with the event). An empty array means the event is not feeding any aggregation right now.
   */
  matchedMeters: Array<string>;
};

/** @internal */
export const UsageEventApiResponseDto$inboundSchema: z.ZodType<
  UsageEventApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customer_id: z.string(),
  event_id: z.string(),
  name: z.string(),
  properties: z.record(z.any()),
  timestamp: z.string(),
  created_at: z.string(),
  matched_meters: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
    "event_id": "eventId",
    "created_at": "createdAt",
    "matched_meters": "matchedMeters",
  });
});
/** @internal */
export type UsageEventApiResponseDto$Outbound = {
  id: string;
  customer_id: string;
  event_id: string;
  name: string;
  properties: { [k: string]: any };
  timestamp: string;
  created_at: string;
  matched_meters: Array<string>;
};

/** @internal */
export const UsageEventApiResponseDto$outboundSchema: z.ZodType<
  UsageEventApiResponseDto$Outbound,
  z.ZodTypeDef,
  UsageEventApiResponseDto
> = z.object({
  id: z.string(),
  customerId: z.string(),
  eventId: z.string(),
  name: z.string(),
  properties: z.record(z.any()),
  timestamp: z.string(),
  createdAt: z.string(),
  matchedMeters: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
    eventId: "event_id",
    createdAt: "created_at",
    matchedMeters: "matched_meters",
  });
});

export function usageEventApiResponseDtoToJSON(
  usageEventApiResponseDto: UsageEventApiResponseDto,
): string {
  return JSON.stringify(
    UsageEventApiResponseDto$outboundSchema.parse(usageEventApiResponseDto),
  );
}
export function usageEventApiResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<UsageEventApiResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsageEventApiResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsageEventApiResponseDto' from JSON`,
  );
}
