/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
  WebhookEventType$outboundSchema,
} from "./webhookeventtype.js";

export type WebhookPendingEventEntity = {
  /**
   * The event ID. Acknowledge the delivery with this ID.
   */
  id: string;
  /**
   * A string representing the object’s type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * The event type carried in the delivery.
   */
  eventType: WebhookEventType;
  /**
   * When the event was recorded for this endpoint.
   */
  createdAt: Date;
  /**
   * The exact JSON request body of the delivery. Forward it byte-for-byte; the signature header is computed over this string.
   */
  body: string;
  /**
   * The HTTP headers a real delivery would carry, including `creem-signature`. Send them unchanged with `body`.
   */
  headers: { [k: string]: string };
};

/** @internal */
export const WebhookPendingEventEntity$inboundSchema: z.ZodType<
  WebhookPendingEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: z.string(),
  event_type: WebhookEventType$inboundSchema,
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  body: z.string(),
  headers: z.record(z.string()),
}).transform((v) => {
  return remap$(v, {
    "event_type": "eventType",
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookPendingEventEntity$Outbound = {
  id: string;
  object: string;
  event_type: string;
  created_at: string;
  body: string;
  headers: { [k: string]: string };
};

/** @internal */
export const WebhookPendingEventEntity$outboundSchema: z.ZodType<
  WebhookPendingEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookPendingEventEntity
> = z.object({
  id: z.string(),
  object: z.string(),
  eventType: WebhookEventType$outboundSchema,
  createdAt: z.date().transform(v => v.toISOString()),
  body: z.string(),
  headers: z.record(z.string()),
}).transform((v) => {
  return remap$(v, {
    eventType: "event_type",
    createdAt: "created_at",
  });
});

export function webhookPendingEventEntityToJSON(
  webhookPendingEventEntity: WebhookPendingEventEntity,
): string {
  return JSON.stringify(
    WebhookPendingEventEntity$outboundSchema.parse(webhookPendingEventEntity),
  );
}
export function webhookPendingEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookPendingEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookPendingEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookPendingEventEntity' from JSON`,
  );
}
