/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomerCreditsAutoRechargeEntity,
  CustomerCreditsAutoRechargeEntity$inboundSchema,
  CustomerCreditsAutoRechargeEntity$Outbound,
  CustomerCreditsAutoRechargeEntity$outboundSchema,
} from "./customercreditsautorechargeentity.js";

/**
 * The event name.
 */
export const WebhookCreditsAutoRechargedEventEntityEventType = {
  CreditsAutoRecharged: "credits.auto_recharged",
} as const;
/**
 * The event name.
 */
export type WebhookCreditsAutoRechargedEventEntityEventType = ClosedEnum<
  typeof WebhookCreditsAutoRechargedEventEntityEventType
>;

export type WebhookCreditsAutoRechargedEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookCreditsAutoRechargedEventEntityEventType;
  /**
   * Timestamp of when the event was created.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: CustomerCreditsAutoRechargeEntity;
};

/** @internal */
export const WebhookCreditsAutoRechargedEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookCreditsAutoRechargedEventEntityEventType> = z
    .nativeEnum(WebhookCreditsAutoRechargedEventEntityEventType);
/** @internal */
export const WebhookCreditsAutoRechargedEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookCreditsAutoRechargedEventEntityEventType> =
    WebhookCreditsAutoRechargedEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookCreditsAutoRechargedEventEntity$inboundSchema: z.ZodType<
  WebhookCreditsAutoRechargedEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookCreditsAutoRechargedEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: CustomerCreditsAutoRechargeEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookCreditsAutoRechargedEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: CustomerCreditsAutoRechargeEntity$Outbound;
};

/** @internal */
export const WebhookCreditsAutoRechargedEventEntity$outboundSchema: z.ZodType<
  WebhookCreditsAutoRechargedEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookCreditsAutoRechargedEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookCreditsAutoRechargedEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: CustomerCreditsAutoRechargeEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookCreditsAutoRechargedEventEntityToJSON(
  webhookCreditsAutoRechargedEventEntity:
    WebhookCreditsAutoRechargedEventEntity,
): string {
  return JSON.stringify(
    WebhookCreditsAutoRechargedEventEntity$outboundSchema.parse(
      webhookCreditsAutoRechargedEventEntity,
    ),
  );
}
export function webhookCreditsAutoRechargedEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookCreditsAutoRechargedEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookCreditsAutoRechargedEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookCreditsAutoRechargedEventEntity' from JSON`,
  );
}
