/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  EnvironmentMode,
  EnvironmentMode$inboundSchema,
  EnvironmentMode$outboundSchema,
} from "./environmentmode.js";
import {
  WebhookDeliveryMode,
  WebhookDeliveryMode$inboundSchema,
  WebhookDeliveryMode$outboundSchema,
} from "./webhookdeliverymode.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
  WebhookEventType$outboundSchema,
} from "./webhookeventtype.js";
import {
  WebhookStatus,
  WebhookStatus$inboundSchema,
  WebhookStatus$outboundSchema,
} from "./webhookstatus.js";

export type WebhookEntity = {
  /**
   * Unique identifier for the object.
   */
  id: string;
  /**
   * String representing the environment.
   */
  mode: EnvironmentMode;
  /**
   * A string representing the object’s type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * The store this webhook endpoint belongs to.
   */
  storeId: string;
  /**
   * A human-readable label for the endpoint.
   */
  name: string | null;
  /**
   * The HTTPS URL Creem delivers events to. For `cli` endpoints this is a placeholder that is never called.
   */
  url: string;
  /**
   * How events reach this endpoint: `http` deliveries are POSTed to `url`; `cli` deliveries wait in the pending-events feed for a local `creem listen` session.
   */
  deliveryMode: WebhookDeliveryMode;
  /**
   * Whether the endpoint receives deliveries. Disabled endpoints keep their configuration but receive nothing.
   */
  status: WebhookStatus;
  events: Array<WebhookEventType>;
  /**
   * The signing secret used to verify delivery signatures. Only returned when the endpoint is created; retrieve it later via the secret endpoint.
   */
  secret?: string | undefined;
};

/** @internal */
export const WebhookEntity$inboundSchema: z.ZodType<
  WebhookEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$inboundSchema,
  object: z.string(),
  store_id: z.string(),
  name: z.nullable(z.string()),
  url: z.string(),
  delivery_mode: WebhookDeliveryMode$inboundSchema,
  status: WebhookStatus$inboundSchema,
  events: z.array(WebhookEventType$inboundSchema),
  secret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "store_id": "storeId",
    "delivery_mode": "deliveryMode",
  });
});
/** @internal */
export type WebhookEntity$Outbound = {
  id: string;
  mode: string;
  object: string;
  store_id: string;
  name: string | null;
  url: string;
  delivery_mode: string;
  status: string;
  events: Array<string>;
  secret?: string | undefined;
};

/** @internal */
export const WebhookEntity$outboundSchema: z.ZodType<
  WebhookEntity$Outbound,
  z.ZodTypeDef,
  WebhookEntity
> = z.object({
  id: z.string(),
  mode: EnvironmentMode$outboundSchema,
  object: z.string(),
  storeId: z.string(),
  name: z.nullable(z.string()),
  url: z.string(),
  deliveryMode: WebhookDeliveryMode$outboundSchema,
  status: WebhookStatus$outboundSchema,
  events: z.array(WebhookEventType$outboundSchema),
  secret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    storeId: "store_id",
    deliveryMode: "delivery_mode",
  });
});

export function webhookEntityToJSON(webhookEntity: WebhookEntity): string {
  return JSON.stringify(WebhookEntity$outboundSchema.parse(webhookEntity));
}
export function webhookEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEntity' from JSON`,
  );
}
