/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WebhookPendingEventEntity,
  WebhookPendingEventEntity$inboundSchema,
  WebhookPendingEventEntity$Outbound,
  WebhookPendingEventEntity$outboundSchema,
} from "./webhookpendingevententity.js";

export type WebhookPendingEventListEntity = {
  /**
   * Pending events, oldest first.
   */
  items: Array<WebhookPendingEventEntity>;
};

/** @internal */
export const WebhookPendingEventListEntity$inboundSchema: z.ZodType<
  WebhookPendingEventListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(WebhookPendingEventEntity$inboundSchema),
});
/** @internal */
export type WebhookPendingEventListEntity$Outbound = {
  items: Array<WebhookPendingEventEntity$Outbound>;
};

/** @internal */
export const WebhookPendingEventListEntity$outboundSchema: z.ZodType<
  WebhookPendingEventListEntity$Outbound,
  z.ZodTypeDef,
  WebhookPendingEventListEntity
> = z.object({
  items: z.array(WebhookPendingEventEntity$outboundSchema),
});

export function webhookPendingEventListEntityToJSON(
  webhookPendingEventListEntity: WebhookPendingEventListEntity,
): string {
  return JSON.stringify(
    WebhookPendingEventListEntity$outboundSchema.parse(
      webhookPendingEventListEntity,
    ),
  );
}
export function webhookPendingEventListEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookPendingEventListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookPendingEventListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookPendingEventListEntity' from JSON`,
  );
}
