/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomerCreditsExhaustionEntity,
  CustomerCreditsExhaustionEntity$inboundSchema,
  CustomerCreditsExhaustionEntity$Outbound,
  CustomerCreditsExhaustionEntity$outboundSchema,
} from "./customercreditsexhaustionentity.js";

/**
 * The event name.
 */
export const WebhookCustomerCreditsExhaustedEventEntityEventType = {
  CustomerCreditsExhausted: "customer_credits.exhausted",
} as const;
/**
 * The event name.
 */
export type WebhookCustomerCreditsExhaustedEventEntityEventType = ClosedEnum<
  typeof WebhookCustomerCreditsExhaustedEventEntityEventType
>;

export type WebhookCustomerCreditsExhaustedEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookCustomerCreditsExhaustedEventEntityEventType;
  /**
   * Timestamp of when the event was created.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: CustomerCreditsExhaustionEntity;
};

/** @internal */
export const WebhookCustomerCreditsExhaustedEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookCustomerCreditsExhaustedEventEntityEventType> =
    z.nativeEnum(WebhookCustomerCreditsExhaustedEventEntityEventType);
/** @internal */
export const WebhookCustomerCreditsExhaustedEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookCustomerCreditsExhaustedEventEntityEventType> =
    WebhookCustomerCreditsExhaustedEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookCustomerCreditsExhaustedEventEntity$inboundSchema:
  z.ZodType<WebhookCustomerCreditsExhaustedEventEntity, z.ZodTypeDef, unknown> =
    z.object({
      id: z.string(),
      eventType:
        WebhookCustomerCreditsExhaustedEventEntityEventType$inboundSchema,
      created_at: z.number(),
      object: CustomerCreditsExhaustionEntity$inboundSchema,
    }).transform((v) => {
      return remap$(v, {
        "created_at": "createdAt",
      });
    });
/** @internal */
export type WebhookCustomerCreditsExhaustedEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: CustomerCreditsExhaustionEntity$Outbound;
};

/** @internal */
export const WebhookCustomerCreditsExhaustedEventEntity$outboundSchema:
  z.ZodType<
    WebhookCustomerCreditsExhaustedEventEntity$Outbound,
    z.ZodTypeDef,
    WebhookCustomerCreditsExhaustedEventEntity
  > = z.object({
    id: z.string(),
    eventType:
      WebhookCustomerCreditsExhaustedEventEntityEventType$outboundSchema,
    createdAt: z.number(),
    object: CustomerCreditsExhaustionEntity$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      createdAt: "created_at",
    });
  });

export function webhookCustomerCreditsExhaustedEventEntityToJSON(
  webhookCustomerCreditsExhaustedEventEntity:
    WebhookCustomerCreditsExhaustedEventEntity,
): string {
  return JSON.stringify(
    WebhookCustomerCreditsExhaustedEventEntity$outboundSchema.parse(
      webhookCustomerCreditsExhaustedEventEntity,
    ),
  );
}
export function webhookCustomerCreditsExhaustedEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<
  WebhookCustomerCreditsExhaustedEventEntity,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WebhookCustomerCreditsExhaustedEventEntity$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WebhookCustomerCreditsExhaustedEventEntity' from JSON`,
  );
}
