/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WebhookEventAckEntity = {
  /**
   * The acknowledged event ID.
   */
  id: string;
  /**
   * A string representing the object’s type. Objects of the same type share the same value.
   */
  object: string;
  /**
   * Whether the first acknowledgment recorded a successful delivery (any 2xx). Repeated acknowledgments return the stored result.
   */
  success: boolean;
};

/** @internal */
export const WebhookEventAckEntity$inboundSchema: z.ZodType<
  WebhookEventAckEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  object: z.string(),
  success: z.boolean(),
});
/** @internal */
export type WebhookEventAckEntity$Outbound = {
  id: string;
  object: string;
  success: boolean;
};

/** @internal */
export const WebhookEventAckEntity$outboundSchema: z.ZodType<
  WebhookEventAckEntity$Outbound,
  z.ZodTypeDef,
  WebhookEventAckEntity
> = z.object({
  id: z.string(),
  object: z.string(),
  success: z.boolean(),
});

export function webhookEventAckEntityToJSON(
  webhookEventAckEntity: WebhookEventAckEntity,
): string {
  return JSON.stringify(
    WebhookEventAckEntity$outboundSchema.parse(webhookEventAckEntity),
  );
}
export function webhookEventAckEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookEventAckEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookEventAckEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookEventAckEntity' from JSON`,
  );
}
