/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomerCreditsGrantEntity,
  CustomerCreditsGrantEntity$inboundSchema,
  CustomerCreditsGrantEntity$Outbound,
  CustomerCreditsGrantEntity$outboundSchema,
} from "./customercreditsgrantentity.js";

/**
 * The event name.
 */
export const WebhookCreditsGrantedEventEntityEventType = {
  CreditsGranted: "credits.granted",
} as const;
/**
 * The event name.
 */
export type WebhookCreditsGrantedEventEntityEventType = ClosedEnum<
  typeof WebhookCreditsGrantedEventEntityEventType
>;

export type WebhookCreditsGrantedEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookCreditsGrantedEventEntityEventType;
  /**
   * Timestamp of when the event was created.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: CustomerCreditsGrantEntity;
};

/** @internal */
export const WebhookCreditsGrantedEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookCreditsGrantedEventEntityEventType> = z
    .nativeEnum(WebhookCreditsGrantedEventEntityEventType);
/** @internal */
export const WebhookCreditsGrantedEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookCreditsGrantedEventEntityEventType> =
    WebhookCreditsGrantedEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookCreditsGrantedEventEntity$inboundSchema: z.ZodType<
  WebhookCreditsGrantedEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookCreditsGrantedEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: CustomerCreditsGrantEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookCreditsGrantedEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: CustomerCreditsGrantEntity$Outbound;
};

/** @internal */
export const WebhookCreditsGrantedEventEntity$outboundSchema: z.ZodType<
  WebhookCreditsGrantedEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookCreditsGrantedEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookCreditsGrantedEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: CustomerCreditsGrantEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookCreditsGrantedEventEntityToJSON(
  webhookCreditsGrantedEventEntity: WebhookCreditsGrantedEventEntity,
): string {
  return JSON.stringify(
    WebhookCreditsGrantedEventEntity$outboundSchema.parse(
      webhookCreditsGrantedEventEntity,
    ),
  );
}
export function webhookCreditsGrantedEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookCreditsGrantedEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookCreditsGrantedEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookCreditsGrantedEventEntity' from JSON`,
  );
}
