/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomerCreditsConsumptionEntity,
  CustomerCreditsConsumptionEntity$inboundSchema,
  CustomerCreditsConsumptionEntity$Outbound,
  CustomerCreditsConsumptionEntity$outboundSchema,
} from "./customercreditsconsumptionentity.js";

/**
 * The event name.
 */
export const WebhookCreditsConsumedEventEntityEventType = {
  CreditsConsumed: "credits.consumed",
} as const;
/**
 * The event name.
 */
export type WebhookCreditsConsumedEventEntityEventType = ClosedEnum<
  typeof WebhookCreditsConsumedEventEntityEventType
>;

export type WebhookCreditsConsumedEventEntity = {
  /**
   * Unique identifier for the event.
   */
  id: string;
  /**
   * The event name.
   */
  eventType: WebhookCreditsConsumedEventEntityEventType;
  /**
   * Timestamp of when the event was created.
   */
  createdAt: number;
  /**
   * Object related to the event.
   */
  object: CustomerCreditsConsumptionEntity;
};

/** @internal */
export const WebhookCreditsConsumedEventEntityEventType$inboundSchema:
  z.ZodNativeEnum<typeof WebhookCreditsConsumedEventEntityEventType> = z
    .nativeEnum(WebhookCreditsConsumedEventEntityEventType);
/** @internal */
export const WebhookCreditsConsumedEventEntityEventType$outboundSchema:
  z.ZodNativeEnum<typeof WebhookCreditsConsumedEventEntityEventType> =
    WebhookCreditsConsumedEventEntityEventType$inboundSchema;

/** @internal */
export const WebhookCreditsConsumedEventEntity$inboundSchema: z.ZodType<
  WebhookCreditsConsumedEventEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  eventType: WebhookCreditsConsumedEventEntityEventType$inboundSchema,
  created_at: z.number(),
  object: CustomerCreditsConsumptionEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});
/** @internal */
export type WebhookCreditsConsumedEventEntity$Outbound = {
  id: string;
  eventType: string;
  created_at: number;
  object: CustomerCreditsConsumptionEntity$Outbound;
};

/** @internal */
export const WebhookCreditsConsumedEventEntity$outboundSchema: z.ZodType<
  WebhookCreditsConsumedEventEntity$Outbound,
  z.ZodTypeDef,
  WebhookCreditsConsumedEventEntity
> = z.object({
  id: z.string(),
  eventType: WebhookCreditsConsumedEventEntityEventType$outboundSchema,
  createdAt: z.number(),
  object: CustomerCreditsConsumptionEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function webhookCreditsConsumedEventEntityToJSON(
  webhookCreditsConsumedEventEntity: WebhookCreditsConsumedEventEntity,
): string {
  return JSON.stringify(
    WebhookCreditsConsumedEventEntity$outboundSchema.parse(
      webhookCreditsConsumedEventEntity,
    ),
  );
}
export function webhookCreditsConsumedEventEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookCreditsConsumedEventEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookCreditsConsumedEventEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookCreditsConsumedEventEntity' from JSON`,
  );
}
