/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WebhookSecretEntity = {
  /**
   * The signing secret for this endpoint. Use it to verify the signature header on every delivery.
   */
  secret: string;
};

/** @internal */
export const WebhookSecretEntity$inboundSchema: z.ZodType<
  WebhookSecretEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  secret: z.string(),
});
/** @internal */
export type WebhookSecretEntity$Outbound = {
  secret: string;
};

/** @internal */
export const WebhookSecretEntity$outboundSchema: z.ZodType<
  WebhookSecretEntity$Outbound,
  z.ZodTypeDef,
  WebhookSecretEntity
> = z.object({
  secret: z.string(),
});

export function webhookSecretEntityToJSON(
  webhookSecretEntity: WebhookSecretEntity,
): string {
  return JSON.stringify(
    WebhookSecretEntity$outboundSchema.parse(webhookSecretEntity),
  );
}
export function webhookSecretEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSecretEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookSecretEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSecretEntity' from JSON`,
  );
}
