/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The event type carried in the delivery.
 */
export const WebhookEventType = {
  CheckoutCompleted: "checkout.completed",
  RefundCreated: "refund.created",
  DisputeCreated: "dispute.created",
  SubscriptionActive: "subscription.active",
  SubscriptionTrialing: "subscription.trialing",
  SubscriptionCanceled: "subscription.canceled",
  SubscriptionScheduledCancel: "subscription.scheduled_cancel",
  SubscriptionPaid: "subscription.paid",
  SubscriptionExpired: "subscription.expired",
  SubscriptionUnpaid: "subscription.unpaid",
  SubscriptionUpdate: "subscription.update",
  SubscriptionPastDue: "subscription.past_due",
  SubscriptionPaused: "subscription.paused",
  CustomerCreditsExhausted: "customer_credits.exhausted",
  CreditsGranted: "credits.granted",
  CreditsConsumed: "credits.consumed",
  CreditsAutoRecharged: "credits.auto_recharged",
} as const;
/**
 * The event type carried in the delivery.
 */
export type WebhookEventType = ClosedEnum<typeof WebhookEventType>;

/** @internal */
export const WebhookEventType$inboundSchema: z.ZodNativeEnum<
  typeof WebhookEventType
> = z.nativeEnum(WebhookEventType);
/** @internal */
export const WebhookEventType$outboundSchema: z.ZodNativeEnum<
  typeof WebhookEventType
> = WebhookEventType$inboundSchema;
