/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PaginationEntity,
  PaginationEntity$inboundSchema,
  PaginationEntity$Outbound,
  PaginationEntity$outboundSchema,
} from "./paginationentity.js";
import {
  WebhookEntity,
  WebhookEntity$inboundSchema,
  WebhookEntity$Outbound,
  WebhookEntity$outboundSchema,
} from "./webhookentity.js";

export type WebhookListEntity = {
  /**
   * List of webhook endpoints
   */
  items: Array<WebhookEntity>;
  /**
   * Pagination details for the list
   */
  pagination: PaginationEntity;
};

/** @internal */
export const WebhookListEntity$inboundSchema: z.ZodType<
  WebhookListEntity,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(WebhookEntity$inboundSchema),
  pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export type WebhookListEntity$Outbound = {
  items: Array<WebhookEntity$Outbound>;
  pagination: PaginationEntity$Outbound;
};

/** @internal */
export const WebhookListEntity$outboundSchema: z.ZodType<
  WebhookListEntity$Outbound,
  z.ZodTypeDef,
  WebhookListEntity
> = z.object({
  items: z.array(WebhookEntity$outboundSchema),
  pagination: PaginationEntity$outboundSchema,
});

export function webhookListEntityToJSON(
  webhookListEntity: WebhookListEntity,
): string {
  return JSON.stringify(
    WebhookListEntity$outboundSchema.parse(webhookListEntity),
  );
}
export function webhookListEntityFromJSON(
  jsonString: string,
): SafeParseResult<WebhookListEntity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookListEntity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookListEntity' from JSON`,
  );
}
