/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * How events reach this endpoint: `http` deliveries are POSTed to `url`; `cli` deliveries wait in the pending-events feed for a local `creem listen` session.
 */
export const WebhookDeliveryMode = {
  Http: "http",
  Cli: "cli",
} as const;
/**
 * How events reach this endpoint: `http` deliveries are POSTed to `url`; `cli` deliveries wait in the pending-events feed for a local `creem listen` session.
 */
export type WebhookDeliveryMode = ClosedEnum<typeof WebhookDeliveryMode>;

/** @internal */
export const WebhookDeliveryMode$inboundSchema: z.ZodNativeEnum<
  typeof WebhookDeliveryMode
> = z.nativeEnum(WebhookDeliveryMode);
/** @internal */
export const WebhookDeliveryMode$outboundSchema: z.ZodNativeEnum<
  typeof WebhookDeliveryMode
> = WebhookDeliveryMode$inboundSchema;
