/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Whether the endpoint receives deliveries. Disabled endpoints keep their configuration but receive nothing.
 */
export const WebhookStatus = {
  Enabled: "enabled",
  Disabled: "disabled",
} as const;
/**
 * Whether the endpoint receives deliveries. Disabled endpoints keep their configuration but receive nothing.
 */
export type WebhookStatus = ClosedEnum<typeof WebhookStatus>;

/** @internal */
export const WebhookStatus$inboundSchema: z.ZodNativeEnum<
  typeof WebhookStatus
> = z.nativeEnum(WebhookStatus);
/** @internal */
export const WebhookStatus$outboundSchema: z.ZodNativeEnum<
  typeof WebhookStatus
> = WebhookStatus$inboundSchema;
