/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsAccountsExperimentalCreditCustomerCreditsAccount } from "../../funcs/customerCreditsAccountsExperimentalCreditCustomerCreditsAccount.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  creditDebitRequestDto: components.CreditDebitRequestDto$inboundSchema,
};

export const tool$customerCreditsAccountsExperimentalCreditCustomerCreditsAccount:
  ToolDefinition<typeof args> = {
    name:
      "customer-credits-accounts-(experimental)-credit-customer-credits-account",
    description: `Credit an account

Add credits to a customer account. Returns the resulting transaction record.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await customerCreditsAccountsExperimentalCreditCustomerCreditsAccount(
          client,
          args.id,
          args.creditDebitRequestDto,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
