/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsAccountsExperimentalListCustomerCreditsAccountEntries } from "../../funcs/customerCreditsAccountsExperimentalListCustomerCreditsAccountEntries.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  limit: z.number().default(10),
  startingAfter: z.string().optional(),
  endingBefore: z.string().optional(),
};

export const tool$customerCreditsAccountsExperimentalListCustomerCreditsAccountEntries:
  ToolDefinition<typeof args> = {
    name:
      "customer-credits-accounts-(experimental)-list-customer-credits-account-entries",
    description: `List account entries

List the credit and debit history for an account with cursor pagination.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await customerCreditsAccountsExperimentalListCustomerCreditsAccountEntries(
          client,
          args.id,
          args.limit,
          args.startingAfter,
          args.endingBefore,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
