/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsAccountsExperimentalCloseCustomerCreditsAccount } from "../../funcs/customerCreditsAccountsExperimentalCloseCustomerCreditsAccount.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$customerCreditsAccountsExperimentalCloseCustomerCreditsAccount:
  ToolDefinition<typeof args> = {
    name:
      "customer-credits-accounts-(experimental)-close-customer-credits-account",
    description: `Close an account

Permanently close an account. This action cannot be undone.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await customerCreditsAccountsExperimentalCloseCustomerCreditsAccount(
          client,
          args.id,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
