/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersUpdateCustomer } from "../../funcs/customersUpdateCustomer.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.UpdateCustomerRequestEntity$inboundSchema,
};

export const tool$customersUpdateCustomer: ToolDefinition<typeof args> = {
  name: "customers-update-customer",
  description: `Update a customer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersUpdateCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
