/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreateCustomer } from "../../funcs/customersCreateCustomer.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateCustomerRequestEntity$inboundSchema,
};

export const tool$customersCreateCustomer: ToolDefinition<typeof args> = {
  name: "customers-create-customer",
  description: `Create a customer

Create a new customer record for the authenticated store.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersCreateCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
