/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsAccountsExperimentalListCustomerCreditsAccounts } from "../../funcs/customerCreditsAccountsExperimentalListCustomerCreditsAccounts.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  limit: z.number().default(10),
  customerId: z.string().optional(),
  startingAfter: z.string().optional(),
  endingBefore: z.string().optional(),
};

export const tool$customerCreditsAccountsExperimentalListCustomerCreditsAccounts:
  ToolDefinition<typeof args> = {
    name:
      "customer-credits-accounts-(experimental)-list-customer-credits-accounts",
    description: `List customer credits accounts

List accounts for the authenticated store with cursor pagination. System accounts are excluded.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await customerCreditsAccountsExperimentalListCustomerCreditsAccounts(
          client,
          args.limit,
          args.customerId,
          args.startingAfter,
          args.endingBefore,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
