import { createHash } from 'node:crypto'
import { GenerateInput, GenerateResult, Generator } from './index'

/**
 * Demo sentinel: a prompt containing this marker makes the stub throw *after*
 * the model would have started, so the moderate → debit → generate → REFUND
 * path (reverse the debit when the model fails post-charge) can be exercised
 * deterministically. Harmless in production (this backend is demo-only).
 */
export const FORCE_GENERATION_ERROR_SENTINEL = '#force-generation-error'

/**
 * A deterministic, dependency-free placeholder generator. It renders the prompt
 * into a gradient SVG "poster" so the full moderate -> debit -> generate ->
 * return flow is demonstrable end-to-end without any model credentials or cost.
 *
 * Swap this out for a real provider by implementing the Generator interface and
 * wiring it into getGenerator().
 */
export class StubGenerator implements Generator {
  readonly name = 'stub'

  async generate(input: GenerateInput): Promise<GenerateResult> {
    // Simulate model latency (videos take longer).
    await sleep(input.mediaType === 'video' ? 1200 : 600)

    // Demo affordance: force a post-debit model failure so the refund path runs.
    if (input.prompt.includes(FORCE_GENERATION_ERROR_SENTINEL)) {
      throw new Error('stub: forced generation failure')
    }

    const svg = renderPoster(input)
    const url = `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`
    return {
      url,
      mediaType: input.mediaType,
      meta: { model: 'stub-poster-v1', requestId: input.requestId, options: input.options ?? {} },
    }
  }
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms))
}

function renderPoster(input: GenerateInput): string {
  const hash = createHash('sha256')
    .update(input.prompt + JSON.stringify(input.options ?? {}))
    .digest('hex')
  const h1 = parseInt(hash.slice(0, 6), 16) % 360
  const h2 = (h1 + 40 + (parseInt(hash.slice(6, 10), 16) % 120)) % 360
  const c1 = `hsl(${h1} 70% 55%)`
  const c2 = `hsl(${h2} 70% 40%)`
  const label = input.mediaType === 'video' ? '▶ VIDEO' : 'IMAGE'
  const words = escapeXml(input.prompt).slice(0, 120)

  return `<svg xmlns="http://www.w3.org/2000/svg" width="768" height="768" viewBox="0 0 768 768">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${c1}"/>
      <stop offset="1" stop-color="${c2}"/>
    </linearGradient>
  </defs>
  <rect width="768" height="768" fill="url(#g)"/>
  <circle cx="384" cy="300" r="150" fill="rgba(255,255,255,0.14)"/>
  <text x="40" y="60" font-family="ui-sans-serif,system-ui,sans-serif" font-size="22" fill="rgba(255,255,255,0.85)" font-weight="700" letter-spacing="3">${label}</text>
  <text x="40" y="700" font-family="ui-sans-serif,system-ui,sans-serif" font-size="30" fill="white" font-weight="700">
    <tspan x="40" dy="0">${wrap(words, 34)[0] ?? ''}</tspan>
    <tspan x="40" dy="38">${wrap(words, 34)[1] ?? ''}</tspan>
    <tspan x="40" dy="38">${wrap(words, 34)[2] ?? ''}</tspan>
  </text>
  <text x="40" y="740" font-family="ui-monospace,monospace" font-size="16" fill="rgba(255,255,255,0.6)">generated by stub-poster-v1</text>
</svg>`
}

function wrap(text: string, width: number): string[] {
  const words = text.split(' ')
  const lines: string[] = []
  let line = ''
  for (const w of words) {
    if ((line + ' ' + w).trim().length > width) {
      lines.push(line.trim())
      line = w
    } else {
      line = (line + ' ' + w).trim()
    }
  }
  if (line) lines.push(line.trim())
  return lines
}

function escapeXml(s: string): string {
  return s.replace(/[<>&'"]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', "'": '&apos;', '"': '&quot;' })[c] as string)
}
