/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { affiliatesCreateInvite } from "../funcs/affiliatesCreateInvite.js";
import { affiliatesList } from "../funcs/affiliatesList.js";
import { affiliatesListCommissions } from "../funcs/affiliatesListCommissions.js";
import { affiliatesListInvites } from "../funcs/affiliatesListInvites.js";
import { affiliatesRetrieve } from "../funcs/affiliatesRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Affiliates extends ClientSDK {
  /**
   * Create an affiliate invitation
   *
   * @remarks
   * Invite someone to your affiliate program by email. They receive an invitation email and become an active affiliate once they accept. If `program_id` is omitted, the invitation is created for your store's affiliate program.
   */
  async createInvite(
    request: components.CreateAffiliateInviteRequestEntity,
    options?: RequestOptions,
  ): Promise<components.AffiliateInviteEntity> {
    return unwrapAsync(affiliatesCreateInvite(
      this,
      request,
      options,
    ));
  }

  /**
   * List affiliate invitations
   *
   * @remarks
   * Retrieve a paginated list of the invitations you have sent, with their status (`pending` until accepted, `accepted` once the affiliate has joined).
   */
  async listInvites(
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListAffiliateInvitesResponse, { page: number }>
  > {
    return unwrapResultIterator(affiliatesListInvites(
      this,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * List all affiliates
   *
   * @remarks
   * Retrieve a paginated list of your affiliates with their referral link, click and conversion counts, and lifetime commission. Affiliates who were invited but have not yet joined a program are not included.
   */
  async list(
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListAffiliatesResponse, { page: number }>
  > {
    return unwrapResultIterator(affiliatesList(
      this,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * Retrieve an affiliate
   *
   * @remarks
   * Retrieve a single affiliate by ID, including referral link, click and conversion counts, and lifetime commission.
   */
  async retrieve(
    id: string,
    options?: RequestOptions,
  ): Promise<components.AffiliateEntity> {
    return unwrapAsync(affiliatesRetrieve(
      this,
      id,
      options,
    ));
  }

  /**
   * List affiliate commissions
   *
   * @remarks
   * Retrieve a paginated list of an affiliate’s commissions. Filter by settlement status (pending, approved, paid).
   */
  async listCommissions(
    id: string,
    status?: components.CommissionStatus | undefined,
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListAffiliateCommissionsResponse, { page: number }>
  > {
    return unwrapResultIterator(affiliatesListCommissions(
      this,
      id,
      status,
      pageNumber,
      pageSize,
      options,
    ));
  }
}
