/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metersArchiveMeter } from "../funcs/metersArchiveMeter.js";
import { metersCreateMeter } from "../funcs/metersCreateMeter.js";
import { metersGetConsumedUnits } from "../funcs/metersGetConsumedUnits.js";
import { metersGetMeter } from "../funcs/metersGetMeter.js";
import { metersListMeters } from "../funcs/metersListMeters.js";
import { metersPreviewExistingMeter } from "../funcs/metersPreviewExistingMeter.js";
import { metersPreviewMeter } from "../funcs/metersPreviewMeter.js";
import { metersUnarchiveMeter } from "../funcs/metersUnarchiveMeter.js";
import { metersUpdateMeter } from "../funcs/metersUpdateMeter.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Meters extends ClientSDK {
  /**
   * Create a meter
   *
   * @remarks
   * Define how a stream of usage events is aggregated into billable units. The unit label doubles as the display unit and as the credit bucket the meter settles into. A duplicate name within the store is rejected with 409 meter_name_taken.
   */
  async createMeter(
    request: components.CreateMeterApiRequestDto,
    options?: RequestOptions,
  ): Promise<components.MeterApiResponseDto> {
    return unwrapAsync(metersCreateMeter(
      this,
      request,
      options,
    ));
  }

  /**
   * List meters
   *
   * @remarks
   * List your meters, newest first, as a cursor page. Archived meters are hidden unless include_archived=true.
   */
  async listMeters(
    limit?: number | undefined,
    startingAfter?: string | undefined,
    endingBefore?: string | undefined,
    includeArchived?: boolean | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListMetersResponse, { cursor: string }>> {
    return unwrapResultIterator(metersListMeters(
      this,
      limit,
      startingAfter,
      endingBefore,
      includeArchived,
      options,
    ));
  }

  /**
   * Preview an unsaved meter definition
   *
   * @remarks
   * Dry-run a candidate meter definition against your real usage over the last 7 whole UTC days (today included, future-dated events excluded) WITHOUT creating anything: matched events, aggregated units, distinct customers, and a zero-filled per-day series, oldest first. Useful for checking a definition before committing to it. The scan is capped defensively and runs newest-first, so a very high-volume store gets the most recent slice of the window rather than an unbounded scan — the recent days stay complete and the oldest day of the series degrades.
   */
  async previewMeter(
    request: components.PreviewMeterApiRequestDto,
    options?: RequestOptions,
  ): Promise<components.MeterPreviewApiResponseDto> {
    return unwrapAsync(metersPreviewMeter(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve a meter
   *
   * @remarks
   * Get one meter by ID. Archived meters ARE returned here — a fetch by explicit ID is an intentional lookup.
   */
  async getMeter(
    id: string,
    options?: RequestOptions,
  ): Promise<components.MeterApiResponseDto> {
    return unwrapAsync(metersGetMeter(
      this,
      id,
      options,
    ));
  }

  /**
   * Update a meter
   *
   * @remarks
   * Rename a meter and/or revise its definition. A rename is always allowed — the name is a label no aggregate depends on — but it must stay unique within the store (409 meter_name_taken). Definition changes (filter, aggregation, aggregation_property) are only accepted while the meter has processed no usage and has no associated purchase; otherwise the request is rejected with 409, because editing the definition would silently rewrite what already-recorded usage means. Send aggregation_property as null to clear it; omit it to leave it unchanged.
   */
  async updateMeter(
    id: string,
    updateMeterApiRequestDto: components.UpdateMeterApiRequestDto,
    options?: RequestOptions,
  ): Promise<components.MeterApiResponseDto> {
    return unwrapAsync(metersUpdateMeter(
      this,
      id,
      updateMeterApiRequestDto,
      options,
    ));
  }

  /**
   * Preview an existing meter
   *
   * @remarks
   * Dry-run an existing meter against your real usage over the last 7 whole UTC days (today included, future-dated events excluded). Same shape as the unsaved-definition preview; nothing is written.
   */
  async previewExistingMeter(
    id: string,
    options?: RequestOptions,
  ): Promise<components.MeterPreviewApiResponseDto> {
    return unwrapAsync(metersPreviewExistingMeter(
      this,
      id,
      options,
    ));
  }

  /**
   * Get consumed units for a customer
   *
   * @remarks
   * How many units a customer has consumed through this meter in a billing period, alongside the period's boundaries. Without `at`, this is an O(1) read of the current period's projection — the number billing uses. With `at`, the units are replayed from the raw events as of that instant, within the billing period containing it, which is the right call for reconstructing what a customer had consumed at a past moment (an invoice date, a support question).
   */
  async getConsumedUnits(
    id: string,
    customerId: string,
    at?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.MeterConsumedUnitsApiResponseDto> {
    return unwrapAsync(metersGetConsumedUnits(
      this,
      id,
      customerId,
      at,
      options,
    ));
  }

  /**
   * Archive a meter
   *
   * @remarks
   * Archive a meter: it leaves the default listing and stops accruing new usage, but is never deleted, so the usage it already recorded stays meaningful. Idempotent — archiving an archived meter returns it unchanged.
   */
  async archiveMeter(
    id: string,
    options?: RequestOptions,
  ): Promise<components.MeterApiResponseDto> {
    return unwrapAsync(metersArchiveMeter(
      this,
      id,
      options,
    ));
  }

  /**
   * Unarchive a meter
   *
   * @remarks
   * Restore an archived meter: it returns to the default listing and resumes accruing usage from the next matching event. Idempotent — unarchiving an active meter returns it unchanged. No gate applies and none is needed: archiving never released the meter's name, because per-store name uniqueness counts archived meters (which is why creating a meter with an archived meter's name returns 409 `meter_name_taken` with `details.archived_holder`), and it never altered the definition. Usage ingested while the meter was archived is retained as raw events and IS folded back in for any period still inside the late-event window, since a period is recomputed in full rather than incrementally — so units for an open period can increase by more than the usage seen since the unarchive. Finalized periods are not moved.
   */
  async unarchiveMeter(
    id: string,
    options?: RequestOptions,
  ): Promise<components.MeterApiResponseDto> {
    return unwrapAsync(metersUnarchiveMeter(
      this,
      id,
      options,
    ));
  }
}
