/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { splitsCreate } from "../funcs/splitsCreate.js";
import { splitsDelete } from "../funcs/splitsDelete.js";
import { splitsList } from "../funcs/splitsList.js";
import { splitsRetrieve } from "../funcs/splitsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Splits extends ClientSDK {
  /**
   * Create a split
   *
   * @remarks
   * Create a revenue split for your store. The split applies either to your whole store (`type: store`) or to a single product (`type: product`). Recipients are existing stores (added directly) or email invitees; a split created with any email invitee starts disabled and activates once the first invitee accepts. The split is always created for the store the API key belongs to.
   */
  async create(
    request: components.CreateSplitRequestEntity,
    options?: RequestOptions,
  ): Promise<components.SplitEntity> {
    return unwrapAsync(splitsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List all splits
   *
   * @remarks
   * Retrieve a paginated list of the active splits configured for your store, each with its recipients and their shares. Email invitees who have not yet accepted are shown with a masked email address.
   */
  async list(
    pageNumber?: number | undefined,
    pageSize?: number | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListSplitsResponse, { page: number }>> {
    return unwrapResultIterator(splitsList(
      this,
      pageNumber,
      pageSize,
      options,
    ));
  }

  /**
   * Retrieve a split
   *
   * @remarks
   * Retrieve a single split by ID, including its recipients and their shares. Email invitees who have not yet accepted are shown with a masked email address and their invite status. Splits belonging to another store are not visible.
   */
  async retrieve(
    id: string,
    options?: RequestOptions,
  ): Promise<components.SplitEntity> {
    return unwrapAsync(splitsRetrieve(
      this,
      id,
      options,
    ));
  }

  /**
   * Delete a split
   *
   * @remarks
   * Delete a split by ID. The split stops applying to future payments immediately. Splits belonging to another store cannot be deleted.
   */
  async delete(
    id: string,
    options?: RequestOptions,
  ): Promise<components.SplitEntity> {
    return unwrapAsync(splitsDelete(
      this,
      id,
      options,
    ));
  }
}
