/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AcknowledgeWebhookEventRequest = {
  /**
   * The webhook ID
   */
  id: string;
  /**
   * The event ID from the pending feed
   */
  eventId: string;
  /**
   * The local delivery result
   */
  acknowledgeWebhookEventRequestEntity:
    components.AcknowledgeWebhookEventRequestEntity;
};

/** @internal */
export const AcknowledgeWebhookEventRequest$inboundSchema: z.ZodType<
  AcknowledgeWebhookEventRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  event_id: z.string(),
  AcknowledgeWebhookEventRequestEntity:
    components.AcknowledgeWebhookEventRequestEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "event_id": "eventId",
    "AcknowledgeWebhookEventRequestEntity":
      "acknowledgeWebhookEventRequestEntity",
  });
});
/** @internal */
export type AcknowledgeWebhookEventRequest$Outbound = {
  id: string;
  event_id: string;
  AcknowledgeWebhookEventRequestEntity:
    components.AcknowledgeWebhookEventRequestEntity$Outbound;
};

/** @internal */
export const AcknowledgeWebhookEventRequest$outboundSchema: z.ZodType<
  AcknowledgeWebhookEventRequest$Outbound,
  z.ZodTypeDef,
  AcknowledgeWebhookEventRequest
> = z.object({
  id: z.string(),
  eventId: z.string(),
  acknowledgeWebhookEventRequestEntity:
    components.AcknowledgeWebhookEventRequestEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    eventId: "event_id",
    acknowledgeWebhookEventRequestEntity:
      "AcknowledgeWebhookEventRequestEntity",
  });
});

export function acknowledgeWebhookEventRequestToJSON(
  acknowledgeWebhookEventRequest: AcknowledgeWebhookEventRequest,
): string {
  return JSON.stringify(
    AcknowledgeWebhookEventRequest$outboundSchema.parse(
      acknowledgeWebhookEventRequest,
    ),
  );
}
export function acknowledgeWebhookEventRequestFromJSON(
  jsonString: string,
): SafeParseResult<AcknowledgeWebhookEventRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AcknowledgeWebhookEventRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AcknowledgeWebhookEventRequest' from JSON`,
  );
}
