/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ArchiveMeterRequest = {
  id: string;
};

/** @internal */
export const ArchiveMeterRequest$inboundSchema: z.ZodType<
  ArchiveMeterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type ArchiveMeterRequest$Outbound = {
  id: string;
};

/** @internal */
export const ArchiveMeterRequest$outboundSchema: z.ZodType<
  ArchiveMeterRequest$Outbound,
  z.ZodTypeDef,
  ArchiveMeterRequest
> = z.object({
  id: z.string(),
});

export function archiveMeterRequestToJSON(
  archiveMeterRequest: ArchiveMeterRequest,
): string {
  return JSON.stringify(
    ArchiveMeterRequest$outboundSchema.parse(archiveMeterRequest),
  );
}
export function archiveMeterRequestFromJSON(
  jsonString: string,
): SafeParseResult<ArchiveMeterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ArchiveMeterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ArchiveMeterRequest' from JSON`,
  );
}
