/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteSplitRequest = {
  /**
   * The unique identifier of the split
   */
  id: string;
};

/** @internal */
export const DeleteSplitRequest$inboundSchema: z.ZodType<
  DeleteSplitRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type DeleteSplitRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteSplitRequest$outboundSchema: z.ZodType<
  DeleteSplitRequest$Outbound,
  z.ZodTypeDef,
  DeleteSplitRequest
> = z.object({
  id: z.string(),
});

export function deleteSplitRequestToJSON(
  deleteSplitRequest: DeleteSplitRequest,
): string {
  return JSON.stringify(
    DeleteSplitRequest$outboundSchema.parse(deleteSplitRequest),
  );
}
export function deleteSplitRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSplitRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteSplitRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSplitRequest' from JSON`,
  );
}
