/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCustomerCreditsTransactionRequest = {
  id: string;
};

/** @internal */
export const GetCustomerCreditsTransactionRequest$inboundSchema: z.ZodType<
  GetCustomerCreditsTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetCustomerCreditsTransactionRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomerCreditsTransactionRequest$outboundSchema: z.ZodType<
  GetCustomerCreditsTransactionRequest$Outbound,
  z.ZodTypeDef,
  GetCustomerCreditsTransactionRequest
> = z.object({
  id: z.string(),
});

export function getCustomerCreditsTransactionRequestToJSON(
  getCustomerCreditsTransactionRequest: GetCustomerCreditsTransactionRequest,
): string {
  return JSON.stringify(
    GetCustomerCreditsTransactionRequest$outboundSchema.parse(
      getCustomerCreditsTransactionRequest,
    ),
  );
}
export function getCustomerCreditsTransactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerCreditsTransactionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetCustomerCreditsTransactionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerCreditsTransactionRequest' from JSON`,
  );
}
