/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetMeterRequest = {
  id: string;
};

/** @internal */
export const GetMeterRequest$inboundSchema: z.ZodType<
  GetMeterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetMeterRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetMeterRequest$outboundSchema: z.ZodType<
  GetMeterRequest$Outbound,
  z.ZodTypeDef,
  GetMeterRequest
> = z.object({
  id: z.string(),
});

export function getMeterRequestToJSON(
  getMeterRequest: GetMeterRequest,
): string {
  return JSON.stringify(GetMeterRequest$outboundSchema.parse(getMeterRequest));
}
export function getMeterRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetMeterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMeterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMeterRequest' from JSON`,
  );
}
