/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetMeterConsumedUnitsRequest = {
  id: string;
  /**
   * The customer whose consumption is read
   */
  customerId: string;
  /**
   * ISO 8601 instant. When present, the consumption is replayed from the raw events as of that point in time, within the billing period that contains it. When absent, the current billing period’s projected total is returned.
   */
  at?: string | undefined;
};

/** @internal */
export const GetMeterConsumedUnitsRequest$inboundSchema: z.ZodType<
  GetMeterConsumedUnitsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  customer_id: z.string(),
  at: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "customer_id": "customerId",
  });
});
/** @internal */
export type GetMeterConsumedUnitsRequest$Outbound = {
  id: string;
  customer_id: string;
  at?: string | undefined;
};

/** @internal */
export const GetMeterConsumedUnitsRequest$outboundSchema: z.ZodType<
  GetMeterConsumedUnitsRequest$Outbound,
  z.ZodTypeDef,
  GetMeterConsumedUnitsRequest
> = z.object({
  id: z.string(),
  customerId: z.string(),
  at: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    customerId: "customer_id",
  });
});

export function getMeterConsumedUnitsRequestToJSON(
  getMeterConsumedUnitsRequest: GetMeterConsumedUnitsRequest,
): string {
  return JSON.stringify(
    GetMeterConsumedUnitsRequest$outboundSchema.parse(
      getMeterConsumedUnitsRequest,
    ),
  );
}
export function getMeterConsumedUnitsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetMeterConsumedUnitsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetMeterConsumedUnitsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetMeterConsumedUnitsRequest' from JSON`,
  );
}
