/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetWebhookSecretRequest = {
  /**
   * The webhook ID
   */
  id: string;
};

/** @internal */
export const GetWebhookSecretRequest$inboundSchema: z.ZodType<
  GetWebhookSecretRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type GetWebhookSecretRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetWebhookSecretRequest$outboundSchema: z.ZodType<
  GetWebhookSecretRequest$Outbound,
  z.ZodTypeDef,
  GetWebhookSecretRequest
> = z.object({
  id: z.string(),
});

export function getWebhookSecretRequestToJSON(
  getWebhookSecretRequest: GetWebhookSecretRequest,
): string {
  return JSON.stringify(
    GetWebhookSecretRequest$outboundSchema.parse(getWebhookSecretRequest),
  );
}
export function getWebhookSecretRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookSecretRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookSecretRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookSecretRequest' from JSON`,
  );
}
