/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListCustomerCreditsTransactionsByReferenceRequest = {
  /**
   * Find all transactions matching this reference
   */
  reference: string;
};

/** @internal */
export const ListCustomerCreditsTransactionsByReferenceRequest$inboundSchema:
  z.ZodType<
    ListCustomerCreditsTransactionsByReferenceRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    reference: z.string(),
  });
/** @internal */
export type ListCustomerCreditsTransactionsByReferenceRequest$Outbound = {
  reference: string;
};

/** @internal */
export const ListCustomerCreditsTransactionsByReferenceRequest$outboundSchema:
  z.ZodType<
    ListCustomerCreditsTransactionsByReferenceRequest$Outbound,
    z.ZodTypeDef,
    ListCustomerCreditsTransactionsByReferenceRequest
  > = z.object({
    reference: z.string(),
  });

export function listCustomerCreditsTransactionsByReferenceRequestToJSON(
  listCustomerCreditsTransactionsByReferenceRequest:
    ListCustomerCreditsTransactionsByReferenceRequest,
): string {
  return JSON.stringify(
    ListCustomerCreditsTransactionsByReferenceRequest$outboundSchema.parse(
      listCustomerCreditsTransactionsByReferenceRequest,
    ),
  );
}
export function listCustomerCreditsTransactionsByReferenceRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ListCustomerCreditsTransactionsByReferenceRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ListCustomerCreditsTransactionsByReferenceRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ListCustomerCreditsTransactionsByReferenceRequest' from JSON`,
  );
}
