/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListSplitsRequest = {
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

export type ListSplitsResponse = {
  result: components.SplitListEntity;
};

/** @internal */
export const ListSplitsRequest$inboundSchema: z.ZodType<
  ListSplitsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_number: z.number().default(1),
  page_size: z.number().default(50),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
  });
});
/** @internal */
export type ListSplitsRequest$Outbound = {
  page_number: number;
  page_size: number;
};

/** @internal */
export const ListSplitsRequest$outboundSchema: z.ZodType<
  ListSplitsRequest$Outbound,
  z.ZodTypeDef,
  ListSplitsRequest
> = z.object({
  pageNumber: z.number().default(1),
  pageSize: z.number().default(50),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
  });
});

export function listSplitsRequestToJSON(
  listSplitsRequest: ListSplitsRequest,
): string {
  return JSON.stringify(
    ListSplitsRequest$outboundSchema.parse(listSplitsRequest),
  );
}
export function listSplitsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListSplitsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSplitsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSplitsRequest' from JSON`,
  );
}

/** @internal */
export const ListSplitsResponse$inboundSchema: z.ZodType<
  ListSplitsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.SplitListEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListSplitsResponse$Outbound = {
  Result: components.SplitListEntity$Outbound;
};

/** @internal */
export const ListSplitsResponse$outboundSchema: z.ZodType<
  ListSplitsResponse$Outbound,
  z.ZodTypeDef,
  ListSplitsResponse
> = z.object({
  result: components.SplitListEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listSplitsResponseToJSON(
  listSplitsResponse: ListSplitsResponse,
): string {
  return JSON.stringify(
    ListSplitsResponse$outboundSchema.parse(listSplitsResponse),
  );
}
export function listSplitsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSplitsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSplitsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSplitsResponse' from JSON`,
  );
}
