/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListMetersRequest = {
  /**
   * Maximum number of meters to return
   */
  limit?: number | undefined;
  /**
   * Cursor for forward pagination — meter ID to start after
   */
  startingAfter?: string | undefined;
  /**
   * Cursor for backward pagination — meter ID to end before
   */
  endingBefore?: string | undefined;
  /**
   * Include archived meters in the page. Defaults to false — archived meters are hidden.
   */
  includeArchived?: boolean | undefined;
};

export type ListMetersResponse = {
  result: components.MeterListApiResponseDto;
};

/** @internal */
export const ListMetersRequest$inboundSchema: z.ZodType<
  ListMetersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().default(10),
  starting_after: z.string().optional(),
  ending_before: z.string().optional(),
  include_archived: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "starting_after": "startingAfter",
    "ending_before": "endingBefore",
    "include_archived": "includeArchived",
  });
});
/** @internal */
export type ListMetersRequest$Outbound = {
  limit: number;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
  include_archived: boolean;
};

/** @internal */
export const ListMetersRequest$outboundSchema: z.ZodType<
  ListMetersRequest$Outbound,
  z.ZodTypeDef,
  ListMetersRequest
> = z.object({
  limit: z.number().default(10),
  startingAfter: z.string().optional(),
  endingBefore: z.string().optional(),
  includeArchived: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    startingAfter: "starting_after",
    endingBefore: "ending_before",
    includeArchived: "include_archived",
  });
});

export function listMetersRequestToJSON(
  listMetersRequest: ListMetersRequest,
): string {
  return JSON.stringify(
    ListMetersRequest$outboundSchema.parse(listMetersRequest),
  );
}
export function listMetersRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListMetersRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMetersRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMetersRequest' from JSON`,
  );
}

/** @internal */
export const ListMetersResponse$inboundSchema: z.ZodType<
  ListMetersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.MeterListApiResponseDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListMetersResponse$Outbound = {
  Result: components.MeterListApiResponseDto$Outbound;
};

/** @internal */
export const ListMetersResponse$outboundSchema: z.ZodType<
  ListMetersResponse$Outbound,
  z.ZodTypeDef,
  ListMetersResponse
> = z.object({
  result: components.MeterListApiResponseDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listMetersResponseToJSON(
  listMetersResponse: ListMetersResponse,
): string {
  return JSON.stringify(
    ListMetersResponse$outboundSchema.parse(listMetersResponse),
  );
}
export function listMetersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMetersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMetersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMetersResponse' from JSON`,
  );
}
