/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListPendingWebhookEventsRequest = {
  /**
   * The webhook ID
   */
  id: string;
  /**
   * Maximum number of pending events to return.
   */
  limit?: number | undefined;
};

/** @internal */
export const ListPendingWebhookEventsRequest$inboundSchema: z.ZodType<
  ListPendingWebhookEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  limit: z.number().int().default(50),
});
/** @internal */
export type ListPendingWebhookEventsRequest$Outbound = {
  id: string;
  limit: number;
};

/** @internal */
export const ListPendingWebhookEventsRequest$outboundSchema: z.ZodType<
  ListPendingWebhookEventsRequest$Outbound,
  z.ZodTypeDef,
  ListPendingWebhookEventsRequest
> = z.object({
  id: z.string(),
  limit: z.number().int().default(50),
});

export function listPendingWebhookEventsRequestToJSON(
  listPendingWebhookEventsRequest: ListPendingWebhookEventsRequest,
): string {
  return JSON.stringify(
    ListPendingWebhookEventsRequest$outboundSchema.parse(
      listPendingWebhookEventsRequest,
    ),
  );
}
export function listPendingWebhookEventsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListPendingWebhookEventsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPendingWebhookEventsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPendingWebhookEventsRequest' from JSON`,
  );
}
