/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListUsageEventsRequest = {
  /**
   * Only return events consumed by this meter (resolved to the meter’s event name)
   */
  meterId?: string | undefined;
  /**
   * Only return events for this customer
   */
  customerId?: string | undefined;
  /**
   * Only return the event carrying this `event_id`
   */
  reference?: string | undefined;
  /**
   * Maximum number of events to return
   */
  limit?: number | undefined;
  /**
   * Cursor for forward pagination — event ID to start after. Usage events are append-only and paginate forward only, so there is deliberately no `ending_before`.
   */
  startingAfter?: string | undefined;
};

export type ListUsageEventsResponse = {
  result: components.UsageEventListApiResponseDto;
};

/** @internal */
export const ListUsageEventsRequest$inboundSchema: z.ZodType<
  ListUsageEventsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  meter_id: z.string().optional(),
  customer_id: z.string().optional(),
  reference: z.string().optional(),
  limit: z.number().default(10),
  starting_after: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "meter_id": "meterId",
    "customer_id": "customerId",
    "starting_after": "startingAfter",
  });
});
/** @internal */
export type ListUsageEventsRequest$Outbound = {
  meter_id?: string | undefined;
  customer_id?: string | undefined;
  reference?: string | undefined;
  limit: number;
  starting_after?: string | undefined;
};

/** @internal */
export const ListUsageEventsRequest$outboundSchema: z.ZodType<
  ListUsageEventsRequest$Outbound,
  z.ZodTypeDef,
  ListUsageEventsRequest
> = z.object({
  meterId: z.string().optional(),
  customerId: z.string().optional(),
  reference: z.string().optional(),
  limit: z.number().default(10),
  startingAfter: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    meterId: "meter_id",
    customerId: "customer_id",
    startingAfter: "starting_after",
  });
});

export function listUsageEventsRequestToJSON(
  listUsageEventsRequest: ListUsageEventsRequest,
): string {
  return JSON.stringify(
    ListUsageEventsRequest$outboundSchema.parse(listUsageEventsRequest),
  );
}
export function listUsageEventsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListUsageEventsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUsageEventsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUsageEventsRequest' from JSON`,
  );
}

/** @internal */
export const ListUsageEventsResponse$inboundSchema: z.ZodType<
  ListUsageEventsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.UsageEventListApiResponseDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListUsageEventsResponse$Outbound = {
  Result: components.UsageEventListApiResponseDto$Outbound;
};

/** @internal */
export const ListUsageEventsResponse$outboundSchema: z.ZodType<
  ListUsageEventsResponse$Outbound,
  z.ZodTypeDef,
  ListUsageEventsResponse
> = z.object({
  result: components.UsageEventListApiResponseDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listUsageEventsResponseToJSON(
  listUsageEventsResponse: ListUsageEventsResponse,
): string {
  return JSON.stringify(
    ListUsageEventsResponse$outboundSchema.parse(listUsageEventsResponse),
  );
}
export function listUsageEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListUsageEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListUsageEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListUsageEventsResponse' from JSON`,
  );
}
