/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListAffiliateInvitesRequest = {
  /**
   * The page number for pagination.
   */
  pageNumber?: number | undefined;
  /**
   * The number of items per page.
   */
  pageSize?: number | undefined;
};

export type ListAffiliateInvitesResponse = {
  result: components.AffiliateInviteListEntity;
};

/** @internal */
export const ListAffiliateInvitesRequest$inboundSchema: z.ZodType<
  ListAffiliateInvitesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  page_number: z.number().default(1),
  page_size: z.number().default(50),
}).transform((v) => {
  return remap$(v, {
    "page_number": "pageNumber",
    "page_size": "pageSize",
  });
});
/** @internal */
export type ListAffiliateInvitesRequest$Outbound = {
  page_number: number;
  page_size: number;
};

/** @internal */
export const ListAffiliateInvitesRequest$outboundSchema: z.ZodType<
  ListAffiliateInvitesRequest$Outbound,
  z.ZodTypeDef,
  ListAffiliateInvitesRequest
> = z.object({
  pageNumber: z.number().default(1),
  pageSize: z.number().default(50),
}).transform((v) => {
  return remap$(v, {
    pageNumber: "page_number",
    pageSize: "page_size",
  });
});

export function listAffiliateInvitesRequestToJSON(
  listAffiliateInvitesRequest: ListAffiliateInvitesRequest,
): string {
  return JSON.stringify(
    ListAffiliateInvitesRequest$outboundSchema.parse(
      listAffiliateInvitesRequest,
    ),
  );
}
export function listAffiliateInvitesRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListAffiliateInvitesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAffiliateInvitesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAffiliateInvitesRequest' from JSON`,
  );
}

/** @internal */
export const ListAffiliateInvitesResponse$inboundSchema: z.ZodType<
  ListAffiliateInvitesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.AffiliateInviteListEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});
/** @internal */
export type ListAffiliateInvitesResponse$Outbound = {
  Result: components.AffiliateInviteListEntity$Outbound;
};

/** @internal */
export const ListAffiliateInvitesResponse$outboundSchema: z.ZodType<
  ListAffiliateInvitesResponse$Outbound,
  z.ZodTypeDef,
  ListAffiliateInvitesResponse
> = z.object({
  result: components.AffiliateInviteListEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    result: "Result",
  });
});

export function listAffiliateInvitesResponseToJSON(
  listAffiliateInvitesResponse: ListAffiliateInvitesResponse,
): string {
  return JSON.stringify(
    ListAffiliateInvitesResponse$outboundSchema.parse(
      listAffiliateInvitesResponse,
    ),
  );
}
export function listAffiliateInvitesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListAffiliateInvitesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAffiliateInvitesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAffiliateInvitesResponse' from JSON`,
  );
}
