/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PreviewExistingMeterRequest = {
  id: string;
};

/** @internal */
export const PreviewExistingMeterRequest$inboundSchema: z.ZodType<
  PreviewExistingMeterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type PreviewExistingMeterRequest$Outbound = {
  id: string;
};

/** @internal */
export const PreviewExistingMeterRequest$outboundSchema: z.ZodType<
  PreviewExistingMeterRequest$Outbound,
  z.ZodTypeDef,
  PreviewExistingMeterRequest
> = z.object({
  id: z.string(),
});

export function previewExistingMeterRequestToJSON(
  previewExistingMeterRequest: PreviewExistingMeterRequest,
): string {
  return JSON.stringify(
    PreviewExistingMeterRequest$outboundSchema.parse(
      previewExistingMeterRequest,
    ),
  );
}
export function previewExistingMeterRequestFromJSON(
  jsonString: string,
): SafeParseResult<PreviewExistingMeterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewExistingMeterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewExistingMeterRequest' from JSON`,
  );
}
