/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RetrieveSplitRequest = {
  /**
   * The unique identifier of the split
   */
  id: string;
};

/** @internal */
export const RetrieveSplitRequest$inboundSchema: z.ZodType<
  RetrieveSplitRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type RetrieveSplitRequest$Outbound = {
  id: string;
};

/** @internal */
export const RetrieveSplitRequest$outboundSchema: z.ZodType<
  RetrieveSplitRequest$Outbound,
  z.ZodTypeDef,
  RetrieveSplitRequest
> = z.object({
  id: z.string(),
});

export function retrieveSplitRequestToJSON(
  retrieveSplitRequest: RetrieveSplitRequest,
): string {
  return JSON.stringify(
    RetrieveSplitRequest$outboundSchema.parse(retrieveSplitRequest),
  );
}
export function retrieveSplitRequestFromJSON(
  jsonString: string,
): SafeParseResult<RetrieveSplitRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RetrieveSplitRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RetrieveSplitRequest' from JSON`,
  );
}
