/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ReverseCustomerCreditsTransactionRequest = {
  id: string;
};

/** @internal */
export const ReverseCustomerCreditsTransactionRequest$inboundSchema: z.ZodType<
  ReverseCustomerCreditsTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type ReverseCustomerCreditsTransactionRequest$Outbound = {
  id: string;
};

/** @internal */
export const ReverseCustomerCreditsTransactionRequest$outboundSchema: z.ZodType<
  ReverseCustomerCreditsTransactionRequest$Outbound,
  z.ZodTypeDef,
  ReverseCustomerCreditsTransactionRequest
> = z.object({
  id: z.string(),
});

export function reverseCustomerCreditsTransactionRequestToJSON(
  reverseCustomerCreditsTransactionRequest:
    ReverseCustomerCreditsTransactionRequest,
): string {
  return JSON.stringify(
    ReverseCustomerCreditsTransactionRequest$outboundSchema.parse(
      reverseCustomerCreditsTransactionRequest,
    ),
  );
}
export function reverseCustomerCreditsTransactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  ReverseCustomerCreditsTransactionRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ReverseCustomerCreditsTransactionRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ReverseCustomerCreditsTransactionRequest' from JSON`,
  );
}
