/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UnarchiveMeterRequest = {
  id: string;
};

/** @internal */
export const UnarchiveMeterRequest$inboundSchema: z.ZodType<
  UnarchiveMeterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type UnarchiveMeterRequest$Outbound = {
  id: string;
};

/** @internal */
export const UnarchiveMeterRequest$outboundSchema: z.ZodType<
  UnarchiveMeterRequest$Outbound,
  z.ZodTypeDef,
  UnarchiveMeterRequest
> = z.object({
  id: z.string(),
});

export function unarchiveMeterRequestToJSON(
  unarchiveMeterRequest: UnarchiveMeterRequest,
): string {
  return JSON.stringify(
    UnarchiveMeterRequest$outboundSchema.parse(unarchiveMeterRequest),
  );
}
export function unarchiveMeterRequestFromJSON(
  jsonString: string,
): SafeParseResult<UnarchiveMeterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UnarchiveMeterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UnarchiveMeterRequest' from JSON`,
  );
}
