/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateWebhookRequest = {
  /**
   * The webhook ID
   */
  id: string;
  /**
   * Webhook endpoint update payload
   */
  updateWebhookRequestEntity: components.UpdateWebhookRequestEntity;
};

/** @internal */
export const UpdateWebhookRequest$inboundSchema: z.ZodType<
  UpdateWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  UpdateWebhookRequestEntity:
    components.UpdateWebhookRequestEntity$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateWebhookRequestEntity": "updateWebhookRequestEntity",
  });
});
/** @internal */
export type UpdateWebhookRequest$Outbound = {
  id: string;
  UpdateWebhookRequestEntity: components.UpdateWebhookRequestEntity$Outbound;
};

/** @internal */
export const UpdateWebhookRequest$outboundSchema: z.ZodType<
  UpdateWebhookRequest$Outbound,
  z.ZodTypeDef,
  UpdateWebhookRequest
> = z.object({
  id: z.string(),
  updateWebhookRequestEntity:
    components.UpdateWebhookRequestEntity$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateWebhookRequestEntity: "UpdateWebhookRequestEntity",
  });
});

export function updateWebhookRequestToJSON(
  updateWebhookRequest: UpdateWebhookRequest,
): string {
  return JSON.stringify(
    UpdateWebhookRequest$outboundSchema.parse(updateWebhookRequest),
  );
}
export function updateWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookRequest' from JSON`,
  );
}
