/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateMeterRequest = {
  id: string;
  updateMeterApiRequestDto: components.UpdateMeterApiRequestDto;
};

/** @internal */
export const UpdateMeterRequest$inboundSchema: z.ZodType<
  UpdateMeterRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  UpdateMeterApiRequestDto: components.UpdateMeterApiRequestDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateMeterApiRequestDto": "updateMeterApiRequestDto",
  });
});
/** @internal */
export type UpdateMeterRequest$Outbound = {
  id: string;
  UpdateMeterApiRequestDto: components.UpdateMeterApiRequestDto$Outbound;
};

/** @internal */
export const UpdateMeterRequest$outboundSchema: z.ZodType<
  UpdateMeterRequest$Outbound,
  z.ZodTypeDef,
  UpdateMeterRequest
> = z.object({
  id: z.string(),
  updateMeterApiRequestDto: components.UpdateMeterApiRequestDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateMeterApiRequestDto: "UpdateMeterApiRequestDto",
  });
});

export function updateMeterRequestToJSON(
  updateMeterRequest: UpdateMeterRequest,
): string {
  return JSON.stringify(
    UpdateMeterRequest$outboundSchema.parse(updateMeterRequest),
  );
}
export function updateMeterRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateMeterRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateMeterRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateMeterRequest' from JSON`,
  );
}
