import type { FunctionReference } from "convex/server";
import type { ConnectedBillingModel } from "./model.js";
import type {
  AppPlanActivateArgs,
  CheckoutCreateArgs,
  CreditBalance,
  ConnectedTransactionList,
  SubscriptionCancelArgs,
  SubscriptionCancelScheduledUpdateArgs,
  SubscriptionResumeArgs,
  SubscriptionUpdateWireArgs,
  TransactionsSearchArgs,
} from "./types.js";

/**
 * Function reference types for the connected widget API.
 *
 * Each one pins the function kind **and** its return type, so wiring the wrong
 * generated export (for example `productsList` where `uiModel` is expected) is
 * a compile error instead of a runtime failure. Argument types are pinned too,
 * which keeps custom RBAC wrappers built on the exported arg validators
 * drop-in compatible.
 */
export type UiModelFunction = FunctionReference<
  "query",
  "public",
  Record<string, never>,
  ConnectedBillingModel
>;

export type CheckoutCreateFunction = FunctionReference<
  "action",
  "public",
  CheckoutCreateArgs,
  { url: string }
>;

/**
 * Convex requires flat object args, so the reference's arg type is the
 * permissive wire shape.
 *
 * Author payloads as {@link SubscriptionUpdateArgs} — the discriminated union —
 * and the mutation re-checks them server-side.
 */
export type SubscriptionUpdateFunction = FunctionReference<
  "mutation",
  "public",
  SubscriptionUpdateWireArgs,
  null
>;

export type SubscriptionCancelFunction = FunctionReference<
  "mutation",
  "public",
  SubscriptionCancelArgs,
  null
>;

export type SubscriptionResumeFunction = FunctionReference<
  "mutation",
  "public",
  SubscriptionResumeArgs,
  null
>;

export type SubscriptionCancelScheduledUpdateFunction = FunctionReference<
  "mutation",
  "public",
  SubscriptionCancelScheduledUpdateArgs,
  { canceled: boolean }
>;

export type CustomerPortalUrlFunction = FunctionReference<
  "action",
  "public",
  Record<string, never>,
  { url: string }
>;

export type TransactionsSearchFunction = FunctionReference<
  "action",
  "public",
  TransactionsSearchArgs,
  ConnectedTransactionList
>;

export type CreditsGetBalanceFunction = FunctionReference<
  "action",
  "public",
  Record<string, never>,
  CreditBalance
>;

export type PlansActivateFunction = FunctionReference<
  "mutation",
  "public",
  AppPlanActivateArgs,
  { success: boolean }
>;

/**
 * Backend function references for connected billing widgets.
 * Created once in your layout/page and passed to `<CreemConvexProvider>`.
 *
 * All references point to Convex functions generated by `creem.api({ resolve })`
 * or your own custom wrappers built on the exported arg validators.
 *
 * Prefer {@link connectCreemApi} over building this by hand — it maps the
 * conventional generated export names for you and fails at compile time when an
 * export is missing or has the wrong shape.
 *
 * @example
 * ```ts
 * const billingApi = connectCreemApi(api.billing);
 * ```
 */
export type ConnectedBillingApi = {
  /** Query that returns the `ConnectedBillingModel` — called by all widgets to load billing state. */
  uiModel: UiModelFunction;
  /** Checkout actions. */
  checkouts: {
    /** Create a checkout session and return `{ url }`. */
    create: CheckoutCreateFunction;
  };
  /** Subscription mutation references. All optional — omit to hide the corresponding UI controls. */
  subscriptions?: {
    /** Plan switch or unit update mutation. */
    update?: SubscriptionUpdateFunction;
    /** Cancel subscription mutation. */
    cancel?: SubscriptionCancelFunction;
    /** Resume paused/scheduled-cancel subscription mutation. */
    resume?: SubscriptionResumeFunction;
    /** Cancel an app-side period-end subscription update. */
    cancelScheduledUpdate?: SubscriptionCancelScheduledUpdateFunction;
  };
  /** Customer actions. */
  customers?: {
    /** Action that returns `{ url }` for the Creem billing portal. */
    portalUrl?: CustomerPortalUrlFunction;
  };
  /** Transaction actions. */
  transactions?: {
    /** Action that returns paginated transaction history. */
    search?: TransactionsSearchFunction;
  };
  /** Customer credit readers used by connected widgets. */
  credits?: {
    /** Get the current entity's default credit balance. */
    getBalance?: CreditsGetBalanceFunction;
  };
  /** Optional app-owned plan activation mutation. */
  plans?: {
    /** Activate an app-owned catalog plan for the current billing entity. */
    activate?: PlansActivateFunction;
  };
};

/**
 * Shape of a `convex/billing.ts` module that exports the functions generated by
 * `creem.api({ resolve })` under their conventional names.
 *
 * Only `uiModel` and `checkoutsCreate` are required; every other export is
 * optional and simply narrows what the widgets can do.
 */
export type CreemBillingModule = {
  uiModel: UiModelFunction;
  checkoutsCreate: CheckoutCreateFunction;
  subscriptionsUpdate?: SubscriptionUpdateFunction;
  subscriptionsCancel?: SubscriptionCancelFunction;
  subscriptionsResume?: SubscriptionResumeFunction;
  subscriptionsCancelScheduledUpdate?: SubscriptionCancelScheduledUpdateFunction;
  customersPortalUrl?: CustomerPortalUrlFunction;
  transactionsSearch?: TransactionsSearchFunction;
  creditsGetBalance?: CreditsGetBalanceFunction;
  plansActivate?: PlansActivateFunction;
};

const defined = <T extends object>(entries: T): T | undefined =>
  Object.values(entries).some((value) => value !== undefined)
    ? entries
    : undefined;

/**
 * Build a {@link ConnectedBillingApi} from a Convex billing module.
 *
 * Pass the generated module namespace (`api.billing`) and every capability you
 * exported is wired automatically. Exports you left out are simply absent, and
 * the matching widget controls stay hidden.
 *
 * This removes the hand-written mapping between the flat Convex export names
 * and the nested widget API — the place mis-wiring bugs used to come from.
 *
 * @example
 * ```ts
 * import { connectCreemApi } from "@creem_io/convex/react";
 * import { api } from "../convex/_generated/api";
 *
 * const billingApi = connectCreemApi(api.billing);
 * ```
 */
export const connectCreemApi = <TModule extends CreemBillingModule>(
  module: TModule,
): ConnectedBillingApi => ({
  uiModel: module.uiModel,
  checkouts: { create: module.checkoutsCreate },
  subscriptions: defined({
    update: module.subscriptionsUpdate,
    cancel: module.subscriptionsCancel,
    resume: module.subscriptionsResume,
    cancelScheduledUpdate: module.subscriptionsCancelScheduledUpdate,
  }),
  customers: defined({ portalUrl: module.customersPortalUrl }),
  transactions: defined({ search: module.transactionsSearch }),
  credits: defined({ getBalance: module.creditsGetBalance }),
  plans: defined({ activate: module.plansActivate }),
});
