/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";
import { CreemError } from "./creemerror.js";

export type UsageMeteringErrorApiResponseDtoData = {
  /**
   * Error details
   */
  error: components.UsageMeteringErrorDetailApiDto;
};

export class UsageMeteringErrorApiResponseDto extends CreemError {
  /**
   * Error details
   */
  error: components.UsageMeteringErrorDetailApiDto;

  /** The original data that was passed to this error instance. */
  data$: UsageMeteringErrorApiResponseDtoData;

  constructor(
    err: UsageMeteringErrorApiResponseDtoData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "UsageMeteringErrorApiResponseDto";
  }
}

/** @internal */
export const UsageMeteringErrorApiResponseDto$inboundSchema: z.ZodType<
  UsageMeteringErrorApiResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: components.UsageMeteringErrorDetailApiDto$inboundSchema,
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UsageMeteringErrorApiResponseDto(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UsageMeteringErrorApiResponseDto$Outbound = {
  error: components.UsageMeteringErrorDetailApiDto$Outbound;
};

/** @internal */
export const UsageMeteringErrorApiResponseDto$outboundSchema: z.ZodType<
  UsageMeteringErrorApiResponseDto$Outbound,
  z.ZodTypeDef,
  UsageMeteringErrorApiResponseDto
> = z.instanceof(UsageMeteringErrorApiResponseDto)
  .transform(v => v.data$)
  .pipe(z.object({
    error: components.UsageMeteringErrorDetailApiDto$outboundSchema,
  }));
