/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { affiliatesListInvites } from "../../funcs/affiliatesListInvites.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  pageNumber: z.number().default(1),
  pageSize: z.number().default(50),
};

export const tool$affiliatesListInvites: ToolDefinition<typeof args> = {
  name: "affiliates-list-invites",
  description: `List affiliate invitations

Retrieve a paginated list of the invitations you have sent, with their status (\`pending\` until accepted, \`accepted\` once the affiliate has joined).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await affiliatesListInvites(
      client,
      args.pageNumber,
      args.pageSize,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
