/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { affiliatesCreateInvite } from "../../funcs/affiliatesCreateInvite.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateAffiliateInviteRequestEntity$inboundSchema,
};

export const tool$affiliatesCreateInvite: ToolDefinition<typeof args> = {
  name: "affiliates-create-invite",
  description: `Create an affiliate invitation

Invite someone to your affiliate program by email. They receive an invitation email and become an active affiliate once they accept. If \`program_id\` is omitted, the invitation is created for your store's affiliate program.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await affiliatesCreateInvite(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
