/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsListTransactionsByReference } from "../../funcs/customerCreditsListTransactionsByReference.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  reference: z.string(),
};

export const tool$customerCreditsListTransactionsByReference: ToolDefinition<
  typeof args
> = {
  name: "customer-credits-list-transactions-by-reference",
  description: `List transactions by reference

List all transactions matching a reference string.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customerCreditsListTransactionsByReference(
      client,
      args.reference,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
