/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customerCreditsPostTransaction } from "../../funcs/customerCreditsPostTransaction.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.PostTransactionDto$inboundSchema,
};

export const tool$customerCreditsPostTransaction: ToolDefinition<typeof args> =
  {
    name: "customer-credits-post-transaction",
    description: `Post a transaction

Post a multi-entry transaction. Entries must balance (total debits must equal total credits).`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await customerCreditsPostTransaction(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
