/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsGetTransaction } from "../../funcs/customerCreditsGetTransaction.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$customerCreditsGetTransaction: ToolDefinition<typeof args> = {
  name: "customer-credits-get-transaction",
  description: `Retrieve a transaction

Get details of a transaction by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customerCreditsGetTransaction(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
