/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { customerCreditsReverseTransactionById } from "../../funcs/customerCreditsReverseTransactionById.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$customerCreditsReverseTransactionById: ToolDefinition<
  typeof args
> = {
  name: "customer-credits-reverse-transaction-by-id",
  description: `Reverse a transaction

Reverse a previous transaction. Creates a new transaction that undoes the original, preserving the full history.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customerCreditsReverseTransactionById(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
