/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { eventsListEvents } from "../../funcs/eventsListEvents.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  meterId: z.string().optional(),
  customerId: z.string().optional(),
  reference: z.string().optional(),
  limit: z.number().default(10),
  startingAfter: z.string().optional(),
};

export const tool$eventsListEvents: ToolDefinition<typeof args> = {
  name: "events-list-events",
  description: `List usage events

List the usage events your store has ingested, oldest first in ingestion order, as a forward cursor page. Filters compose: by meter (resolved to the meter's event name), by customer, and by \`reference\` (the \`event_id\` you supplied). Events are returned raw — a meter's filter clauses are not applied. Usage events are append-only, so pagination is forward-only and there is no \`ending_before\`.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsListEvents(
      client,
      args.meterId,
      args.customerId,
      args.reference,
      args.limit,
      args.startingAfter,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
