/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsPreviewEvents } from "../../funcs/eventsPreviewEvents.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.IngestUsageEventsApiRequestDto$inboundSchema,
};

export const tool$eventsPreviewEvents: ToolDefinition<typeof args> = {
  name: "events-preview-events",
  description: `Preview usage events

Dry-run of \`POST /v1/events/ingest\`: send the exact batch you would ingest and get a per-event report of what would happen — **nothing is stored**.

For each event: whether it passes validation (invalid events are reported in place instead of rejecting the batch, unlike ingest), the \`event_id\` it would be recorded under, whether it would deduplicate against an already-stored event or an earlier entry of the same batch (advisory — another writer can land between preview and ingest), the active meters that would consume it, and the same warnings ingest returns.

Usage events are immutable once ingested, so preview is the way to gain first-run confidence: wire your integration against preview, check \`valid\` is true and every event matches the meters you expect, then switch the path to \`ingest\`.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsPreviewEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
