/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { metersGetConsumedUnits } from "../../funcs/metersGetConsumedUnits.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  customerId: z.string(),
  at: z.string().optional(),
};

export const tool$metersGetConsumedUnits: ToolDefinition<typeof args> = {
  name: "meters-get-consumed-units",
  description: `Get consumed units for a customer

How many units a customer has consumed through this meter in a billing period, alongside the period's boundaries. Without \`at\`, this is an O(1) read of the current period's projection — the number billing uses. With \`at\`, the units are replayed from the raw events as of that instant, within the billing period containing it, which is the right call for reconstructing what a customer had consumed at a past moment (an invoice date, a support question).`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metersGetConsumedUnits(
      client,
      args.id,
      args.customerId,
      args.at,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
