/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { metersUpdateMeter } from "../../funcs/metersUpdateMeter.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  updateMeterApiRequestDto: components.UpdateMeterApiRequestDto$inboundSchema,
};

export const tool$metersUpdateMeter: ToolDefinition<typeof args> = {
  name: "meters-update-meter",
  description: `Update a meter

Rename a meter and/or revise its definition. A rename is always allowed — the name is a label no aggregate depends on — but it must stay unique within the store (409 meter_name_taken). Definition changes (filter, aggregation, aggregation_property) are only accepted while the meter has processed no usage and has no associated purchase; otherwise the request is rejected with 409, because editing the definition would silently rewrite what already-recorded usage means. Send aggregation_property as null to clear it; omit it to leave it unchanged.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metersUpdateMeter(
      client,
      args.id,
      args.updateMeterApiRequestDto,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
