/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { metersGetMeter } from "../../funcs/metersGetMeter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$metersGetMeter: ToolDefinition<typeof args> = {
  name: "meters-get-meter",
  description: `Retrieve a meter

Get one meter by ID. Archived meters ARE returned here — a fetch by explicit ID is an intentional lookup.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metersGetMeter(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
