/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { metersPreviewExistingMeter } from "../../funcs/metersPreviewExistingMeter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$metersPreviewExistingMeter: ToolDefinition<typeof args> = {
  name: "meters-preview-existing-meter",
  description: `Preview an existing meter

Dry-run an existing meter against your real usage over the last 7 whole UTC days (today included, future-dated events excluded). Same shape as the unsaved-definition preview; nothing is written.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metersPreviewExistingMeter(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
