/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { metersListMeters } from "../../funcs/metersListMeters.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  limit: z.number().default(10),
  startingAfter: z.string().optional(),
  endingBefore: z.string().optional(),
  includeArchived: z.boolean().default(false),
};

export const tool$metersListMeters: ToolDefinition<typeof args> = {
  name: "meters-list-meters",
  description: `List meters

List your meters, newest first, as a cursor page. Archived meters are hidden unless include_archived=true.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metersListMeters(
      client,
      args.limit,
      args.startingAfter,
      args.endingBefore,
      args.includeArchived,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
