/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metersCreateMeter } from "../../funcs/metersCreateMeter.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateMeterApiRequestDto$inboundSchema,
};

export const tool$metersCreateMeter: ToolDefinition<typeof args> = {
  name: "meters-create-meter",
  description: `Create a meter

Define how a stream of usage events is aggregated into billable units. The unit label doubles as the display unit and as the credit bucket the meter settles into. A duplicate name within the store is rejected with 409 meter_name_taken.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metersCreateMeter(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
