/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { splitsDelete } from "../../funcs/splitsDelete.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$splitsDelete: ToolDefinition<typeof args> = {
  name: "splits-delete",
  description: `Delete a split

Delete a split by ID. The split stops applying to future payments immediately. Splits belonging to another store cannot be deleted.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await splitsDelete(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
