/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { splitsCreate } from "../../funcs/splitsCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.CreateSplitRequestEntity$inboundSchema,
};

export const tool$splitsCreate: ToolDefinition<typeof args> = {
  name: "splits-create",
  description: `Create a split

Create a revenue split for your store. The split applies either to your whole store (\`type: store\`) or to a single product (\`type: product\`). Recipients are existing stores (added directly) or email invitees; a split created with any email invitee starts disabled and activates once the first invitee accepts. The split is always created for the store the API key belongs to.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await splitsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
