/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { webhooksListPendingEvents } from "../../funcs/webhooksListPendingEvents.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  limit: z.number().int().default(50),
};

export const tool$webhooksListPendingEvents: ToolDefinition<typeof args> = {
  name: "webhooks-list-pending-events",
  description: `List pending events for a CLI webhook endpoint

Events recorded for a \`cli\` delivery-mode endpoint that have not been acknowledged yet, oldest first. Each item carries the exact request body and headers an HTTP delivery would send. Forward them to your local server, then acknowledge each event with the status it returned. Only valid for endpoints created with \`delivery_mode: cli\`.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksListPendingEvents(
      client,
      args.id,
      args.limit,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
