/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { webhooksGetSecret } from "../../funcs/webhooksGetSecret.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$webhooksGetSecret: ToolDefinition<typeof args> = {
  name: "webhooks-get-secret",
  description: `Retrieve a webhook signing secret

Retrieve the signing secret for a webhook endpoint, used to verify delivery signatures.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksGetSecret(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
