/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { webhooksList } from "../../funcs/webhooksList.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  pageNumber: z.number().default(1),
  pageSize: z.number().default(10),
};

export const tool$webhooksList: ToolDefinition<typeof args> = {
  name: "webhooks-list",
  description: `List webhook endpoints

List the webhook endpoints configured for your store.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksList(
      client,
      args.pageNumber,
      args.pageSize,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
