/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { webhooksUpdate } from "../../funcs/webhooksUpdate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  updateWebhookRequestEntity:
    components.UpdateWebhookRequestEntity$inboundSchema,
};

export const tool$webhooksUpdate: ToolDefinition<typeof args> = {
  name: "webhooks-update",
  description: `Update a webhook endpoint

Update the URL, name, status or event filter of a webhook endpoint. Only supplied fields change.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksUpdate(
      client,
      args.id,
      args.updateWebhookRequestEntity,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
