/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { webhooksDelete } from "../../funcs/webhooksDelete.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
};

export const tool$webhooksDelete: ToolDefinition<typeof args> = {
  name: "webhooks-delete",
  description: `Delete a webhook endpoint

Permanently delete a webhook endpoint and its delivery history. To pause deliveries without losing the configuration, update the status to disabled instead.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksDelete(
      client,
      args.id,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
