/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { webhooksAcknowledgeEvent } from "../../funcs/webhooksAcknowledgeEvent.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  id: z.string(),
  eventId: z.string(),
  acknowledgeWebhookEventRequestEntity:
    components.AcknowledgeWebhookEventRequestEntity$inboundSchema,
};

export const tool$webhooksAcknowledgeEvent: ToolDefinition<typeof args> = {
  name: "webhooks-acknowledge-event",
  description: `Acknowledge a CLI webhook event

Report the status your local server returned for an event from the pending feed. Any 2xx marks the delivery successful; anything else records a failure. Acknowledged events leave the pending feed and appear in the dashboard event log with the reported result. Only valid for endpoints created with \`delivery_mode: cli\`.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksAcknowledgeEvent(
      client,
      args.id,
      args.eventId,
      args.acknowledgeWebhookEventRequestEntity,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
